import createClient from "openapi-fetch";
import { PUBLIC_GO_BACKEND_URL } from "$env/static/public";
import { getLocale } from "$paraglide/runtime";
import type { paths } from "./schema";

/**
 * Generated typed client for the Go backend (../../../backend). Types come
 * from schema.d.ts (generated by `openapi-typescript` from the Go API's
 * own OpenAPI spec - see backend/DESIGN.md's "API shape and frontend
 * integration" section). Call it directly at call sites, e.g.
 * `api.GET("/articles/{slug}", { params: { path: { slug } } })` - no
 * hand-written wrapper functions per endpoint.
 *
 * Lives outside $lib/server because SvelteKit's universal `+page.ts` loads
 * call this API directly from the browser as well as the server (see
 * DESIGN.md's "Fetch from the client" decision) - a `$lib/server` module
 * cannot be imported from code that also runs client-side.
 *
 * `credentials: "include"` below only matters for a real browser fetch -
 * the browser's own cookie jar attaches the session cookie and stores any
 * Set-Cookie response automatically, no code needed. It does nothing when
 * this same call executes inside the Node process itself (SSR of a
 * `+page.ts`, or any `+page.server.ts` load/action) - there's no browser
 * involved in a server-to-server request, so nothing forwards cookies
 * either direction on its own (same reason goAuth.ts's fetchIdentity()
 * has always forwarded /me's cookies by hand). `+page.server.ts` files
 * use `$lib/server/apiClient`'s `serverApi(event)` instead, which
 * forwards cookies explicitly (found and fixed 2026-09-02 - see
 * backend/DESIGN.md's note on this). A `+page.ts` load can't do that (no
 * server-only imports, no raw cookie access) - every call site here
 * already passes its own `fetch` parameter into each `api.*()` call
 * (`api.GET(..., { fetch })`), which is the correct, established
 * pattern: it lets SvelteKit's built-in same-site cookie passthrough
 * apply during SSR, best-effort. Keep doing this for any new `+page.ts`
 * call site - it's free and can only help, even though (see DESIGN.md)
 * it isn't a complete guarantee independent of prod domain topology.
 */
export const api = createClient<paths>({
  baseUrl: PUBLIC_GO_BACKEND_URL,
  // The session cookie (backend/internal/auth) must ride along on every
  // request now that real auth exists - the backend's CORS layer
  // (internal/api.withCORS) only allows this because it echoes this site's
  // own origin rather than "*" (browsers reject that combination for
  // credentialed requests).
  credentials: "include",
});

// The Go API resolves translated fields from Accept-Language (see
// backend/internal/locale) - send the site's actual selected locale
// (paraglide's getLocale(), which can differ from the browser's own
// language settings if the user picked a language via the site's own
// switcher) rather than leaving the browser's default header in place.
api.use({
  onRequest({ request }) {
    request.headers.set("Accept-Language", getLocale());
    return request;
  },
});
