import createClient from "openapi-fetch";
import { PUBLIC_GO_BACKEND_URL } from "$env/static/public";
import { getLocale } from "$paraglide/runtime";
import type { paths } from "./schema";

/**
 * Generated typed client for the Go backend (../../../backend). Types come
 * from schema.d.ts (generated by `openapi-typescript` from the Go API's
 * own OpenAPI spec - see backend/DESIGN.md's "API shape and frontend
 * integration" section). Call it directly at call sites, e.g.
 * `api.GET("/articles/{slug}", { params: { path: { slug } } })` - no
 * hand-written wrapper functions per endpoint.
 *
 * Lives outside $lib/server because SvelteKit's universal `+page.ts` loads
 * call this API directly from the browser as well as the server (see
 * DESIGN.md's "Fetch from the client" decision) - a `$lib/server` module
 * cannot be imported from code that also runs client-side.
 */
export const api = createClient<paths>({
  baseUrl: PUBLIC_GO_BACKEND_URL,
  // The session cookie (backend/internal/auth) must ride along on every
  // request now that real auth exists - the backend's CORS layer
  // (internal/api.withCORS) only allows this because it echoes this site's
  // own origin rather than "*" (browsers reject that combination for
  // credentialed requests).
  credentials: "include",
});

// The Go API resolves translated fields from Accept-Language (see
// backend/internal/locale) - send the site's actual selected locale
// (paraglide's getLocale(), which can differ from the browser's own
// language settings if the user picked a language via the site's own
// switcher) rather than leaving the browser's default header in place.
api.use({
  onRequest({ request }) {
    request.headers.set("Accept-Language", getLocale());
    return request;
  },
});
