/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published articles */
        get: operations["list-articles"];
        put?: never;
        /** Create an article */
        post: operations["create-article"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an article by slug */
        get: operations["get-article"];
        put?: never;
        post?: never;
        /** Soft-delete an article */
        delete: operations["delete-article"];
        options?: never;
        head?: never;
        /** Replace an article (full-replace, not a partial patch) */
        patch: operations["update-article"];
        trace?: never;
    };
    "/articles/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comment on an article as the acting member */
        post: operations["create-comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a comment */
        delete: operations["delete-comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Like an article as the acting member */
        post: operations["like-article"];
        /** Unlike an article as the acting member */
        delete: operations["unlike-article"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Record the external scheduler task id for a future publish */
        patch: operations["set-article-schedule"];
        trace?: never;
    };
    "/committees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List committees, optionally filtered to one by shortName */
        get: operations["list-committees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/custom-authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List custom (non-member) bylines */
        get: operations["list-custom-authors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events */
        get: operations["list-events"];
        put?: never;
        /** Create an event, or a recurring series if Body.recurring is set */
        post: operations["create-event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an event by slug */
        get: operations["get-event"];
        put?: never;
        post?: never;
        /** Soft-delete an event */
        delete: operations["delete-event"];
        options?: never;
        head?: never;
        /** Replace an event (full-replace, not a partial patch) */
        patch: operations["update-event"];
        trace?: never;
    };
    "/events/{slug}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set the acting member's going/interested/none status */
        patch: operations["set-event-attendance"];
        trace?: never;
    };
    "/events/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comment on an event as the acting member */
        post: operations["create-event-comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{slug}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a comment */
        delete: operations["delete-event-comment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/members/{id}/mandates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a member's currently-active mandates */
        get: operations["list-member-mandates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tags */
        get: operations["list-tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an image (storage is mocked, see internal/integrations) */
        post: operations["upload-image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArticleDetail: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ArticleDetail.json
             */
            readonly $schema?: string;
            author: components["schemas"]["Author"];
            body: string;
            bodyEn?: string;
            bodySv: string;
            /** Format: int64 */
            commentCount: number;
            comments: components["schemas"]["Comment"][] | null;
            committee?: components["schemas"]["Committee"];
            /** Format: date-time */
            createdAt: string;
            header: string;
            headerEn?: string;
            headerSv: string;
            id: string;
            imageUrl?: string;
            imageUrls?: string[] | null;
            /** Format: int64 */
            likeCount: number;
            notificationText?: string;
            /** Format: date-time */
            publishedAt?: string;
            scheduledId?: string;
            sendNotification: boolean;
            slug: string;
            status?: string;
            tags: components["schemas"]["Tag"][] | null;
            /** Format: date-time */
            updatedAt?: string;
            youtubeUrl?: string;
        };
        ArticleInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ArticleInput.json
             */
            readonly $schema?: string;
            author: components["schemas"]["AuthorInput"];
            bodyEn: string | null;
            bodySv: string;
            committeeId: string | null;
            headerEn: string | null;
            headerSv: string;
            imageUrl: string | null;
            imageUrls: string[] | null;
            notificationText: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            sendNotification: boolean;
            tagIds: string[] | null;
            youtubeUrl: string | null;
        };
        ArticleSummary: {
            author: components["schemas"]["Author"];
            body: string;
            bodyEn?: string;
            bodySv: string;
            /** Format: int64 */
            commentCount: number;
            committee?: components["schemas"]["Committee"];
            /** Format: date-time */
            createdAt: string;
            header: string;
            headerEn?: string;
            headerSv: string;
            id: string;
            imageUrl?: string;
            imageUrls?: string[] | null;
            /** Format: int64 */
            likeCount: number;
            notificationText?: string;
            /** Format: date-time */
            publishedAt?: string;
            scheduledId?: string;
            sendNotification: boolean;
            slug: string;
            status?: string;
            tags: components["schemas"]["Tag"][] | null;
            /** Format: date-time */
            updatedAt?: string;
            youtubeUrl?: string;
        };
        Author: {
            customAuthor?: components["schemas"]["CustomAuthor"];
            id: string;
            member: components["schemas"]["Member"];
            position?: components["schemas"]["Position"];
            type: string;
        };
        AuthorInput: {
            customId?: string;
            mandateId?: string;
        };
        Comment: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Comment.json
             */
            readonly $schema?: string;
            content?: string;
            id: string;
            member: components["schemas"]["Member"];
            /** Format: date-time */
            published: string;
        };
        Committee: {
            id: string;
            name: string;
            nameEn?: string;
            nameSv: string;
            shortName?: string;
            symbolUrl?: string;
        };
        CreateCommentInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateCommentInputBody.json
             */
            readonly $schema?: string;
            content: string;
        };
        CreateEventCommentInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateEventCommentInputBody.json
             */
            readonly $schema?: string;
            content: string;
        };
        CustomAuthor: {
            id: string;
            imageUrl?: string;
            name: string;
            nameEn?: string;
            nameSv: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        EventDetail: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/EventDetail.json
             */
            readonly $schema?: string;
            alarmActive: boolean;
            author: components["schemas"]["Member"];
            /** Format: int64 */
            commentCount: number;
            comments: components["schemas"]["Comment"][] | null;
            description: string;
            descriptionEn?: string;
            descriptionSv: string;
            /** Format: date-time */
            endAt: string;
            going: components["schemas"]["Member"][] | null;
            /** Format: int64 */
            goingCount: number;
            id: string;
            imageUrl?: string;
            interested: components["schemas"]["Member"][] | null;
            /** Format: int64 */
            interestedCount: number;
            isCancelled: boolean;
            link?: string;
            location?: string;
            organizer: string;
            recurringParentId?: string;
            shortDescription?: string;
            shortDescriptionEn?: string;
            shortDescriptionSv?: string;
            slug: string;
            /** Format: date-time */
            startAt: string;
            tags: components["schemas"]["Tag"][] | null;
            title: string;
            titleEn?: string;
            titleSv: string;
        };
        EventInput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/EventInput.json
             */
            readonly $schema?: string;
            alarmActive: boolean;
            descriptionEn: string | null;
            descriptionSv: string;
            /** Format: date-time */
            endAt: string;
            imageUrl: string | null;
            isCancelled: boolean;
            link: string | null;
            location: string | null;
            organizer: string;
            recurring?: components["schemas"]["RecurringInput"];
            shortDescriptionEn: string | null;
            shortDescriptionSv: string | null;
            /** Format: date-time */
            startAt: string;
            tagIds: string[] | null;
            titleEn: string | null;
            titleSv: string;
        };
        EventSummary: {
            alarmActive: boolean;
            author: components["schemas"]["Member"];
            /** Format: int64 */
            commentCount: number;
            description: string;
            descriptionEn?: string;
            descriptionSv: string;
            /** Format: date-time */
            endAt: string;
            /** Format: int64 */
            goingCount: number;
            id: string;
            imageUrl?: string;
            /** Format: int64 */
            interestedCount: number;
            isCancelled: boolean;
            link?: string;
            location?: string;
            organizer: string;
            recurringParentId?: string;
            shortDescription?: string;
            shortDescriptionEn?: string;
            shortDescriptionSv?: string;
            slug: string;
            /** Format: date-time */
            startAt: string;
            tags: components["schemas"]["Tag"][] | null;
            title: string;
            titleEn?: string;
            titleSv: string;
        };
        ListArticlesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListArticlesOutputBody.json
             */
            readonly $schema?: string;
            articles: components["schemas"]["ArticleSummary"][] | null;
            /** Format: int64 */
            pageCount: number;
        };
        ListEventsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListEventsOutputBody.json
             */
            readonly $schema?: string;
            events: components["schemas"]["EventSummary"][] | null;
            /** Format: int64 */
            pageCount: number;
        };
        Mandate: {
            id: string;
            position: components["schemas"]["Position"];
        };
        Member: {
            firstName?: string;
            id: string;
            lastName?: string;
            nickname?: string;
            picturePath?: string;
            studentId?: string;
        };
        Position: {
            id: string;
            name: string;
            nameEn?: string;
            nameSv: string;
        };
        RecurringInput: {
            /** Format: date-time */
            endAt: string;
            /** Format: int64 */
            separationCount: number;
            type: string;
        };
        SetAttendanceInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetAttendanceInputBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            status: "going" | "interested" | "none";
        };
        SetScheduleInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SetScheduleInputBody.json
             */
            readonly $schema?: string;
            scheduledId: string;
        };
        Tag: {
            color?: string;
            id: string;
            isDefault: boolean;
            name: string;
            nameEn?: string;
            nameSv: string;
        };
        UploadOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UploadOutputBody.json
             */
            readonly $schema?: string;
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-articles": {
        parameters: {
            query?: {
                /** @description free-text search over header/body */
                search?: string;
                /** @description tag UUIDs, ANY-match */
                tags?: string[] | null;
                committeeId?: string;
                authorStudentId?: string;
                /** @description 1-based */
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListArticlesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-article": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-article": {
        parameters: {
            query?: {
                /** @description pass 'any' to bypass the publish/removed filter, for an author viewing their own draft or scheduled article */
                status?: "any";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-article": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-article": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-comment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-comment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "like-article": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "unlike-article": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-article-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetScheduleInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-committees": {
        parameters: {
            query?: {
                shortName?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Committee"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-custom-authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomAuthor"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-events": {
        parameters: {
            query?: {
                /** @description free-text search over title/description */
                search?: string;
                /** @description tag UUIDs, ANY-match */
                tags?: string[] | null;
                /** @description list past events (ended) instead of upcoming ones */
                past?: boolean;
                /** @description 1-based */
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEventsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-event": {
        parameters: {
            query?: {
                /** @description pass 'any' to bypass the removed filter, for an editor viewing a soft-removed event */
                status?: "any";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-event": {
        parameters: {
            query?: {
                /** @description how a recurring series is affected; defaults to THIS */
                scope?: "THIS" | "FUTURE" | "ALL";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-event": {
        parameters: {
            query?: {
                /** @description how a recurring series is affected; defaults to THIS */
                scope?: "THIS" | "FUTURE" | "ALL";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-event-attendance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAttendanceInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-event-comment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventCommentInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-event-comment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-member-mandates": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mandate"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "upload-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
