use_global = false

dictionaries = [ 'en_gb' ]

ignore_paths = [
    '**/pnpm-lock.yaml',
    'scheduler-service/go.sum',
    'src/database/prisma/migrations/**',
    'src/database/prisma/schema.prisma',
]

ignore_patterns = [
    # Names
    'AF Bostäder',
    'AF-borgen',
    'BoPoolen',
    'D-Chip',
    'D-sektionen inom TLTH',
    'Fr\*nch',
    'Gammal && Äcklig',
    'IBM Plex',
    'iDét',
    'RåsenbaD',
    'SEK',
    'YouTube',

    # Technical
    '&shy;', # Soft-hyphen
    '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', # Email
    'iCal',
    'github\.com/Dsek-LTH',
    '[A-Za-z0-9+/]{40,}', # Base64 data of 40+ characters.

    # Abbreviations (only allowed in lower case)
    'dchip',
    'dguild',
    'dsek',
    'gammal_och_äcklig',
    'infocom',

    # Swedish words sanctioned for code use.
    '[Nn]0lla',
    '[Nn]0llegasque',
    '[Nn]0llegeneral',
    '[Nn]0llning',
    '[Nn]0llor', # This looks better than the English or null plural-form.
]

words = [
    'accelerometer',
    'adapters',
    'approvements',
    'blop',
    'bookables',
    'breakpoint',
    'café',
    'checkboxes',
    'cli',
    'contentful',
    'cta', # Call To Action
    'enforceability',
    'funsies',
    'gyckle',
    'licensor',
    'Oklch',
    'purchasables',
    'selectable',
    'shortener',
    'shoppable',
    'strikethrough', # Noun
    'sublicensable',
    'sublicense',
    'subprocessor',
    'unapprove',
    'unapproving',
    'unconsume',
    'unbooked',
    'unported',
    'webshop',
    'wikia',
    'woggle',
    'öre',

    # Names
    'Agardh', # Head Processor 2026
    'CSN',
    'Datagården',
    'Gehlsdorf', # Treasurer 2026
    'Helander', # Head of Facilities 2026
    'Hemberg', # Auditor 2026
    'Kiosken',
    'Kämnärsrätten',
    'LTH',
    'Lund',
    'Québec',
    'Repobeats',
    'Rilde', # Auditor 2026
    'Råsa',
    'Råsenbad',
    'Sjøn',
    'SRD',
    'Studentlund',
    'Svensson', # Guild President 2026
    'Teknologkåren',
    'TLTH',

    # Tools
    'authentik',
    'cjs',
    'clsx',
    'croppie',
    'dayjs',
    'dompurify',
    'Dynmap',
    'embla',
    'inlang',
    'Meili',
    'Meilisearch',
    'MinIO',
    'nodemailer',
    'paraglide',
    'pnpm',
    'postcss',
    'prisma',
    'Stocklist',
    'tiptap',
    'vaul',
    'vercel',
    'vitest',
    'zenstack',
    'zod',

    # Guild-specific words
    'Cheps',
    'Gasque',
    'gyckle',
    'gyckles',
    'Ouveralle',
    'Ouvve',
    'Shäraton',
    'Singbook',
    'Slasque',
    'spex',
    'VTM',
    'Øverphøs',

    # Swedish words sanctioned for code use.
    "sexet's",
    'Källarmästare',
    'Peppare',
    'phadder',
    'phadders',
    'Stab',
    'yrka',
    'yrkande',
    'Øverpeppare',
    'Processmästare',
    'Skattmästare',
    'Revisor',
    'Ordförande',
]

[[overrides]] # Swedish
paths = [
    'src/translations/sv.json',
    'src/routes/(app)/privacy-policy/+page.svelte',
]
dictionaries = [ 'sv' ]
extra_ignore_patterns = [
    '[Nn]0llades',
    '[Nn]0llan',
    '[Nn]0llans',
    '[Nn]0llepolicy',
    '[Nn]0llningen',
    '[Nn]0llningens',
    '[Nn]0llningsevent',
    '[Nn]0llningsnyheter',
    '[Nn]0llningspolicy',
    '[Nn]0llorna',
    'enl\.',

    # Names
    'StiL',

    # Bugs in codebook.
    '\\nön',
]
words = [
    'admininställningar',
    'aliaset',
    'dagsansvarig',
    'datan',
    'filsökväg',
    'ickefungerande',
    'issue', # 'Issue' as in 'GitHub issue' is well established terminology.
    'jättestängd',
    'LAN',
    'länkförkortare',
    'mejlalias',
    'mejlaliaset',
    'mötesår',
    'notistext',
    'nyhetstaggar',
    'onajs',
    'ping',
    'skojsigt',
    'spegatklädd',
    'spärrningsregler',
    'taggnamn',
    'wikia',

    # Names
    'Dagisar',
    'Delphi',
    'Kallini', # Subprocessor 2026
    'Ohrgren', # Head of Frontend 2026
    'Råsenbad',
    'Shäraton',
    'Sjøn',
    'Studentlund',
    'tlth',

    # Tools
    'authentik',
    'Dynmap',
    'Orbi',
    'Stocklist',

    # Guild-specific words
    'Cheps',
    'Delphivrål',
    'Gasque',
    'gyckle',
    'matpref',
    'Nollegasque',
    'Nollegeneral',
    'Ouveralle',
    'Ouvve',
    'ouvven',
    'peppare',
    'Pepparnas',
    'phadder',
    'phaddergrupp',
    'phaddergruppen',
    'phaddergrupper',
    'phaddrar',
    'phaddrarna',
    'policykod',
    'Råsa',
    'Sjungbok',
    'Slasque',
    'slasquen',
    'SRD',
    'Studentlunds',
    'trivselråd',
    'trivselrådet',
    'träningsphasen',
    'Øverpeppare',
    'VTM',
]

flag_words = [
    'gyckel'
]

[[overrides]] # Commands
paths = [
    'dev/README.md',
    'dev/setup.ts',
    'Dockerfile',
    'README.md',
]
extra_ignore_patterns = [
    'chmod\s[ugoa]?[-+=][rwxXstugo]+',
    'pg_isready',
]
extra_words = [
    'chmod',
    'chown',
    'lsof',
    'mkdir',
    'openssl',
    'pnpm',
]

[[overrides]] # CSS
paths = [
    '**/*.css',
    '**/*.svelte',
    'src/translations/*.json',
]
extra_ignore_patterns = [
    'font-extrabold',
    'h-dvh',
    'scroll-behavior',
    'w-dvw',
]

[[overrides]] # SVG
paths = [ '**/*.svg' ]
extra_words = [
    'dasharray',
    'miterlimit',
    'xlink',
]

# Configs for specific files.

[[overrides]]
paths = [ 'AGENTS.md' ]
extra_words = [ 'mcp' ]

[[overrides]]
paths = [ '**/Dockerfile' ]
extra_ignore_patterns = [
    'gcr\.io/distroless',
    'USER nonroot:nonroot',
]

[[overrides]]
paths = [ 'LICENSE' ]
extra_ignore_patterns = [
    'CeCILL' # Some Fr*nch license
]
extra_words = [
    'agpl', # Affero General Public License
    'epl', # Eclipse Public License
    'eupl', # EU Public License
    'osl', # Open Software License
]

[[overrides]]
paths = [ '**/Makefile' ]
extra_ignore_patterns = [
    'PHONY', # Case sensitive
]

[[overrides]]
paths = [ 'README.md' ]
extra_words = [
    'EUPL',
]

[[overrides]]
paths = [
    "scheduler-service/go.mod",
    "scheduler-service/Makefile",
]
extra_words = [
    # Tools
    'goimports',
    'gorm',

    # Tool Authors
    'alecthomas',
    'goccy',
    'jinzhu',
    'rogpeppe',
    'segmentio',
    'xhit',

    # Tools with Authors
    'golines', 'golangci',
    'fastjson', 'valyala',
    'structtags', 'ldez',
    'pgpassfile', 'jackc',
    'pgservicefile',
    'pgx',
    'dcrd', 'decred',
    'dcrec',
    'godotenv', 'joho',
    'gofumpt', 'mvdan',
    'blackmagic', 'lestrrat',
    'dsig',
    'httpcc',
    'httprc',
    'jwx',
    'secp',
]

[[overrides]]
paths = [ 'scheduler-service/databaseHandler.go' ]
extra_words = [
    'DSN', # Database Source Name
    'dbname', # Part of the source name
    'sslmode', # Part of the source name
]

[[overrides]]
paths = [ 'shell.nix' ]
extra_words = [
    'nixpkgs',
    'pkgs',
]

[[overrides]] # TODO: Remove this.
paths = [ 'src/translations/en.json' ]
extra_ignore_patterns = [
    'href=\\".*?\\"',
]

[[overrides]]
paths = [ 'src/translations/sv.json' ]
extra_ignore_patterns = [
    '".*":', # The JSON keys are english and spellchecked in the english version.
    '\{\w+\}', # The parameters are english and spellchecked in the english version.
    'href=\\".*?\\"', # Routes are english and spellchecked in the english version.

    '[kåååst]', # Phonetic notation.
    'font-extrabold', # CSS class
    'Software Engineering', # A specialisation.
]

[[overrides]]
paths = [ 'codebook.toml' ]
extra_ignore_patterns = [
    # This monstrosity matches toml strings.
    # We only want to lint the comments in this file.
    "\"\"\"(?:\\\\.|[^\\\\])*?\"\"\"|'''[\\s\\S]*?'''|\"(?:\\\\.|[^\"\\\\\\n])*\"|'[^'\\n]*'"
]

[[overrides]]
paths = [ 'src/database/seed/data.ts' ]
# We just ignore all string, kind of a cop-out but this data is not important.
extra_ignore_patterns = [
    '".*?"',
    '`.*?`',
]

[[overrides]]
paths = [ 'src/routes/(app)/songbook/helpers.ts' ]
extra_ignore_patterns = [ 'e\.g\. ".*?"' ] # Song category examples.


[[overrides]]
paths = [ 'src/routes/(app)/salto/[door]/constants.ts' ]
# This file contains names and positions in Swedish.
extra_words = [
    'Processmästare',
]
