// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TicketQueueEntry struct {
	ID             pgtype.UUID        `json:"id"`
	ReleaseID      pgtype.UUID        `json:"release_id"`
	MemberID       string             `json:"member_id"`
	Status         string             `json:"status"`
	QueuePosition  pgtype.Int4        `json:"queue_position"`
	OfferExpiresAt pgtype.Timestamptz `json:"offer_expires_at"`
	RequestedAt    pgtype.Timestamptz `json:"requested_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TicketRelease struct {
	ID                 pgtype.UUID        `json:"id"`
	EventID            pgtype.UUID        `json:"event_id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Location           string             `json:"location"`
	Quantity           int32              `json:"quantity"`
	OpensAt            pgtype.Timestamptz `json:"opens_at"`
	ClosesAt           pgtype.Timestamptz `json:"closes_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	GraceWindowSeconds int32              `json:"grace_window_seconds"`
	OfferWindowSeconds int32              `json:"offer_window_seconds"`
	Status             string             `json:"status"`
	CreatedBy          string             `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
