// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptEntry(ctx context.Context, arg AcceptEntryParams) (int64, error)
	CancelEntry(ctx context.Context, arg CancelEntryParams) (int64, error)
	CountGrantedOrAccepted(ctx context.Context, releaseID pgtype.UUID) (int64, error)
	CountWaitlisted(ctx context.Context, releaseID pgtype.UUID) (int64, error)
	CreateRelease(ctx context.Context, arg CreateReleaseParams) (TicketRelease, error)
	DecrementWaitlistPositions(ctx context.Context, arg DecrementWaitlistPositionsParams) error
	ExpireEntry(ctx context.Context, id pgtype.UUID) error
	GetQueueEntry(ctx context.Context, arg GetQueueEntryParams) (TicketQueueEntry, error)
	// Not filtered by expires_at - old releases are kept in the database (not
	// purged) and stay reachable directly, e.g. for an admin reviewing a past
	// event's attendee list. They're just excluded from the listings below.
	GetRelease(ctx context.Context, id pgtype.UUID) (TicketRelease, error)
	GetReleaseCounts(ctx context.Context, id pgtype.UUID) (GetReleaseCountsRow, error)
	GrantEntry(ctx context.Context, arg GrantEntryParams) error
	// Idempotent: a repeat request for the same (release, member) just returns
	// the existing row unchanged instead of erroring.
	InsertQueueEntry(ctx context.Context, arg InsertQueueEntryParams) (TicketQueueEntry, error)
	// The admin roster for one release - only entries that actually hold a
	// confirmed ticket (pending/waitlisted/granted/expired/cancelled are noise
	// for "who has a ticket" purposes, and their status would always read the
	// same anyway).
	ListAcceptedEntriesForRelease(ctx context.Context, releaseID pgtype.UUID) ([]TicketQueueEntry, error)
	// The admin listing - nothing excluded, so past events stay reviewable.
	ListAllReleases(ctx context.Context) ([]TicketRelease, error)
	// A member's "my tickets" view - expired releases (event over) are excluded
	// so old tickets don't build up indefinitely.
	ListEntriesForMember(ctx context.Context, memberID string) ([]ListEntriesForMemberRow, error)
	ListExpiredGrantedForUpdate(ctx context.Context, releaseID pgtype.UUID) ([]TicketQueueEntry, error)
	ListPendingForUpdate(ctx context.Context, releaseID pgtype.UUID) ([]TicketQueueEntry, error)
	// The public/browsing listing - expired releases (event over) are excluded.
	ListReleases(ctx context.Context) ([]TicketRelease, error)
	// Releases that have at least one granted-but-unaccepted offer, used to
	// know which releases need an expiry sweep.
	ListReleasesWithActiveOffers(ctx context.Context) ([]TicketRelease, error)
	// Releases whose lottery hasn't run yet, used to re-arm in-process timers
	// after a restart.
	ListScheduledReleases(ctx context.Context) ([]TicketRelease, error)
	ListWaitlistFrontForUpdate(ctx context.Context, arg ListWaitlistFrontForUpdateParams) ([]TicketQueueEntry, error)
	LockRelease(ctx context.Context, id pgtype.UUID) (TicketRelease, error)
	SetReleaseStatus(ctx context.Context, arg SetReleaseStatusParams) error
	UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (TicketRelease, error)
	WaitlistEntry(ctx context.Context, arg WaitlistEntryParams) error
}

var _ Querier = (*Queries)(nil)
