// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptEntry = `-- name: AcceptEntry :execrows
UPDATE ticket_queue_entry
SET status = 'accepted', updated_at = now()
WHERE release_id = $1 AND member_id = $2 AND status = 'granted' AND offer_expires_at > now()
`

type AcceptEntryParams struct {
	ReleaseID pgtype.UUID `json:"release_id"`
	MemberID  string      `json:"member_id"`
}

func (q *Queries) AcceptEntry(ctx context.Context, arg AcceptEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptEntry, arg.ReleaseID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelEntry = `-- name: CancelEntry :execrows
UPDATE ticket_queue_entry
SET status = 'cancelled', updated_at = now()
WHERE release_id = $1 AND member_id = $2 AND status IN ('pending', 'granted', 'waitlisted')
`

type CancelEntryParams struct {
	ReleaseID pgtype.UUID `json:"release_id"`
	MemberID  string      `json:"member_id"`
}

func (q *Queries) CancelEntry(ctx context.Context, arg CancelEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelEntry, arg.ReleaseID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGrantedOrAccepted = `-- name: CountGrantedOrAccepted :one
SELECT count(*) FROM ticket_queue_entry
WHERE release_id = $1 AND status IN ('granted', 'accepted')
`

func (q *Queries) CountGrantedOrAccepted(ctx context.Context, releaseID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGrantedOrAccepted, releaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaitlisted = `-- name: CountWaitlisted :one
SELECT count(*) FROM ticket_queue_entry
WHERE release_id = $1 AND status = 'waitlisted'
`

func (q *Queries) CountWaitlisted(ctx context.Context, releaseID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlisted, releaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRelease = `-- name: CreateRelease :one
INSERT INTO ticket_release (
    event_id, title, description, location, quantity, opens_at, closes_at, expires_at, grace_window_seconds, offer_window_seconds, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, event_id, title, description, location, quantity, opens_at, closes_at, expires_at, grace_window_seconds, offer_window_seconds, status, created_by, created_at
`

type CreateReleaseParams struct {
	EventID            pgtype.UUID        `json:"event_id"`
	Title              string             `json:"title"`
	Description        string             `json:"description"`
	Location           string             `json:"location"`
	Quantity           int32              `json:"quantity"`
	OpensAt            pgtype.Timestamptz `json:"opens_at"`
	ClosesAt           pgtype.Timestamptz `json:"closes_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	GraceWindowSeconds int32              `json:"grace_window_seconds"`
	OfferWindowSeconds int32              `json:"offer_window_seconds"`
	CreatedBy          string             `json:"created_by"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (TicketRelease, error) {
	row := q.db.QueryRow(ctx, createRelease,
		arg.EventID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Quantity,
		arg.OpensAt,
		arg.ClosesAt,
		arg.ExpiresAt,
		arg.GraceWindowSeconds,
		arg.OfferWindowSeconds,
		arg.CreatedBy,
	)
	var i TicketRelease
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Quantity,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ExpiresAt,
		&i.GraceWindowSeconds,
		&i.OfferWindowSeconds,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const decrementWaitlistPositions = `-- name: DecrementWaitlistPositions :exec
UPDATE ticket_queue_entry
SET queue_position = queue_position - $2, updated_at = now()
WHERE release_id = $1 AND status = 'waitlisted'
`

type DecrementWaitlistPositionsParams struct {
	ReleaseID     pgtype.UUID `json:"release_id"`
	QueuePosition pgtype.Int4 `json:"queue_position"`
}

func (q *Queries) DecrementWaitlistPositions(ctx context.Context, arg DecrementWaitlistPositionsParams) error {
	_, err := q.db.Exec(ctx, decrementWaitlistPositions, arg.ReleaseID, arg.QueuePosition)
	return err
}

const expireEntry = `-- name: ExpireEntry :exec
UPDATE ticket_queue_entry SET status = 'expired', updated_at = now() WHERE id = $1
`

func (q *Queries) ExpireEntry(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expireEntry, id)
	return err
}

const getQueueEntry = `-- name: GetQueueEntry :one
SELECT id, release_id, member_id, status, queue_position, offer_expires_at, requested_at, updated_at
FROM ticket_queue_entry
WHERE release_id = $1 AND member_id = $2
`

type GetQueueEntryParams struct {
	ReleaseID pgtype.UUID `json:"release_id"`
	MemberID  string      `json:"member_id"`
}

func (q *Queries) GetQueueEntry(ctx context.Context, arg GetQueueEntryParams) (TicketQueueEntry, error) {
	row := q.db.QueryRow(ctx, getQueueEntry, arg.ReleaseID, arg.MemberID)
	var i TicketQueueEntry
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.MemberID,
		&i.Status,
		&i.QueuePosition,
		&i.OfferExpiresAt,
		&i.RequestedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, event_id, title, description, location, quantity, opens_at, closes_at, expires_at, grace_window_seconds, offer_window_seconds, status, created_by, created_at
FROM ticket_release
WHERE id = $1
`

// Not filtered by expires_at - old releases are kept in the database (not
// purged) and stay reachable directly, e.g. for an admin reviewing a past
// event's attendee list. They're just excluded from the listings below.
func (q *Queries) GetRelease(ctx context.Context, id pgtype.UUID) (TicketRelease, error) {
	row := q.db.QueryRow(ctx, getRelease, id)
	var i TicketRelease
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Quantity,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ExpiresAt,
		&i.GraceWindowSeconds,
		&i.OfferWindowSeconds,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getReleaseCounts = `-- name: GetReleaseCounts :one
SELECT
    r.quantity::int AS quantity,
    count(*) FILTER (WHERE q.status IN ('granted', 'accepted'))::int AS claimed,
    count(*) FILTER (WHERE q.status = 'waitlisted')::int AS waitlisted
FROM ticket_release r
LEFT JOIN ticket_queue_entry q ON q.release_id = r.id
WHERE r.id = $1
GROUP BY r.quantity
`

type GetReleaseCountsRow struct {
	Quantity   int32 `json:"quantity"`
	Claimed    int32 `json:"claimed"`
	Waitlisted int32 `json:"waitlisted"`
}

func (q *Queries) GetReleaseCounts(ctx context.Context, id pgtype.UUID) (GetReleaseCountsRow, error) {
	row := q.db.QueryRow(ctx, getReleaseCounts, id)
	var i GetReleaseCountsRow
	err := row.Scan(&i.Quantity, &i.Claimed, &i.Waitlisted)
	return i, err
}

const grantEntry = `-- name: GrantEntry :exec
UPDATE ticket_queue_entry
SET status = 'granted', queue_position = NULL, offer_expires_at = $3, updated_at = now()
WHERE id = $1 AND release_id = $2
`

type GrantEntryParams struct {
	ID             pgtype.UUID        `json:"id"`
	ReleaseID      pgtype.UUID        `json:"release_id"`
	OfferExpiresAt pgtype.Timestamptz `json:"offer_expires_at"`
}

func (q *Queries) GrantEntry(ctx context.Context, arg GrantEntryParams) error {
	_, err := q.db.Exec(ctx, grantEntry, arg.ID, arg.ReleaseID, arg.OfferExpiresAt)
	return err
}

const insertQueueEntry = `-- name: InsertQueueEntry :one
INSERT INTO ticket_queue_entry (release_id, member_id, status)
VALUES ($1, $2, 'pending')
ON CONFLICT (release_id, member_id) DO UPDATE SET member_id = EXCLUDED.member_id
RETURNING id, release_id, member_id, status, queue_position, offer_expires_at, requested_at, updated_at
`

type InsertQueueEntryParams struct {
	ReleaseID pgtype.UUID `json:"release_id"`
	MemberID  string      `json:"member_id"`
}

// Idempotent: a repeat request for the same (release, member) just returns
// the existing row unchanged instead of erroring.
func (q *Queries) InsertQueueEntry(ctx context.Context, arg InsertQueueEntryParams) (TicketQueueEntry, error) {
	row := q.db.QueryRow(ctx, insertQueueEntry, arg.ReleaseID, arg.MemberID)
	var i TicketQueueEntry
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.MemberID,
		&i.Status,
		&i.QueuePosition,
		&i.OfferExpiresAt,
		&i.RequestedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAcceptedEntriesForRelease = `-- name: ListAcceptedEntriesForRelease :many
SELECT id, release_id, member_id, status, queue_position, offer_expires_at, requested_at, updated_at
FROM ticket_queue_entry
WHERE release_id = $1 AND status = 'accepted'
ORDER BY requested_at ASC
`

// The admin roster for one release - only entries that actually hold a
// confirmed ticket (pending/waitlisted/granted/expired/cancelled are noise
// for "who has a ticket" purposes, and their status would always read the
// same anyway).
func (q *Queries) ListAcceptedEntriesForRelease(ctx context.Context, releaseID pgtype.UUID) ([]TicketQueueEntry, error) {
	rows, err := q.db.Query(ctx, listAcceptedEntriesForRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketQueueEntry{}
	for rows.Next() {
		var i TicketQueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.MemberID,
			&i.Status,
			&i.QueuePosition,
			&i.OfferExpiresAt,
			&i.RequestedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReleases = `-- name: ListAllReleases :many
SELECT id, event_id, title, description, location, quantity, opens_at, closes_at, expires_at, grace_window_seconds, offer_window_seconds, status, created_by, created_at
FROM ticket_release
ORDER BY opens_at DESC
`

// The admin listing - nothing excluded, so past events stay reviewable.
func (q *Queries) ListAllReleases(ctx context.Context) ([]TicketRelease, error) {
	rows, err := q.db.Query(ctx, listAllReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketRelease{}
	for rows.Next() {
		var i TicketRelease
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Quantity,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ExpiresAt,
			&i.GraceWindowSeconds,
			&i.OfferWindowSeconds,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesForMember = `-- name: ListEntriesForMember :many
SELECT
    e.id, e.release_id, e.member_id, e.status, e.queue_position, e.offer_expires_at, e.requested_at, e.updated_at,
    r.title AS release_title
FROM ticket_queue_entry e
JOIN ticket_release r ON r.id = e.release_id
WHERE e.member_id = $1 AND r.expires_at > now()
ORDER BY e.requested_at DESC
`

type ListEntriesForMemberRow struct {
	ID             pgtype.UUID        `json:"id"`
	ReleaseID      pgtype.UUID        `json:"release_id"`
	MemberID       string             `json:"member_id"`
	Status         string             `json:"status"`
	QueuePosition  pgtype.Int4        `json:"queue_position"`
	OfferExpiresAt pgtype.Timestamptz `json:"offer_expires_at"`
	RequestedAt    pgtype.Timestamptz `json:"requested_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ReleaseTitle   string             `json:"release_title"`
}

// A member's "my tickets" view - expired releases (event over) are excluded
// so old tickets don't build up indefinitely.
func (q *Queries) ListEntriesForMember(ctx context.Context, memberID string) ([]ListEntriesForMemberRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesForMemberRow{}
	for rows.Next() {
		var i ListEntriesForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.MemberID,
			&i.Status,
			&i.QueuePosition,
			&i.OfferExpiresAt,
			&i.RequestedAt,
			&i.UpdatedAt,
			&i.ReleaseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredGrantedForUpdate = `-- name: ListExpiredGrantedForUpdate :many
SELECT id, release_id, member_id, status, queue_position, offer_expires_at, requested_at, updated_at
FROM ticket_queue_entry
WHERE release_id = $1 AND status = 'granted' AND offer_expires_at <= now()
FOR UPDATE
`

func (q *Queries) ListExpiredGrantedForUpdate(ctx context.Context, releaseID pgtype.UUID) ([]TicketQueueEntry, error) {
	rows, err := q.db.Query(ctx, listExpiredGrantedForUpdate, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketQueueEntry{}
	for rows.Next() {
		var i TicketQueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.MemberID,
			&i.Status,
			&i.QueuePosition,
			&i.OfferExpiresAt,
			&i.RequestedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingForUpdate = `-- name: ListPendingForUpdate :many
SELECT id, release_id, member_id, status, queue_position, offer_expires_at, requested_at, updated_at
FROM ticket_queue_entry
WHERE release_id = $1 AND status = 'pending'
FOR UPDATE
`

func (q *Queries) ListPendingForUpdate(ctx context.Context, releaseID pgtype.UUID) ([]TicketQueueEntry, error) {
	rows, err := q.db.Query(ctx, listPendingForUpdate, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketQueueEntry{}
	for rows.Next() {
		var i TicketQueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.MemberID,
			&i.Status,
			&i.QueuePosition,
			&i.OfferExpiresAt,
			&i.RequestedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT id, event_id, title, description, location, quantity, opens_at, closes_at, expires_at, grace_window_seconds, offer_window_seconds, status, created_by, created_at
FROM ticket_release
WHERE expires_at > now()
ORDER BY opens_at DESC
`

// The public/browsing listing - expired releases (event over) are excluded.
func (q *Queries) ListReleases(ctx context.Context) ([]TicketRelease, error) {
	rows, err := q.db.Query(ctx, listReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketRelease{}
	for rows.Next() {
		var i TicketRelease
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Quantity,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ExpiresAt,
			&i.GraceWindowSeconds,
			&i.OfferWindowSeconds,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesWithActiveOffers = `-- name: ListReleasesWithActiveOffers :many
SELECT DISTINCT r.id, r.event_id, r.title, r.description, r.location, r.quantity, r.opens_at, r.closes_at, r.expires_at, r.grace_window_seconds, r.offer_window_seconds, r.status, r.created_by, r.created_at
FROM ticket_release r
JOIN ticket_queue_entry q ON q.release_id = r.id
WHERE q.status = 'granted'
`

// Releases that have at least one granted-but-unaccepted offer, used to
// know which releases need an expiry sweep.
func (q *Queries) ListReleasesWithActiveOffers(ctx context.Context) ([]TicketRelease, error) {
	rows, err := q.db.Query(ctx, listReleasesWithActiveOffers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketRelease{}
	for rows.Next() {
		var i TicketRelease
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Quantity,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ExpiresAt,
			&i.GraceWindowSeconds,
			&i.OfferWindowSeconds,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledReleases = `-- name: ListScheduledReleases :many
SELECT id, event_id, title, description, location, quantity, opens_at, closes_at, expires_at, grace_window_seconds, offer_window_seconds, status, created_by, created_at
FROM ticket_release
WHERE status = 'scheduled'
`

// Releases whose lottery hasn't run yet, used to re-arm in-process timers
// after a restart.
func (q *Queries) ListScheduledReleases(ctx context.Context) ([]TicketRelease, error) {
	rows, err := q.db.Query(ctx, listScheduledReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketRelease{}
	for rows.Next() {
		var i TicketRelease
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.Quantity,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ExpiresAt,
			&i.GraceWindowSeconds,
			&i.OfferWindowSeconds,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitlistFrontForUpdate = `-- name: ListWaitlistFrontForUpdate :many
SELECT id, release_id, member_id, status, queue_position, offer_expires_at, requested_at, updated_at
FROM ticket_queue_entry
WHERE release_id = $1 AND status = 'waitlisted'
ORDER BY queue_position ASC
LIMIT $2
FOR UPDATE
`

type ListWaitlistFrontForUpdateParams struct {
	ReleaseID pgtype.UUID `json:"release_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListWaitlistFrontForUpdate(ctx context.Context, arg ListWaitlistFrontForUpdateParams) ([]TicketQueueEntry, error) {
	rows, err := q.db.Query(ctx, listWaitlistFrontForUpdate, arg.ReleaseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketQueueEntry{}
	for rows.Next() {
		var i TicketQueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.MemberID,
			&i.Status,
			&i.QueuePosition,
			&i.OfferExpiresAt,
			&i.RequestedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRelease = `-- name: LockRelease :one
SELECT id, event_id, title, description, location, quantity, opens_at, closes_at, expires_at, grace_window_seconds, offer_window_seconds, status, created_by, created_at
FROM ticket_release
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockRelease(ctx context.Context, id pgtype.UUID) (TicketRelease, error) {
	row := q.db.QueryRow(ctx, lockRelease, id)
	var i TicketRelease
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Quantity,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ExpiresAt,
		&i.GraceWindowSeconds,
		&i.OfferWindowSeconds,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const setReleaseStatus = `-- name: SetReleaseStatus :exec
UPDATE ticket_release SET status = $2 WHERE id = $1
`

type SetReleaseStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetReleaseStatus(ctx context.Context, arg SetReleaseStatusParams) error {
	_, err := q.db.Exec(ctx, setReleaseStatus, arg.ID, arg.Status)
	return err
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE ticket_release
SET title = $2, description = $3, location = $4, quantity = $5, closes_at = $6
WHERE id = $1
RETURNING id, event_id, title, description, location, quantity, opens_at, closes_at, expires_at, grace_window_seconds, offer_window_seconds, status, created_by, created_at
`

type UpdateReleaseParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Location    string             `json:"location"`
	Quantity    int32              `json:"quantity"`
	ClosesAt    pgtype.Timestamptz `json:"closes_at"`
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (TicketRelease, error) {
	row := q.db.QueryRow(ctx, updateRelease,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.Quantity,
		arg.ClosesAt,
	)
	var i TicketRelease
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.Quantity,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ExpiresAt,
		&i.GraceWindowSeconds,
		&i.OfferWindowSeconds,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const waitlistEntry = `-- name: WaitlistEntry :exec
UPDATE ticket_queue_entry
SET status = 'waitlisted', queue_position = $3, offer_expires_at = NULL, updated_at = now()
WHERE id = $1 AND release_id = $2
`

type WaitlistEntryParams struct {
	ID            pgtype.UUID `json:"id"`
	ReleaseID     pgtype.UUID `json:"release_id"`
	QueuePosition pgtype.Int4 `json:"queue_position"`
}

func (q *Queries) WaitlistEntry(ctx context.Context, arg WaitlistEntryParams) error {
	_, err := q.db.Exec(ctx, waitlistEntry, arg.ID, arg.ReleaseID, arg.QueuePosition)
	return err
}
