FROM docker.io/node:22-trixie

RUN apt-get update && apt-get install -y \
  openssl \
  && rm -rf /var/lib/apt/lists/*

# pnpm via Corepack
RUN corepack enable pnpm \
  && mkdir -p /pnpm/store

ENV NPM_CONFIG_STORE_DIR=/pnpm/store
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

# Set version so git isn't required
ENV VERSION=dev

VOLUME /workspace
VOLUME /pnpm/store

WORKDIR /workspace

