// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPoliciesForRolesOrStudentID = `-- name: ListPoliciesForRolesOrStudentID :many
SELECT api_name
FROM api_access_policies
WHERE role = ANY($1::text[])
   OR student_id = $2
`

type ListPoliciesForRolesOrStudentIDParams struct {
	Roles     []string    `json:"roles"`
	StudentID pgtype.Text `json:"student_id"`
}

// Mirrors hooks.server.helpers.ts's getAccessPolicies: a policy applies if
// it's granted to any of the caller's derived roles, or to their
// student_id specifically. Pass a NULL student_id for an anonymous caller
// (no derived roles are ever real student ids) - "student_id = NULL" never
// matches, which is the same no-op the old code got from Prisma ignoring
// an undefined filter.
func (q *Queries) ListPoliciesForRolesOrStudentID(ctx context.Context, arg ListPoliciesForRolesOrStudentIDParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPoliciesForRolesOrStudentID, arg.Roles, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var api_name string
		if err := rows.Scan(&api_name); err != nil {
			return nil, err
		}
		items = append(items, api_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
