// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adminsettings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAdminSetting = `-- name: DeleteAdminSetting :execrows
DELETE FROM admin_settings WHERE key = $1
`

func (q *Queries) DeleteAdminSetting(ctx context.Context, key string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminSetting, key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAdminSettings = `-- name: ListAdminSettings :many
SELECT key, value, created_at, updated_at FROM admin_settings ORDER BY key ASC
`

func (q *Queries) ListAdminSettings(ctx context.Context) ([]AdminSetting, error) {
	rows, err := q.db.Query(ctx, listAdminSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminSetting{}
	for rows.Next() {
		var i AdminSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAdminSetting = `-- name: UpsertAdminSetting :one
INSERT INTO admin_settings (key, value, updated_at)
VALUES ($1, $2, CURRENT_TIMESTAMP)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = CURRENT_TIMESTAMP
RETURNING key, value, created_at, updated_at
`

type UpsertAdminSettingParams struct {
	Key   string      `json:"key"`
	Value pgtype.Text `json:"value"`
}

func (q *Queries) UpsertAdminSetting(ctx context.Context, arg UpsertAdminSettingParams) (AdminSetting, error) {
	row := q.db.QueryRow(ctx, upsertAdminSetting, arg.Key, arg.Value)
	var i AdminSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
