// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeAlertForMember = `-- name: CloseAlertForMember :exec
INSERT INTO _alerts_closed_by ("A", "B") VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CloseAlertForMemberParams struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

func (q *Queries) CloseAlertForMember(ctx context.Context, arg CloseAlertForMemberParams) error {
	_, err := q.db.Exec(ctx, closeAlertForMember, arg.A, arg.B)
	return err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (severity, message_sv, message_en)
VALUES ($1, $2, $3)
RETURNING id, severity, message_sv, message_en, created_at, removed_at
`

type CreateAlertParams struct {
	Severity  string `json:"severity"`
	MessageSv string `json:"message_sv"`
	MessageEn string `json:"message_en"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert, arg.Severity, arg.MessageSv, arg.MessageEn)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Severity,
		&i.MessageSv,
		&i.MessageEn,
		&i.CreatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const listActiveAlerts = `-- name: ListActiveAlerts :many
SELECT id, severity, message_sv, message_en, created_at, removed_at
FROM alerts
WHERE removed_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAlerts(ctx context.Context) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listActiveAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.Severity,
			&i.MessageSv,
			&i.MessageEn,
			&i.CreatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClosedAlertIDsForMember = `-- name: ListClosedAlertIDsForMember :many
SELECT "A" FROM _alerts_closed_by WHERE "B" = $1
`

func (q *Queries) ListClosedAlertIDsForMember(ctx context.Context, b pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listClosedAlertIDsForMember, b)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var A pgtype.UUID
		if err := rows.Scan(&A); err != nil {
			return nil, err
		}
		items = append(items, A)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAlert = `-- name: SoftDeleteAlert :exec
UPDATE alerts SET removed_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteAlert(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAlert, id)
	return err
}
