// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countArticleSlugsWithPrefix = `-- name: CountArticleSlugsWithPrefix :one
SELECT count(*) FROM articles WHERE slug LIKE $1 || '%'
`

func (q *Queries) CountArticleSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countArticleSlugsWithPrefix, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticles = `-- name: CountArticles :one
SELECT count(*) FROM articles a
JOIN authors au ON au.id = a.author_id
JOIN members m ON m.id = au.member_id
WHERE a.published_datetime IS NOT NULL
  AND a.published_datetime <= now()
  AND (a.removed_at IS NULL OR a.removed_at > now())
  AND (
    $1::text IS NULL
    OR a.header_sv ILIKE '%' || $1::text || '%'
    OR a.header_en ILIKE '%' || $1::text || '%'
    OR a.body_sv ILIKE '%' || $1::text || '%'
    OR a.body_en ILIKE '%' || $1::text || '%'
  )
  AND (
    $2::uuid[] IS NULL
    OR EXISTS (
        SELECT 1 FROM _article_tags t
        WHERE t."A" = a.id AND t."B" = ANY($2::uuid[])
    )
  )
  AND ($3::uuid IS NULL OR a.committee_id = $3::uuid)
  AND ($4::text IS NULL OR m.student_id = $4::text)
  AND (
    $5::uuid IS NULL
    OR a.nollning_season_id = $5::uuid
  )
`

type CountArticlesParams struct {
	Search           pgtype.Text   `json:"search"`
	TagIds           []pgtype.UUID `json:"tag_ids"`
	CommitteeID      pgtype.UUID   `json:"committee_id"`
	AuthorStudentID  pgtype.Text   `json:"author_student_id"`
	NollningSeasonID pgtype.UUID   `json:"nollning_season_id"`
}

func (q *Queries) CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles,
		arg.Search,
		arg.TagIds,
		arg.CommitteeID,
		arg.AuthorStudentID,
		arg.NollningSeasonID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
    header_sv, header_en, body_sv, body_en, image_url, image_urls,
    youtube_url, author_id, published_datetime, should_send_notification,
    notification_text, committee_id, slug, nollning_season_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, slug
`

type CreateArticleParams struct {
	HeaderSv               string             `json:"header_sv"`
	HeaderEn               pgtype.Text        `json:"header_en"`
	BodySv                 string             `json:"body_sv"`
	BodyEn                 pgtype.Text        `json:"body_en"`
	ImageUrl               pgtype.Text        `json:"image_url"`
	ImageUrls              []string           `json:"image_urls"`
	YoutubeUrl             pgtype.Text        `json:"youtube_url"`
	AuthorID               pgtype.UUID        `json:"author_id"`
	PublishedDatetime      pgtype.Timestamptz `json:"published_datetime"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	NotificationText       pgtype.Text        `json:"notification_text"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
	Slug                   string             `json:"slug"`
	NollningSeasonID       pgtype.UUID        `json:"nollning_season_id"`
}

type CreateArticleRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.HeaderSv,
		arg.HeaderEn,
		arg.BodySv,
		arg.BodyEn,
		arg.ImageUrl,
		arg.ImageUrls,
		arg.YoutubeUrl,
		arg.AuthorID,
		arg.PublishedDatetime,
		arg.ShouldSendNotification,
		arg.NotificationText,
		arg.CommitteeID,
		arg.Slug,
		arg.NollningSeasonID,
	)
	var i CreateArticleRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT
    a.id, a.header_sv, a.header_en, a.body_sv, a.body_en, a.image_url,
    a.author_id, a.published_datetime, a.latest_edit_datetime, a.slug,
    a.removed_at, a.status, a.created_datetime, a.youtube_url, a.image_urls,
    a.notification_text, a.should_send_notification, a.scheduled_id, a.committee_id,
    a.nollning_season_id,
    c.name_sv AS committee_name_sv, c.name_en AS committee_name_en,
    c.short_name AS committee_short_name, c.symbol_url AS committee_symbol_url,
    au.type AS author_type,
    m.id AS member_id, m.student_id AS member_student_id,
    m.first_name AS member_first_name, m.last_name AS member_last_name,
    m.nickname AS member_nickname, m.picture_path AS member_picture_path,
    p.id AS position_id, p.name_sv AS position_name_sv, p.name_en AS position_name_en,
    ca.id AS custom_author_id, ca.name_sv AS custom_author_name_sv,
    ca.name_en AS custom_author_name_en, ca.image_url AS custom_author_image_url,
    COALESCE(cm.n, 0)::int AS comment_count,
    COALESCE(lk.n, 0)::int AS like_count
FROM articles a
JOIN authors au ON au.id = a.author_id
JOIN members m ON m.id = au.member_id
LEFT JOIN mandates mn ON mn.id = au.mandate_id
LEFT JOIN positions p ON p.id = mn.position_id
LEFT JOIN custom_authors ca ON ca.id = au.custom_id
LEFT JOIN committees c ON c.id = a.committee_id
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM article_comments WHERE article_id = a.id
) cm ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _article_likes WHERE "A" = a.id
) lk ON true
WHERE a.slug = $1
  AND a.published_datetime IS NOT NULL
  AND a.published_datetime <= now()
  AND (a.removed_at IS NULL OR a.removed_at > now())
`

type GetArticleBySlugRow struct {
	ID                     pgtype.UUID        `json:"id"`
	HeaderSv               string             `json:"header_sv"`
	HeaderEn               pgtype.Text        `json:"header_en"`
	BodySv                 string             `json:"body_sv"`
	BodyEn                 pgtype.Text        `json:"body_en"`
	ImageUrl               pgtype.Text        `json:"image_url"`
	AuthorID               pgtype.UUID        `json:"author_id"`
	PublishedDatetime      pgtype.Timestamptz `json:"published_datetime"`
	LatestEditDatetime     pgtype.Timestamptz `json:"latest_edit_datetime"`
	Slug                   string             `json:"slug"`
	RemovedAt              pgtype.Timestamptz `json:"removed_at"`
	Status                 pgtype.Text        `json:"status"`
	CreatedDatetime        pgtype.Timestamptz `json:"created_datetime"`
	YoutubeUrl             pgtype.Text        `json:"youtube_url"`
	ImageUrls              []string           `json:"image_urls"`
	NotificationText       pgtype.Text        `json:"notification_text"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	ScheduledID            pgtype.Text        `json:"scheduled_id"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
	NollningSeasonID       pgtype.UUID        `json:"nollning_season_id"`
	CommitteeNameSv        pgtype.Text        `json:"committee_name_sv"`
	CommitteeNameEn        pgtype.Text        `json:"committee_name_en"`
	CommitteeShortName     pgtype.Text        `json:"committee_short_name"`
	CommitteeSymbolUrl     pgtype.Text        `json:"committee_symbol_url"`
	AuthorType             pgtype.Text        `json:"author_type"`
	MemberID               pgtype.UUID        `json:"member_id"`
	MemberStudentID        pgtype.Text        `json:"member_student_id"`
	MemberFirstName        pgtype.Text        `json:"member_first_name"`
	MemberLastName         pgtype.Text        `json:"member_last_name"`
	MemberNickname         pgtype.Text        `json:"member_nickname"`
	MemberPicturePath      pgtype.Text        `json:"member_picture_path"`
	PositionID             pgtype.Text        `json:"position_id"`
	PositionNameSv         pgtype.Text        `json:"position_name_sv"`
	PositionNameEn         pgtype.Text        `json:"position_name_en"`
	CustomAuthorID         pgtype.UUID        `json:"custom_author_id"`
	CustomAuthorNameSv     pgtype.Text        `json:"custom_author_name_sv"`
	CustomAuthorNameEn     pgtype.Text        `json:"custom_author_name_en"`
	CustomAuthorImageUrl   pgtype.Text        `json:"custom_author_image_url"`
	CommentCount           int32              `json:"comment_count"`
	LikeCount              int32              `json:"like_count"`
}

// Public lookup: only published, not (currently) removed articles.
func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.HeaderSv,
		&i.HeaderEn,
		&i.BodySv,
		&i.BodyEn,
		&i.ImageUrl,
		&i.AuthorID,
		&i.PublishedDatetime,
		&i.LatestEditDatetime,
		&i.Slug,
		&i.RemovedAt,
		&i.Status,
		&i.CreatedDatetime,
		&i.YoutubeUrl,
		&i.ImageUrls,
		&i.NotificationText,
		&i.ShouldSendNotification,
		&i.ScheduledID,
		&i.CommitteeID,
		&i.NollningSeasonID,
		&i.CommitteeNameSv,
		&i.CommitteeNameEn,
		&i.CommitteeShortName,
		&i.CommitteeSymbolUrl,
		&i.AuthorType,
		&i.MemberID,
		&i.MemberStudentID,
		&i.MemberFirstName,
		&i.MemberLastName,
		&i.MemberNickname,
		&i.MemberPicturePath,
		&i.PositionID,
		&i.PositionNameSv,
		&i.PositionNameEn,
		&i.CustomAuthorID,
		&i.CustomAuthorNameSv,
		&i.CustomAuthorNameEn,
		&i.CustomAuthorImageUrl,
		&i.CommentCount,
		&i.LikeCount,
	)
	return i, err
}

const getArticleIDBySlug = `-- name: GetArticleIDBySlug :one
SELECT id FROM articles WHERE slug = $1
`

func (q *Queries) GetArticleIDBySlug(ctx context.Context, slug string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getArticleIDBySlug, slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getArticleRowBySlug = `-- name: GetArticleRowBySlug :one
SELECT
    a.id, a.header_sv, a.header_en, a.body_sv, a.body_en, a.image_url,
    a.author_id, a.published_datetime, a.latest_edit_datetime, a.slug,
    a.removed_at, a.status, a.created_datetime, a.youtube_url, a.image_urls,
    a.notification_text, a.should_send_notification, a.scheduled_id, a.committee_id,
    a.nollning_season_id,
    c.name_sv AS committee_name_sv, c.name_en AS committee_name_en,
    c.short_name AS committee_short_name, c.symbol_url AS committee_symbol_url,
    au.type AS author_type,
    m.id AS member_id, m.student_id AS member_student_id,
    m.first_name AS member_first_name, m.last_name AS member_last_name,
    m.nickname AS member_nickname, m.picture_path AS member_picture_path,
    p.id AS position_id, p.name_sv AS position_name_sv, p.name_en AS position_name_en,
    ca.id AS custom_author_id, ca.name_sv AS custom_author_name_sv,
    ca.name_en AS custom_author_name_en, ca.image_url AS custom_author_image_url,
    COALESCE(cm.n, 0)::int AS comment_count,
    COALESCE(lk.n, 0)::int AS like_count
FROM articles a
JOIN authors au ON au.id = a.author_id
JOIN members m ON m.id = au.member_id
LEFT JOIN mandates mn ON mn.id = au.mandate_id
LEFT JOIN positions p ON p.id = mn.position_id
LEFT JOIN custom_authors ca ON ca.id = au.custom_id
LEFT JOIN committees c ON c.id = a.committee_id
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM article_comments WHERE article_id = a.id
) cm ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _article_likes WHERE "A" = a.id
) lk ON true
WHERE a.slug = $1
`

type GetArticleRowBySlugRow struct {
	ID                     pgtype.UUID        `json:"id"`
	HeaderSv               string             `json:"header_sv"`
	HeaderEn               pgtype.Text        `json:"header_en"`
	BodySv                 string             `json:"body_sv"`
	BodyEn                 pgtype.Text        `json:"body_en"`
	ImageUrl               pgtype.Text        `json:"image_url"`
	AuthorID               pgtype.UUID        `json:"author_id"`
	PublishedDatetime      pgtype.Timestamptz `json:"published_datetime"`
	LatestEditDatetime     pgtype.Timestamptz `json:"latest_edit_datetime"`
	Slug                   string             `json:"slug"`
	RemovedAt              pgtype.Timestamptz `json:"removed_at"`
	Status                 pgtype.Text        `json:"status"`
	CreatedDatetime        pgtype.Timestamptz `json:"created_datetime"`
	YoutubeUrl             pgtype.Text        `json:"youtube_url"`
	ImageUrls              []string           `json:"image_urls"`
	NotificationText       pgtype.Text        `json:"notification_text"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	ScheduledID            pgtype.Text        `json:"scheduled_id"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
	NollningSeasonID       pgtype.UUID        `json:"nollning_season_id"`
	CommitteeNameSv        pgtype.Text        `json:"committee_name_sv"`
	CommitteeNameEn        pgtype.Text        `json:"committee_name_en"`
	CommitteeShortName     pgtype.Text        `json:"committee_short_name"`
	CommitteeSymbolUrl     pgtype.Text        `json:"committee_symbol_url"`
	AuthorType             pgtype.Text        `json:"author_type"`
	MemberID               pgtype.UUID        `json:"member_id"`
	MemberStudentID        pgtype.Text        `json:"member_student_id"`
	MemberFirstName        pgtype.Text        `json:"member_first_name"`
	MemberLastName         pgtype.Text        `json:"member_last_name"`
	MemberNickname         pgtype.Text        `json:"member_nickname"`
	MemberPicturePath      pgtype.Text        `json:"member_picture_path"`
	PositionID             pgtype.Text        `json:"position_id"`
	PositionNameSv         pgtype.Text        `json:"position_name_sv"`
	PositionNameEn         pgtype.Text        `json:"position_name_en"`
	CustomAuthorID         pgtype.UUID        `json:"custom_author_id"`
	CustomAuthorNameSv     pgtype.Text        `json:"custom_author_name_sv"`
	CustomAuthorNameEn     pgtype.Text        `json:"custom_author_name_en"`
	CustomAuthorImageUrl   pgtype.Text        `json:"custom_author_image_url"`
	CommentCount           int32              `json:"comment_count"`
	LikeCount              int32              `json:"like_count"`
}

// Unfiltered lookup: no publish/removed filter. Used internally after
// create/update (so the caller gets back exactly what it just wrote even if
// it's a future scheduled draft), and by the ArticleByAnySlug service method
// for callers - like the SvelteKit edit page - that need to load a draft or
// future-scheduled article by its own author. There's no auth on this API,
// so this is no more exposed than the existing unauthenticated mutations;
// see backend/CLAUDE.md.
func (q *Queries) GetArticleRowBySlug(ctx context.Context, slug string) (GetArticleRowBySlugRow, error) {
	row := q.db.QueryRow(ctx, getArticleRowBySlug, slug)
	var i GetArticleRowBySlugRow
	err := row.Scan(
		&i.ID,
		&i.HeaderSv,
		&i.HeaderEn,
		&i.BodySv,
		&i.BodyEn,
		&i.ImageUrl,
		&i.AuthorID,
		&i.PublishedDatetime,
		&i.LatestEditDatetime,
		&i.Slug,
		&i.RemovedAt,
		&i.Status,
		&i.CreatedDatetime,
		&i.YoutubeUrl,
		&i.ImageUrls,
		&i.NotificationText,
		&i.ShouldSendNotification,
		&i.ScheduledID,
		&i.CommitteeID,
		&i.NollningSeasonID,
		&i.CommitteeNameSv,
		&i.CommitteeNameEn,
		&i.CommitteeShortName,
		&i.CommitteeSymbolUrl,
		&i.AuthorType,
		&i.MemberID,
		&i.MemberStudentID,
		&i.MemberFirstName,
		&i.MemberLastName,
		&i.MemberNickname,
		&i.MemberPicturePath,
		&i.PositionID,
		&i.PositionNameSv,
		&i.PositionNameEn,
		&i.CustomAuthorID,
		&i.CustomAuthorNameSv,
		&i.CustomAuthorNameEn,
		&i.CustomAuthorImageUrl,
		&i.CommentCount,
		&i.LikeCount,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many

SELECT
    a.id, a.header_sv, a.header_en, a.body_sv, a.body_en, a.image_url,
    a.author_id, a.published_datetime, a.latest_edit_datetime, a.slug,
    a.removed_at, a.status, a.created_datetime, a.youtube_url, a.image_urls,
    a.notification_text, a.should_send_notification, a.scheduled_id, a.committee_id,
    a.nollning_season_id,
    c.name_sv AS committee_name_sv, c.name_en AS committee_name_en,
    c.short_name AS committee_short_name, c.symbol_url AS committee_symbol_url,
    au.type AS author_type,
    m.id AS member_id, m.student_id AS member_student_id,
    m.first_name AS member_first_name, m.last_name AS member_last_name,
    m.nickname AS member_nickname, m.picture_path AS member_picture_path,
    p.id AS position_id, p.name_sv AS position_name_sv, p.name_en AS position_name_en,
    ca.id AS custom_author_id, ca.name_sv AS custom_author_name_sv,
    ca.name_en AS custom_author_name_en, ca.image_url AS custom_author_image_url,
    COALESCE(cm.n, 0)::int AS comment_count,
    COALESCE(lk.n, 0)::int AS like_count
FROM articles a
JOIN authors au ON au.id = a.author_id
JOIN members m ON m.id = au.member_id
LEFT JOIN mandates mn ON mn.id = au.mandate_id
LEFT JOIN positions p ON p.id = mn.position_id
LEFT JOIN custom_authors ca ON ca.id = au.custom_id
LEFT JOIN committees c ON c.id = a.committee_id
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM article_comments WHERE article_id = a.id
) cm ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _article_likes WHERE "A" = a.id
) lk ON true
WHERE a.published_datetime IS NOT NULL
  AND a.published_datetime <= now()
  AND (a.removed_at IS NULL OR a.removed_at > now())
  AND (
    $1::text IS NULL
    OR a.header_sv ILIKE '%' || $1::text || '%'
    OR a.header_en ILIKE '%' || $1::text || '%'
    OR a.body_sv ILIKE '%' || $1::text || '%'
    OR a.body_en ILIKE '%' || $1::text || '%'
  )
  AND (
    $2::uuid[] IS NULL
    OR EXISTS (
        SELECT 1 FROM _article_tags t
        WHERE t."A" = a.id AND t."B" = ANY($2::uuid[])
    )
  )
  AND ($3::uuid IS NULL OR a.committee_id = $3::uuid)
  AND ($4::text IS NULL OR m.student_id = $4::text)
  AND (
    $5::uuid IS NULL
    OR a.nollning_season_id = $5::uuid
  )
ORDER BY a.published_datetime DESC
LIMIT $7 OFFSET $6
`

type ListArticlesParams struct {
	Search           pgtype.Text   `json:"search"`
	TagIds           []pgtype.UUID `json:"tag_ids"`
	CommitteeID      pgtype.UUID   `json:"committee_id"`
	AuthorStudentID  pgtype.Text   `json:"author_student_id"`
	NollningSeasonID pgtype.UUID   `json:"nollning_season_id"`
	Offset           int32         `json:"offset"`
	Limit            int32         `json:"limit"`
}

type ListArticlesRow struct {
	ID                     pgtype.UUID        `json:"id"`
	HeaderSv               string             `json:"header_sv"`
	HeaderEn               pgtype.Text        `json:"header_en"`
	BodySv                 string             `json:"body_sv"`
	BodyEn                 pgtype.Text        `json:"body_en"`
	ImageUrl               pgtype.Text        `json:"image_url"`
	AuthorID               pgtype.UUID        `json:"author_id"`
	PublishedDatetime      pgtype.Timestamptz `json:"published_datetime"`
	LatestEditDatetime     pgtype.Timestamptz `json:"latest_edit_datetime"`
	Slug                   string             `json:"slug"`
	RemovedAt              pgtype.Timestamptz `json:"removed_at"`
	Status                 pgtype.Text        `json:"status"`
	CreatedDatetime        pgtype.Timestamptz `json:"created_datetime"`
	YoutubeUrl             pgtype.Text        `json:"youtube_url"`
	ImageUrls              []string           `json:"image_urls"`
	NotificationText       pgtype.Text        `json:"notification_text"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	ScheduledID            pgtype.Text        `json:"scheduled_id"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
	NollningSeasonID       pgtype.UUID        `json:"nollning_season_id"`
	CommitteeNameSv        pgtype.Text        `json:"committee_name_sv"`
	CommitteeNameEn        pgtype.Text        `json:"committee_name_en"`
	CommitteeShortName     pgtype.Text        `json:"committee_short_name"`
	CommitteeSymbolUrl     pgtype.Text        `json:"committee_symbol_url"`
	AuthorType             pgtype.Text        `json:"author_type"`
	MemberID               pgtype.UUID        `json:"member_id"`
	MemberStudentID        pgtype.Text        `json:"member_student_id"`
	MemberFirstName        pgtype.Text        `json:"member_first_name"`
	MemberLastName         pgtype.Text        `json:"member_last_name"`
	MemberNickname         pgtype.Text        `json:"member_nickname"`
	MemberPicturePath      pgtype.Text        `json:"member_picture_path"`
	PositionID             pgtype.Text        `json:"position_id"`
	PositionNameSv         pgtype.Text        `json:"position_name_sv"`
	PositionNameEn         pgtype.Text        `json:"position_name_en"`
	CustomAuthorID         pgtype.UUID        `json:"custom_author_id"`
	CustomAuthorNameSv     pgtype.Text        `json:"custom_author_name_sv"`
	CustomAuthorNameEn     pgtype.Text        `json:"custom_author_name_en"`
	CustomAuthorImageUrl   pgtype.Text        `json:"custom_author_image_url"`
	CommentCount           int32              `json:"comment_count"`
	LikeCount              int32              `json:"like_count"`
}

// Shared column list for the "joined article" shape: article + committee +
// author (member / mandate+position / custom author) + comment & like
// counts. Duplicated across ListArticles/GetArticleBySlug/GetArticleRowBySlug
// because sqlc has no macro/fragment support.
func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.Query(ctx, listArticles,
		arg.Search,
		arg.TagIds,
		arg.CommitteeID,
		arg.AuthorStudentID,
		arg.NollningSeasonID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesRow{}
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.HeaderSv,
			&i.HeaderEn,
			&i.BodySv,
			&i.BodyEn,
			&i.ImageUrl,
			&i.AuthorID,
			&i.PublishedDatetime,
			&i.LatestEditDatetime,
			&i.Slug,
			&i.RemovedAt,
			&i.Status,
			&i.CreatedDatetime,
			&i.YoutubeUrl,
			&i.ImageUrls,
			&i.NotificationText,
			&i.ShouldSendNotification,
			&i.ScheduledID,
			&i.CommitteeID,
			&i.NollningSeasonID,
			&i.CommitteeNameSv,
			&i.CommitteeNameEn,
			&i.CommitteeShortName,
			&i.CommitteeSymbolUrl,
			&i.AuthorType,
			&i.MemberID,
			&i.MemberStudentID,
			&i.MemberFirstName,
			&i.MemberLastName,
			&i.MemberNickname,
			&i.MemberPicturePath,
			&i.PositionID,
			&i.PositionNameSv,
			&i.PositionNameEn,
			&i.CustomAuthorID,
			&i.CustomAuthorNameSv,
			&i.CustomAuthorNameEn,
			&i.CustomAuthorImageUrl,
			&i.CommentCount,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArticleScheduledID = `-- name: SetArticleScheduledID :exec
UPDATE articles SET scheduled_id = $2 WHERE slug = $1
`

type SetArticleScheduledIDParams struct {
	Slug        string      `json:"slug"`
	ScheduledID pgtype.Text `json:"scheduled_id"`
}

// Targeted single-field write: the caller's external scheduler task id,
// recorded after scheduling a future publish succeeds. Deliberately
// separate from UpdateArticle (which is full-replace) since this needs to
// happen without the caller re-submitting the whole article.
func (q *Queries) SetArticleScheduledID(ctx context.Context, arg SetArticleScheduledIDParams) error {
	_, err := q.db.Exec(ctx, setArticleScheduledID, arg.Slug, arg.ScheduledID)
	return err
}

const softDeleteArticle = `-- name: SoftDeleteArticle :exec
UPDATE articles SET removed_at = now() WHERE slug = $1
`

func (q *Queries) SoftDeleteArticle(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, softDeleteArticle, slug)
	return err
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles SET
    header_sv = $2,
    header_en = $3,
    body_sv = $4,
    body_en = $5,
    image_url = $6,
    image_urls = $7,
    youtube_url = $8,
    author_id = $9,
    published_datetime = $10,
    should_send_notification = $11,
    notification_text = $12,
    committee_id = $13,
    nollning_season_id = $14,
    latest_edit_datetime = now()
WHERE slug = $1
RETURNING id, slug
`

type UpdateArticleParams struct {
	Slug                   string             `json:"slug"`
	HeaderSv               string             `json:"header_sv"`
	HeaderEn               pgtype.Text        `json:"header_en"`
	BodySv                 string             `json:"body_sv"`
	BodyEn                 pgtype.Text        `json:"body_en"`
	ImageUrl               pgtype.Text        `json:"image_url"`
	ImageUrls              []string           `json:"image_urls"`
	YoutubeUrl             pgtype.Text        `json:"youtube_url"`
	AuthorID               pgtype.UUID        `json:"author_id"`
	PublishedDatetime      pgtype.Timestamptz `json:"published_datetime"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	NotificationText       pgtype.Text        `json:"notification_text"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
	NollningSeasonID       pgtype.UUID        `json:"nollning_season_id"`
}

type UpdateArticleRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug string      `json:"slug"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Slug,
		arg.HeaderSv,
		arg.HeaderEn,
		arg.BodySv,
		arg.BodyEn,
		arg.ImageUrl,
		arg.ImageUrls,
		arg.YoutubeUrl,
		arg.AuthorID,
		arg.PublishedDatetime,
		arg.ShouldSendNotification,
		arg.NotificationText,
		arg.CommitteeID,
		arg.NollningSeasonID,
	)
	var i UpdateArticleRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}
