// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (member_id, mandate_id, custom_id)
VALUES ($1, $2::uuid, $3::uuid)
RETURNING id
`

type CreateAuthorParams struct {
	MemberID  pgtype.UUID `json:"member_id"`
	MandateID pgtype.UUID `json:"mandate_id"`
	CustomID  pgtype.UUID `json:"custom_id"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.MemberID, arg.MandateID, arg.CustomID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findAuthor = `-- name: FindAuthor :one
SELECT id FROM authors
WHERE member_id = $1
  AND mandate_id IS NOT DISTINCT FROM $2::uuid
  AND custom_id IS NOT DISTINCT FROM $3::uuid
LIMIT 1
`

type FindAuthorParams struct {
	MemberID  pgtype.UUID `json:"member_id"`
	MandateID pgtype.UUID `json:"mandate_id"`
	CustomID  pgtype.UUID `json:"custom_id"`
}

// Authors are reused across articles: an author row is the (member,
// mandate, custom-author) triple, so the same byline is only created once.
func (q *Queries) FindAuthor(ctx context.Context, arg FindAuthorParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAuthor, arg.MemberID, arg.MandateID, arg.CustomID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getMandateMemberID = `-- name: GetMandateMemberID :one
SELECT member_id FROM mandates WHERE id = $1
`

// Used to verify a caller posting "as" a mandate actually holds it.
// custom_authors has no owner column in the schema (they're shared
// personas, e.g. "Styrelsen"), so there's no equivalent check for those.
func (q *Queries) GetMandateMemberID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMandateMemberID, id)
	var member_id pgtype.UUID
	err := row.Scan(&member_id)
	return member_id, err
}
