// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBookingRequestBookables = `-- name: AddBookingRequestBookables :exec
INSERT INTO _booking_requests_bookables ("A", "B")
SELECT unnest($1::uuid[]), $2
ON CONFLICT DO NOTHING
`

type AddBookingRequestBookablesParams struct {
	BookableIds      []pgtype.UUID `json:"bookable_ids"`
	BookingRequestID pgtype.UUID   `json:"booking_request_id"`
}

func (q *Queries) AddBookingRequestBookables(ctx context.Context, arg AddBookingRequestBookablesParams) error {
	_, err := q.db.Exec(ctx, addBookingRequestBookables, arg.BookableIds, arg.BookingRequestID)
	return err
}

const clearBookingRequestBookables = `-- name: ClearBookingRequestBookables :exec
DELETE FROM _booking_requests_bookables WHERE "B" = $1
`

func (q *Queries) ClearBookingRequestBookables(ctx context.Context, bookingRequestID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearBookingRequestBookables, bookingRequestID)
	return err
}

const createBookable = `-- name: CreateBookable :one
INSERT INTO bookables (name_sv, name_en, "isDisabled", door, category_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name_sv, name_en, "isDisabled", door, category_id
`

type CreateBookableParams struct {
	NameSv     string      `json:"name_sv"`
	NameEn     pgtype.Text `json:"name_en"`
	IsDisabled bool        `json:"isDisabled"`
	Door       pgtype.Text `json:"door"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type CreateBookableRow struct {
	ID         pgtype.UUID `json:"id"`
	NameSv     string      `json:"name_sv"`
	NameEn     pgtype.Text `json:"name_en"`
	IsDisabled bool        `json:"isDisabled"`
	Door       pgtype.Text `json:"door"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CreateBookable(ctx context.Context, arg CreateBookableParams) (CreateBookableRow, error) {
	row := q.db.QueryRow(ctx, createBookable,
		arg.NameSv,
		arg.NameEn,
		arg.IsDisabled,
		arg.Door,
		arg.CategoryID,
	)
	var i CreateBookableRow
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.IsDisabled,
		&i.Door,
		&i.CategoryID,
	)
	return i, err
}

const createBookableCategory = `-- name: CreateBookableCategory :one
INSERT INTO bookable_categories (name_sv, name_en)
VALUES ($1, $2)
RETURNING id, name_sv, name_en
`

type CreateBookableCategoryParams struct {
	NameSv string      `json:"name_sv"`
	NameEn pgtype.Text `json:"name_en"`
}

func (q *Queries) CreateBookableCategory(ctx context.Context, arg CreateBookableCategoryParams) (BookableCategory, error) {
	row := q.db.QueryRow(ctx, createBookableCategory, arg.NameSv, arg.NameEn)
	var i BookableCategory
	err := row.Scan(&i.ID, &i.NameSv, &i.NameEn)
	return i, err
}

const createBookingRequest = `-- name: CreateBookingRequest :one
INSERT INTO booking_requests (booker_id, start, "end", event, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, booker_id, start, "end", created, event, status
`

type CreateBookingRequestParams struct {
	BookerID pgtype.UUID          `json:"booker_id"`
	Start    pgtype.Timestamptz   `json:"start"`
	End      pgtype.Timestamptz   `json:"end"`
	Event    pgtype.Text          `json:"event"`
	Status   BookingRequestStatus `json:"status"`
}

func (q *Queries) CreateBookingRequest(ctx context.Context, arg CreateBookingRequestParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, createBookingRequest,
		arg.BookerID,
		arg.Start,
		arg.End,
		arg.Event,
		arg.Status,
	)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.BookerID,
		&i.Start,
		&i.End,
		&i.Created,
		&i.Event,
		&i.Status,
	)
	return i, err
}

const deleteBookingRequest = `-- name: DeleteBookingRequest :exec
DELETE FROM booking_requests WHERE id = $1
`

func (q *Queries) DeleteBookingRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBookingRequest, id)
	return err
}

const getBookableByID = `-- name: GetBookableByID :one
SELECT b.id, b.name_sv, b.name_en, b."isDisabled", b.door, b.category_id,
       c.id AS category_id_joined, c.name_sv AS category_name_sv, c.name_en AS category_name_en
FROM bookables b
LEFT JOIN bookable_categories c ON c.id = b.category_id
WHERE b.id = $1
`

type GetBookableByIDRow struct {
	ID               pgtype.UUID `json:"id"`
	NameSv           string      `json:"name_sv"`
	NameEn           pgtype.Text `json:"name_en"`
	IsDisabled       bool        `json:"isDisabled"`
	Door             pgtype.Text `json:"door"`
	CategoryID       pgtype.UUID `json:"category_id"`
	CategoryIDJoined pgtype.UUID `json:"category_id_joined"`
	CategoryNameSv   pgtype.Text `json:"category_name_sv"`
	CategoryNameEn   pgtype.Text `json:"category_name_en"`
}

func (q *Queries) GetBookableByID(ctx context.Context, id pgtype.UUID) (GetBookableByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookableByID, id)
	var i GetBookableByIDRow
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.IsDisabled,
		&i.Door,
		&i.CategoryID,
		&i.CategoryIDJoined,
		&i.CategoryNameSv,
		&i.CategoryNameEn,
	)
	return i, err
}

const getBookableCategoryByID = `-- name: GetBookableCategoryByID :one
SELECT id, name_sv, name_en FROM bookable_categories WHERE id = $1
`

func (q *Queries) GetBookableCategoryByID(ctx context.Context, id pgtype.UUID) (BookableCategory, error) {
	row := q.db.QueryRow(ctx, getBookableCategoryByID, id)
	var i BookableCategory
	err := row.Scan(&i.ID, &i.NameSv, &i.NameEn)
	return i, err
}

const getBookingRequestByID = `-- name: GetBookingRequestByID :one
SELECT br.id, br.booker_id, br.start, br."end", br.created, br.event, br.status,
       m.id AS booker_member_id, m.student_id AS booker_student_id,
       m.first_name AS booker_first_name, m.last_name AS booker_last_name,
       m.nickname AS booker_nickname, m.picture_path AS booker_picture_path
FROM booking_requests br
LEFT JOIN members m ON m.id = br.booker_id
WHERE br.id = $1
`

type GetBookingRequestByIDRow struct {
	ID                pgtype.UUID          `json:"id"`
	BookerID          pgtype.UUID          `json:"booker_id"`
	Start             pgtype.Timestamptz   `json:"start"`
	End               pgtype.Timestamptz   `json:"end"`
	Created           pgtype.Timestamptz   `json:"created"`
	Event             pgtype.Text          `json:"event"`
	Status            BookingRequestStatus `json:"status"`
	BookerMemberID    pgtype.UUID          `json:"booker_member_id"`
	BookerStudentID   pgtype.Text          `json:"booker_student_id"`
	BookerFirstName   pgtype.Text          `json:"booker_first_name"`
	BookerLastName    pgtype.Text          `json:"booker_last_name"`
	BookerNickname    pgtype.Text          `json:"booker_nickname"`
	BookerPicturePath pgtype.Text          `json:"booker_picture_path"`
}

func (q *Queries) GetBookingRequestByID(ctx context.Context, id pgtype.UUID) (GetBookingRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingRequestByID, id)
	var i GetBookingRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.BookerID,
		&i.Start,
		&i.End,
		&i.Created,
		&i.Event,
		&i.Status,
		&i.BookerMemberID,
		&i.BookerStudentID,
		&i.BookerFirstName,
		&i.BookerLastName,
		&i.BookerNickname,
		&i.BookerPicturePath,
	)
	return i, err
}

const getCurrentKarhusmastare = `-- name: GetCurrentKarhusmastare :one
SELECT m.id, m.student_id, m.first_name, m.last_name, m.nickname, m.picture_path
FROM mandates ma
JOIN members m ON m.id = ma.member_id
WHERE ma.position_id = 'dsek.km.mastare'
  AND ma.start_date <= CURRENT_DATE AND ma.end_date >= CURRENT_DATE
ORDER BY ma.start_date DESC
LIMIT 1
`

type GetCurrentKarhusmastareRow struct {
	ID          pgtype.UUID `json:"id"`
	StudentID   pgtype.Text `json:"student_id"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	Nickname    pgtype.Text `json:"nickname"`
	PicturePath pgtype.Text `json:"picture_path"`
}

// The building-manager position holder, notified on every new booking
// request - a hardcoded position slug in the old app too (dsek.km.mastare),
// not configurable.
func (q *Queries) GetCurrentKarhusmastare(ctx context.Context) (GetCurrentKarhusmastareRow, error) {
	row := q.db.QueryRow(ctx, getCurrentKarhusmastare)
	var i GetCurrentKarhusmastareRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Nickname,
		&i.PicturePath,
	)
	return i, err
}

const listBookableCategories = `-- name: ListBookableCategories :many
SELECT id, name_sv, name_en FROM bookable_categories ORDER BY name_sv
`

func (q *Queries) ListBookableCategories(ctx context.Context) ([]BookableCategory, error) {
	rows, err := q.db.Query(ctx, listBookableCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookableCategory{}
	for rows.Next() {
		var i BookableCategory
		if err := rows.Scan(&i.ID, &i.NameSv, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookables = `-- name: ListBookables :many
SELECT b.id, b.name_sv, b.name_en, b."isDisabled", b.door, b.category_id,
       c.id AS category_id_joined, c.name_sv AS category_name_sv, c.name_en AS category_name_en
FROM bookables b
LEFT JOIN bookable_categories c ON c.id = b.category_id
ORDER BY b.name_sv
`

type ListBookablesRow struct {
	ID               pgtype.UUID `json:"id"`
	NameSv           string      `json:"name_sv"`
	NameEn           pgtype.Text `json:"name_en"`
	IsDisabled       bool        `json:"isDisabled"`
	Door             pgtype.Text `json:"door"`
	CategoryID       pgtype.UUID `json:"category_id"`
	CategoryIDJoined pgtype.UUID `json:"category_id_joined"`
	CategoryNameSv   pgtype.Text `json:"category_name_sv"`
	CategoryNameEn   pgtype.Text `json:"category_name_en"`
}

func (q *Queries) ListBookables(ctx context.Context) ([]ListBookablesRow, error) {
	rows, err := q.db.Query(ctx, listBookables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookablesRow{}
	for rows.Next() {
		var i ListBookablesRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.IsDisabled,
			&i.Door,
			&i.CategoryID,
			&i.CategoryIDJoined,
			&i.CategoryNameSv,
			&i.CategoryNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookablesForBookingRequests = `-- name: ListBookablesForBookingRequests :many
SELECT link."B" AS booking_request_id, b.id, b.name_sv, b.name_en, b."isDisabled", b.door, b.category_id
FROM _booking_requests_bookables link
JOIN bookables b ON b.id = link."A"
WHERE link."B" = ANY($1::uuid[])
ORDER BY b.name_sv
`

type ListBookablesForBookingRequestsRow struct {
	BookingRequestID pgtype.UUID `json:"booking_request_id"`
	ID               pgtype.UUID `json:"id"`
	NameSv           string      `json:"name_sv"`
	NameEn           pgtype.Text `json:"name_en"`
	IsDisabled       bool        `json:"isDisabled"`
	Door             pgtype.Text `json:"door"`
	CategoryID       pgtype.UUID `json:"category_id"`
}

func (q *Queries) ListBookablesForBookingRequests(ctx context.Context, bookingRequestIds []pgtype.UUID) ([]ListBookablesForBookingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listBookablesForBookingRequests, bookingRequestIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookablesForBookingRequestsRow{}
	for rows.Next() {
		var i ListBookablesForBookingRequestsRow
		if err := rows.Scan(
			&i.BookingRequestID,
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.IsDisabled,
			&i.Door,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConflictingBookingRequests = `-- name: ListConflictingBookingRequests :many
SELECT DISTINCT br.id, br.booker_id, br.start, br."end", br.created, br.event, br.status,
       m.id AS booker_member_id, m.student_id AS booker_student_id,
       m.first_name AS booker_first_name, m.last_name AS booker_last_name,
       m.nickname AS booker_nickname, m.picture_path AS booker_picture_path
FROM booking_requests br
LEFT JOIN members m ON m.id = br.booker_id
JOIN _booking_requests_bookables link ON link."B" = br.id
WHERE link."A" = ANY($1::uuid[])
  AND br.status != 'DENIED'
  AND ($2::uuid IS NULL OR br.id != $2::uuid)
  AND br.start IS NOT NULL AND br."end" IS NOT NULL
  AND br.start < $3 AND br."end" > $4
ORDER BY br.start
`

type ListConflictingBookingRequestsParams struct {
	BookableIds []pgtype.UUID      `json:"bookable_ids"`
	ExcludeID   pgtype.UUID        `json:"exclude_id"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
}

type ListConflictingBookingRequestsRow struct {
	ID                pgtype.UUID          `json:"id"`
	BookerID          pgtype.UUID          `json:"booker_id"`
	Start             pgtype.Timestamptz   `json:"start"`
	End               pgtype.Timestamptz   `json:"end"`
	Created           pgtype.Timestamptz   `json:"created"`
	Event             pgtype.Text          `json:"event"`
	Status            BookingRequestStatus `json:"status"`
	BookerMemberID    pgtype.UUID          `json:"booker_member_id"`
	BookerStudentID   pgtype.Text          `json:"booker_student_id"`
	BookerFirstName   pgtype.Text          `json:"booker_first_name"`
	BookerLastName    pgtype.Text          `json:"booker_last_name"`
	BookerNickname    pgtype.Text          `json:"booker_nickname"`
	BookerPicturePath pgtype.Text          `json:"booker_picture_path"`
}

// Non-blocking overlap warning (2026-09-02 decision, see DESIGN.md's
// Booking section) - the old app never checked this at all; Go surfaces it
// as a warning on create/update rather than rejecting the request outright.
// DENIED requests never conflict; exclude_id lets an edit ignore its own
// pre-existing row (NULL/unset on create, where nothing to exclude yet).
func (q *Queries) ListConflictingBookingRequests(ctx context.Context, arg ListConflictingBookingRequestsParams) ([]ListConflictingBookingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listConflictingBookingRequests,
		arg.BookableIds,
		arg.ExcludeID,
		arg.EndAt,
		arg.StartAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConflictingBookingRequestsRow{}
	for rows.Next() {
		var i ListConflictingBookingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookerID,
			&i.Start,
			&i.End,
			&i.Created,
			&i.Event,
			&i.Status,
			&i.BookerMemberID,
			&i.BookerStudentID,
			&i.BookerFirstName,
			&i.BookerLastName,
			&i.BookerNickname,
			&i.BookerPicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingBookingRequests = `-- name: ListUpcomingBookingRequests :many
SELECT br.id, br.booker_id, br.start, br."end", br.created, br.event, br.status,
       m.id AS booker_member_id, m.student_id AS booker_student_id,
       m.first_name AS booker_first_name, m.last_name AS booker_last_name,
       m.nickname AS booker_nickname, m.picture_path AS booker_picture_path
FROM booking_requests br
LEFT JOIN members m ON m.id = br.booker_id
WHERE br.start >= $1
ORDER BY br.start ASC NULLS LAST, br."end" ASC NULLS LAST, br.status ASC
`

type ListUpcomingBookingRequestsRow struct {
	ID                pgtype.UUID          `json:"id"`
	BookerID          pgtype.UUID          `json:"booker_id"`
	Start             pgtype.Timestamptz   `json:"start"`
	End               pgtype.Timestamptz   `json:"end"`
	Created           pgtype.Timestamptz   `json:"created"`
	Event             pgtype.Text          `json:"event"`
	Status            BookingRequestStatus `json:"status"`
	BookerMemberID    pgtype.UUID          `json:"booker_member_id"`
	BookerStudentID   pgtype.Text          `json:"booker_student_id"`
	BookerFirstName   pgtype.Text          `json:"booker_first_name"`
	BookerLastName    pgtype.Text          `json:"booker_last_name"`
	BookerNickname    pgtype.Text          `json:"booker_nickname"`
	BookerPicturePath pgtype.Text          `json:"booker_picture_path"`
}

// Mirrors the old app's getUpcomingBookingRequests: every request starting
// on or after `since` (callers pass now-1week, matching the old hardcoded
// window), regardless of booker - visibility is gated at the service layer
// (booking_request:read), not per-row ownership.
func (q *Queries) ListUpcomingBookingRequests(ctx context.Context, since pgtype.Timestamptz) ([]ListUpcomingBookingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingBookingRequests, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingBookingRequestsRow{}
	for rows.Next() {
		var i ListUpcomingBookingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.BookerID,
			&i.Start,
			&i.End,
			&i.Created,
			&i.Event,
			&i.Status,
			&i.BookerMemberID,
			&i.BookerStudentID,
			&i.BookerFirstName,
			&i.BookerLastName,
			&i.BookerNickname,
			&i.BookerPicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookable = `-- name: UpdateBookable :one
UPDATE bookables
SET name_sv = $2, name_en = $3, "isDisabled" = $4, door = $5, category_id = $6
WHERE id = $1
RETURNING id, name_sv, name_en, "isDisabled", door, category_id
`

type UpdateBookableParams struct {
	ID         pgtype.UUID `json:"id"`
	NameSv     string      `json:"name_sv"`
	NameEn     pgtype.Text `json:"name_en"`
	IsDisabled bool        `json:"isDisabled"`
	Door       pgtype.Text `json:"door"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type UpdateBookableRow struct {
	ID         pgtype.UUID `json:"id"`
	NameSv     string      `json:"name_sv"`
	NameEn     pgtype.Text `json:"name_en"`
	IsDisabled bool        `json:"isDisabled"`
	Door       pgtype.Text `json:"door"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) UpdateBookable(ctx context.Context, arg UpdateBookableParams) (UpdateBookableRow, error) {
	row := q.db.QueryRow(ctx, updateBookable,
		arg.ID,
		arg.NameSv,
		arg.NameEn,
		arg.IsDisabled,
		arg.Door,
		arg.CategoryID,
	)
	var i UpdateBookableRow
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.IsDisabled,
		&i.Door,
		&i.CategoryID,
	)
	return i, err
}

const updateBookableCategory = `-- name: UpdateBookableCategory :one
UPDATE bookable_categories SET name_sv = $2, name_en = $3
WHERE id = $1
RETURNING id, name_sv, name_en
`

type UpdateBookableCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	NameSv string      `json:"name_sv"`
	NameEn pgtype.Text `json:"name_en"`
}

func (q *Queries) UpdateBookableCategory(ctx context.Context, arg UpdateBookableCategoryParams) (BookableCategory, error) {
	row := q.db.QueryRow(ctx, updateBookableCategory, arg.ID, arg.NameSv, arg.NameEn)
	var i BookableCategory
	err := row.Scan(&i.ID, &i.NameSv, &i.NameEn)
	return i, err
}

const updateBookingRequest = `-- name: UpdateBookingRequest :one
UPDATE booking_requests
SET start = $2, "end" = $3, event = $4, status = $5
WHERE id = $1
RETURNING id, booker_id, start, "end", created, event, status
`

type UpdateBookingRequestParams struct {
	ID     pgtype.UUID          `json:"id"`
	Start  pgtype.Timestamptz   `json:"start"`
	End    pgtype.Timestamptz   `json:"end"`
	Event  pgtype.Text          `json:"event"`
	Status BookingRequestStatus `json:"status"`
}

// Full-replace of the editable fields, same PUT-dressed-as-PATCH
// convention as articles/events/songs. Status is passed through explicitly
// rather than left untouched - the service decides whether to reset it to
// PENDING (non-admin edit) or keep the caller-supplied value (admin edit),
// mirroring the old app's isAdmin branch exactly.
func (q *Queries) UpdateBookingRequest(ctx context.Context, arg UpdateBookingRequestParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, updateBookingRequest,
		arg.ID,
		arg.Start,
		arg.End,
		arg.Event,
		arg.Status,
	)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.BookerID,
		&i.Start,
		&i.End,
		&i.Created,
		&i.Event,
		&i.Status,
	)
	return i, err
}

const updateBookingRequestStatus = `-- name: UpdateBookingRequestStatus :one
UPDATE booking_requests SET status = $2
WHERE id = $1
RETURNING id, booker_id, start, "end", created, event, status
`

type UpdateBookingRequestStatusParams struct {
	ID     pgtype.UUID          `json:"id"`
	Status BookingRequestStatus `json:"status"`
}

func (q *Queries) UpdateBookingRequestStatus(ctx context.Context, arg UpdateBookingRequestStatusParams) (BookingRequest, error) {
	row := q.db.QueryRow(ctx, updateBookingRequestStatus, arg.ID, arg.Status)
	var i BookingRequest
	err := row.Scan(
		&i.ID,
		&i.BookerID,
		&i.Start,
		&i.End,
		&i.Created,
		&i.Event,
		&i.Status,
	)
	return i, err
}
