// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cafe.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCafeShift = `-- name: CreateCafeShift :one
INSERT INTO cafe_shifts (date, "workerId", time_slot)
VALUES ($1, $2, $3)
RETURNING id, date, "workerId", time_slot
`

type CreateCafeShiftParams struct {
	Date     pgtype.Timestamp `json:"date"`
	WorkerID pgtype.UUID      `json:"worker_id"`
	TimeSlot TimeSlots        `json:"time_slot"`
}

func (q *Queries) CreateCafeShift(ctx context.Context, arg CreateCafeShiftParams) (CafeShift, error) {
	row := q.db.QueryRow(ctx, createCafeShift, arg.Date, arg.WorkerID, arg.TimeSlot)
	var i CafeShift
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.WorkerId,
		&i.TimeSlot,
	)
	return i, err
}

const deleteCafeShift = `-- name: DeleteCafeShift :execrows
DELETE FROM cafe_shifts WHERE id = $1
`

func (q *Queries) DeleteCafeShift(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCafeShift, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCafeShiftByID = `-- name: GetCafeShiftByID :one
SELECT cs.id, cs.date, cs."workerId", cs.time_slot,
       m.id AS worker_member_id, m.student_id AS worker_student_id,
       m.first_name AS worker_first_name, m.last_name AS worker_last_name,
       m.nickname AS worker_nickname, m.picture_path AS worker_picture_path
FROM cafe_shifts cs
JOIN members m ON m.id = cs."workerId"
WHERE cs.id = $1
`

type GetCafeShiftByIDRow struct {
	ID                pgtype.UUID      `json:"id"`
	Date              pgtype.Timestamp `json:"date"`
	WorkerId          pgtype.UUID      `json:"workerId"`
	TimeSlot          TimeSlots        `json:"time_slot"`
	WorkerMemberID    pgtype.UUID      `json:"worker_member_id"`
	WorkerStudentID   pgtype.Text      `json:"worker_student_id"`
	WorkerFirstName   pgtype.Text      `json:"worker_first_name"`
	WorkerLastName    pgtype.Text      `json:"worker_last_name"`
	WorkerNickname    pgtype.Text      `json:"worker_nickname"`
	WorkerPicturePath pgtype.Text      `json:"worker_picture_path"`
}

// Re-fetches a single shift with its worker joined, after
// CreateCafeShift/UpdateCafeShiftWorker's own RETURNING (which has no room
// for the join) - used to build the full Shift (with nickname/picture)
// SetShift returns.
func (q *Queries) GetCafeShiftByID(ctx context.Context, id pgtype.UUID) (GetCafeShiftByIDRow, error) {
	row := q.db.QueryRow(ctx, getCafeShiftByID, id)
	var i GetCafeShiftByIDRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.WorkerId,
		&i.TimeSlot,
		&i.WorkerMemberID,
		&i.WorkerStudentID,
		&i.WorkerFirstName,
		&i.WorkerLastName,
		&i.WorkerNickname,
		&i.WorkerPicturePath,
	)
	return i, err
}

const getCiabattaByYearWeek = `-- name: GetCiabattaByYearWeek :one
SELECT id, year, week, name FROM ciabatta_of_the_week
WHERE year = $1 AND week = $2
`

type GetCiabattaByYearWeekParams struct {
	Year int32 `json:"year"`
	Week int32 `json:"week"`
}

func (q *Queries) GetCiabattaByYearWeek(ctx context.Context, arg GetCiabattaByYearWeekParams) (CiabattaOfTheWeek, error) {
	row := q.db.QueryRow(ctx, getCiabattaByYearWeek, arg.Year, arg.Week)
	var i CiabattaOfTheWeek
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Week,
		&i.Name,
	)
	return i, err
}

const listCafeShiftsInRange = `-- name: ListCafeShiftsInRange :many
SELECT cs.id, cs.date, cs."workerId", cs.time_slot,
       m.id AS worker_member_id, m.student_id AS worker_student_id,
       m.first_name AS worker_first_name, m.last_name AS worker_last_name,
       m.nickname AS worker_nickname, m.picture_path AS worker_picture_path
FROM cafe_shifts cs
JOIN members m ON m.id = cs."workerId"
WHERE cs.date >= $1 AND cs.date <= $2
ORDER BY cs.date ASC, cs.time_slot ASC
`

type ListCafeShiftsInRangeParams struct {
	StartDate pgtype.Timestamp `json:"start_date"`
	EndDate   pgtype.Timestamp `json:"end_date"`
}

type ListCafeShiftsInRangeRow struct {
	ID                pgtype.UUID      `json:"id"`
	Date              pgtype.Timestamp `json:"date"`
	WorkerId          pgtype.UUID      `json:"workerId"`
	TimeSlot          TimeSlots        `json:"time_slot"`
	WorkerMemberID    pgtype.UUID      `json:"worker_member_id"`
	WorkerStudentID   pgtype.Text      `json:"worker_student_id"`
	WorkerFirstName   pgtype.Text      `json:"worker_first_name"`
	WorkerLastName    pgtype.Text      `json:"worker_last_name"`
	WorkerNickname    pgtype.Text      `json:"worker_nickname"`
	WorkerPicturePath pgtype.Text      `json:"worker_picture_path"`
}

// Every shift (with its worker) in [start_date, end_date] inclusive -
// start_date/end_date share the same TIMESTAMP(3) precision as the
// column, so callers pass day-aligned bounds. Used both for a week's
// worth of shifts (ListShifts) and for a single day's shifts (the
// toggle logic in SetShift, which needs every slot for one date at once,
// mirroring the old updateSchedule action's single dayShifts query).
func (q *Queries) ListCafeShiftsInRange(ctx context.Context, arg ListCafeShiftsInRangeParams) ([]ListCafeShiftsInRangeRow, error) {
	rows, err := q.db.Query(ctx, listCafeShiftsInRange, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCafeShiftsInRangeRow{}
	for rows.Next() {
		var i ListCafeShiftsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.WorkerId,
			&i.TimeSlot,
			&i.WorkerMemberID,
			&i.WorkerStudentID,
			&i.WorkerFirstName,
			&i.WorkerLastName,
			&i.WorkerNickname,
			&i.WorkerPicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkdownsByPrefix = `-- name: ListMarkdownsByPrefix :many
SELECT name, markdown_sv, markdown_en
FROM markdowns
WHERE name LIKE $1
ORDER BY name ASC
`

// Lists every markdowns row whose name matches prefix (a plain LIKE
// pattern, e.g. "cafe:open%") - internal/cafe's own private reuse of the
// markdowns table, same pattern as internal/committees' direct
// GetMarkdown call. internal/markdown itself only ever fetches one named
// page at a time, so this doesn't belong there.
func (q *Queries) ListMarkdownsByPrefix(ctx context.Context, prefix string) ([]Markdown, error) {
	rows, err := q.db.Query(ctx, listMarkdownsByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Markdown{}
	for rows.Next() {
		var i Markdown
		if err := rows.Scan(&i.Name, &i.MarkdownSv, &i.MarkdownEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCafeShiftWorker = `-- name: UpdateCafeShiftWorker :one
UPDATE cafe_shifts SET "workerId" = $1
WHERE id = $2
RETURNING id, date, "workerId", time_slot
`

type UpdateCafeShiftWorkerParams struct {
	WorkerID pgtype.UUID `json:"worker_id"`
	ID       pgtype.UUID `json:"id"`
}

// Reassigns an existing shift to a different worker - the admin-only
// "there's already a shift here, but not this member's" branch.
func (q *Queries) UpdateCafeShiftWorker(ctx context.Context, arg UpdateCafeShiftWorkerParams) (CafeShift, error) {
	row := q.db.QueryRow(ctx, updateCafeShiftWorker, arg.WorkerID, arg.ID)
	var i CafeShift
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.WorkerId,
		&i.TimeSlot,
	)
	return i, err
}

const upsertCiabatta = `-- name: UpsertCiabatta :one
INSERT INTO ciabatta_of_the_week (year, week, name)
VALUES ($1, $2, $3)
ON CONFLICT (year, week) DO UPDATE SET name = $3
RETURNING id, year, week, name
`

type UpsertCiabattaParams struct {
	Year int32  `json:"year"`
	Week int32  `json:"week"`
	Name string `json:"name"`
}

func (q *Queries) UpsertCiabatta(ctx context.Context, arg UpsertCiabattaParams) (CiabattaOfTheWeek, error) {
	row := q.db.QueryRow(ctx, upsertCiabatta, arg.Year, arg.Week, arg.Name)
	var i CiabattaOfTheWeek
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Week,
		&i.Name,
	)
	return i, err
}
