// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: committees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommitteeByShortName = `-- name: GetCommitteeByShortName :one
SELECT c.id, c.name_sv, c.name_en, c.short_name, c.description_sv, c.description_en,
       c.dark_image_url, c.light_image_url, c.mono_image_url, c.symbol_url,
       c.banner_url, c.is_banner_text_light, c.preview_url,
       count(m.id) AS mandate_count,
       count(DISTINCT m.member_id) AS member_count
FROM committees c
LEFT JOIN positions p ON p.committee_id = c.id
LEFT JOIN mandates m ON m.position_id = p.id
    AND m.start_date <= CURRENT_DATE AND m.end_date >= CURRENT_DATE
WHERE c.short_name = $1
GROUP BY c.id
`

type GetCommitteeByShortNameRow struct {
	ID                pgtype.UUID `json:"id"`
	NameSv            string      `json:"name_sv"`
	NameEn            pgtype.Text `json:"name_en"`
	ShortName         pgtype.Text `json:"short_name"`
	DescriptionSv     pgtype.Text `json:"description_sv"`
	DescriptionEn     pgtype.Text `json:"description_en"`
	DarkImageUrl      pgtype.Text `json:"dark_image_url"`
	LightImageUrl     pgtype.Text `json:"light_image_url"`
	MonoImageUrl      pgtype.Text `json:"mono_image_url"`
	SymbolUrl         pgtype.Text `json:"symbol_url"`
	BannerUrl         pgtype.Text `json:"banner_url"`
	IsBannerTextLight bool        `json:"is_banner_text_light"`
	PreviewUrl        pgtype.Text `json:"preview_url"`
	MandateCount      int64       `json:"mandate_count"`
	MemberCount       int64       `json:"member_count"`
}

// Currently-active mandate/unique-member counts, same as
// ListCommitteesWithCounts - the committee detail page shows these too.
func (q *Queries) GetCommitteeByShortName(ctx context.Context, shortName pgtype.Text) (GetCommitteeByShortNameRow, error) {
	row := q.db.QueryRow(ctx, getCommitteeByShortName, shortName)
	var i GetCommitteeByShortNameRow
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.ShortName,
		&i.DescriptionSv,
		&i.DescriptionEn,
		&i.DarkImageUrl,
		&i.LightImageUrl,
		&i.MonoImageUrl,
		&i.SymbolUrl,
		&i.BannerUrl,
		&i.IsBannerTextLight,
		&i.PreviewUrl,
		&i.MandateCount,
		&i.MemberCount,
	)
	return i, err
}

const listCommitteesWithCounts = `-- name: ListCommitteesWithCounts :many
SELECT c.id, c.name_sv, c.name_en, c.short_name, c.description_sv, c.description_en,
       c.dark_image_url, c.light_image_url, c.mono_image_url, c.symbol_url,
       c.banner_url, c.is_banner_text_light, c.preview_url,
       count(m.id) AS mandate_count,
       count(DISTINCT m.member_id) AS member_count
FROM committees c
LEFT JOIN positions p ON p.committee_id = c.id
LEFT JOIN mandates m ON m.position_id = p.id
    AND m.start_date <= CURRENT_DATE AND m.end_date >= CURRENT_DATE
GROUP BY c.id
ORDER BY c.name_sv
`

type ListCommitteesWithCountsRow struct {
	ID                pgtype.UUID `json:"id"`
	NameSv            string      `json:"name_sv"`
	NameEn            pgtype.Text `json:"name_en"`
	ShortName         pgtype.Text `json:"short_name"`
	DescriptionSv     pgtype.Text `json:"description_sv"`
	DescriptionEn     pgtype.Text `json:"description_en"`
	DarkImageUrl      pgtype.Text `json:"dark_image_url"`
	LightImageUrl     pgtype.Text `json:"light_image_url"`
	MonoImageUrl      pgtype.Text `json:"mono_image_url"`
	SymbolUrl         pgtype.Text `json:"symbol_url"`
	BannerUrl         pgtype.Text `json:"banner_url"`
	IsBannerTextLight bool        `json:"is_banner_text_light"`
	PreviewUrl        pgtype.Text `json:"preview_url"`
	MandateCount      int64       `json:"mandate_count"`
	MemberCount       int64       `json:"member_count"`
}

// Full fields + currently-active mandate/unique-member counts, for the
// committee overview page (mirrors the old "about" page's query).
func (q *Queries) ListCommitteesWithCounts(ctx context.Context) ([]ListCommitteesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listCommitteesWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommitteesWithCountsRow{}
	for rows.Next() {
		var i ListCommitteesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.ShortName,
			&i.DescriptionSv,
			&i.DescriptionEn,
			&i.DarkImageUrl,
			&i.LightImageUrl,
			&i.MonoImageUrl,
			&i.SymbolUrl,
			&i.BannerUrl,
			&i.IsBannerTextLight,
			&i.PreviewUrl,
			&i.MandateCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommittee = `-- name: UpdateCommittee :one
UPDATE committees
SET name_sv = $2, name_en = $3, description_sv = $4, description_en = $5,
    dark_image_url = $6, light_image_url = $7, mono_image_url = $8, symbol_url = $9,
    banner_url = $10, is_banner_text_light = $11, preview_url = $12
WHERE short_name = $1
RETURNING id, name_sv, name_en, short_name, description_sv, description_en,
          dark_image_url, light_image_url, mono_image_url, symbol_url,
          banner_url, is_banner_text_light, preview_url
`

type UpdateCommitteeParams struct {
	ShortName         pgtype.Text `json:"short_name"`
	NameSv            string      `json:"name_sv"`
	NameEn            pgtype.Text `json:"name_en"`
	DescriptionSv     pgtype.Text `json:"description_sv"`
	DescriptionEn     pgtype.Text `json:"description_en"`
	DarkImageUrl      pgtype.Text `json:"dark_image_url"`
	LightImageUrl     pgtype.Text `json:"light_image_url"`
	MonoImageUrl      pgtype.Text `json:"mono_image_url"`
	SymbolUrl         pgtype.Text `json:"symbol_url"`
	BannerUrl         pgtype.Text `json:"banner_url"`
	IsBannerTextLight bool        `json:"is_banner_text_light"`
	PreviewUrl        pgtype.Text `json:"preview_url"`
}

func (q *Queries) UpdateCommittee(ctx context.Context, arg UpdateCommitteeParams) (Committee, error) {
	row := q.db.QueryRow(ctx, updateCommittee,
		arg.ShortName,
		arg.NameSv,
		arg.NameEn,
		arg.DescriptionSv,
		arg.DescriptionEn,
		arg.DarkImageUrl,
		arg.LightImageUrl,
		arg.MonoImageUrl,
		arg.SymbolUrl,
		arg.BannerUrl,
		arg.IsBannerTextLight,
		arg.PreviewUrl,
	)
	var i Committee
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.ShortName,
		&i.DescriptionSv,
		&i.DescriptionEn,
		&i.DarkImageUrl,
		&i.LightImageUrl,
		&i.MonoImageUrl,
		&i.SymbolUrl,
		&i.BannerUrl,
		&i.IsBannerTextLight,
		&i.PreviewUrl,
	)
	return i, err
}
