// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: committees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCommittees = `-- name: ListCommittees :many
SELECT id, name_sv, name_en, short_name, symbol_url FROM committees
WHERE $1::text IS NULL OR short_name = $1::text
ORDER BY name_sv
`

type ListCommitteesRow struct {
	ID        pgtype.UUID `json:"id"`
	NameSv    string      `json:"name_sv"`
	NameEn    pgtype.Text `json:"name_en"`
	ShortName pgtype.Text `json:"short_name"`
	SymbolUrl pgtype.Text `json:"symbol_url"`
}

func (q *Queries) ListCommittees(ctx context.Context, shortName pgtype.Text) ([]ListCommitteesRow, error) {
	rows, err := q.db.Query(ctx, listCommittees, shortName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommitteesRow{}
	for rows.Next() {
		var i ListCommitteesRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.ShortName,
			&i.SymbolUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
