// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticleComment = `-- name: CreateArticleComment :one
INSERT INTO article_comments (article_id, member_id, content, published)
VALUES ($1, $2, $3, now())
RETURNING id, published
`

type CreateArticleCommentParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	MemberID  pgtype.UUID `json:"member_id"`
	Content   pgtype.Text `json:"content"`
}

type CreateArticleCommentRow struct {
	ID        pgtype.UUID        `json:"id"`
	Published pgtype.Timestamptz `json:"published"`
}

func (q *Queries) CreateArticleComment(ctx context.Context, arg CreateArticleCommentParams) (CreateArticleCommentRow, error) {
	row := q.db.QueryRow(ctx, createArticleComment, arg.ArticleID, arg.MemberID, arg.Content)
	var i CreateArticleCommentRow
	err := row.Scan(&i.ID, &i.Published)
	return i, err
}

const deleteArticleComment = `-- name: DeleteArticleComment :exec
DELETE FROM article_comments
WHERE id = $1 AND article_id = $2
`

type DeleteArticleCommentParams struct {
	CommentID pgtype.UUID `json:"comment_id"`
	ArticleID pgtype.UUID `json:"article_id"`
}

func (q *Queries) DeleteArticleComment(ctx context.Context, arg DeleteArticleCommentParams) error {
	_, err := q.db.Exec(ctx, deleteArticleComment, arg.CommentID, arg.ArticleID)
	return err
}

const listArticleComments = `-- name: ListArticleComments :many
SELECT
    c.id, c.content, c.published,
    m.id AS member_id, m.student_id AS member_student_id,
    m.first_name AS member_first_name, m.last_name AS member_last_name,
    m.nickname AS member_nickname, m.picture_path AS member_picture_path
FROM article_comments c
JOIN members m ON m.id = c.member_id
WHERE c.article_id = $1
ORDER BY c.published ASC
`

type ListArticleCommentsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Content           pgtype.Text        `json:"content"`
	Published         pgtype.Timestamptz `json:"published"`
	MemberID          pgtype.UUID        `json:"member_id"`
	MemberStudentID   pgtype.Text        `json:"member_student_id"`
	MemberFirstName   pgtype.Text        `json:"member_first_name"`
	MemberLastName    pgtype.Text        `json:"member_last_name"`
	MemberNickname    pgtype.Text        `json:"member_nickname"`
	MemberPicturePath pgtype.Text        `json:"member_picture_path"`
}

func (q *Queries) ListArticleComments(ctx context.Context, articleID pgtype.UUID) ([]ListArticleCommentsRow, error) {
	rows, err := q.db.Query(ctx, listArticleComments, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticleCommentsRow{}
	for rows.Next() {
		var i ListArticleCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Published,
			&i.MemberID,
			&i.MemberStudentID,
			&i.MemberFirstName,
			&i.MemberLastName,
			&i.MemberNickname,
			&i.MemberPicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
