// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_authors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCustomAuthors = `-- name: ListCustomAuthors :many
SELECT id, name_sv, name_en, image_url FROM custom_authors ORDER BY name_sv
`

type ListCustomAuthorsRow struct {
	ID       pgtype.UUID `json:"id"`
	NameSv   string      `json:"name_sv"`
	NameEn   pgtype.Text `json:"name_en"`
	ImageUrl pgtype.Text `json:"image_url"`
}

// Unfiltered: the old TS backend restricted this list to custom authors
// whose custom_author_roles matched one of the member's Keycloak-derived
// roles (getDerivedRoles) - that role-derivation system isn't ported to Go
// (see ../../DESIGN.md's Auth section on the mock RBAC gap), so for now
// every member can choose from every custom author. Revisit once real
// roles exist.
func (q *Queries) ListCustomAuthors(ctx context.Context) ([]ListCustomAuthorsRow, error) {
	rows, err := q.db.Query(ctx, listCustomAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomAuthorsRow{}
	for rows.Next() {
		var i ListCustomAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
