// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDoorAccessPolicy = `-- name: CreateDoorAccessPolicy :one
INSERT INTO door_access_policies (door_name, role, student_id, start_datetime, end_datetime, is_ban, information)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, door_name, role, student_id, start_datetime, end_datetime, is_ban, information
`

type CreateDoorAccessPolicyParams struct {
	DoorName      string             `json:"door_name"`
	Role          pgtype.Text        `json:"role"`
	StudentID     pgtype.Text        `json:"student_id"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
	IsBan         bool               `json:"is_ban"`
	Information   pgtype.Text        `json:"information"`
}

func (q *Queries) CreateDoorAccessPolicy(ctx context.Context, arg CreateDoorAccessPolicyParams) (DoorAccessPolicy, error) {
	row := q.db.QueryRow(ctx, createDoorAccessPolicy,
		arg.DoorName,
		arg.Role,
		arg.StudentID,
		arg.StartDatetime,
		arg.EndDatetime,
		arg.IsBan,
		arg.Information,
	)
	var i DoorAccessPolicy
	err := row.Scan(
		&i.ID,
		&i.DoorName,
		&i.Role,
		&i.StudentID,
		&i.StartDatetime,
		&i.EndDatetime,
		&i.IsBan,
		&i.Information,
	)
	return i, err
}

const deleteDoorAccessPolicy = `-- name: DeleteDoorAccessPolicy :exec
DELETE FROM door_access_policies WHERE id = $1
`

func (q *Queries) DeleteDoorAccessPolicy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDoorAccessPolicy, id)
	return err
}

const existsPositionWithPrefix = `-- name: ExistsPositionWithPrefix :one
SELECT EXISTS(SELECT 1 FROM positions WHERE id LIKE $1::text) AS exists
`

// pattern is built by the caller as "{prefix}%" - a real SQL LIKE
// wildcard, unlike the old TS's `startsWith(`${p}%`)`, which (per Prisma's
// literal-escaping of startsWith) only ever matched a position id that
// literally contained a "%" character, i.e. never. User-confirmed fix
// (2026-09-03, see DESIGN.md's Phase 10 entry): role-based door/create-form
// validation now does a real prefix match.
func (q *Queries) ExistsPositionWithPrefix(ctx context.Context, pattern string) (bool, error) {
	row := q.db.QueryRow(ctx, existsPositionWithPrefix, pattern)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDoorByName = `-- name: GetDoorByName :one
SELECT name, id, verbose_name FROM doors WHERE name = $1
`

func (q *Queries) GetDoorByName(ctx context.Context, name string) (Door, error) {
	row := q.db.QueryRow(ctx, getDoorByName, name)
	var i Door
	err := row.Scan(&i.Name, &i.ID, &i.VerboseName)
	return i, err
}

const listActiveDoorAccessPoliciesForSalto = `-- name: ListActiveDoorAccessPoliciesForSalto :many
SELECT role, student_id, is_ban
FROM door_access_policies
WHERE door_name = $1
  AND (start_datetime <= now() OR start_datetime IS NULL)
  AND (end_datetime >= now() OR end_datetime IS NULL)
`

type ListActiveDoorAccessPoliciesForSaltoRow struct {
	Role      pgtype.Text `json:"role"`
	StudentID pgtype.Text `json:"student_id"`
	IsBan     bool        `json:"is_ban"`
}

// The real security-relevant read: policies currently in their active
// window (both start and end), for GET /salto/{door} to resolve into an
// allowed-student list. Unlike ListDoorAccessPoliciesForAdmin, a
// not-yet-started policy is excluded here - matches the old +server.ts's
// own filter exactly.
func (q *Queries) ListActiveDoorAccessPoliciesForSalto(ctx context.Context, doorName string) ([]ListActiveDoorAccessPoliciesForSaltoRow, error) {
	rows, err := q.db.Query(ctx, listActiveDoorAccessPoliciesForSalto, doorName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDoorAccessPoliciesForSaltoRow{}
	for rows.Next() {
		var i ListActiveDoorAccessPoliciesForSaltoRow
		if err := rows.Scan(&i.Role, &i.StudentID, &i.IsBan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePositionsForMemberByStudentID = `-- name: ListActivePositionsForMemberByStudentID :many
SELECT p.id, p.name_sv, p.name_en, p.board_member
FROM positions p
JOIN mandates ma ON ma.position_id = p.id
JOIN members m ON m.id = ma.member_id
WHERE m.student_id = $1
  AND ma.start_date <= CURRENT_DATE AND ma.end_date >= CURRENT_DATE
`

type ListActivePositionsForMemberByStudentIDRow struct {
	ID          string      `json:"id"`
	NameSv      string      `json:"name_sv"`
	NameEn      pgtype.Text `json:"name_en"`
	BoardMember bool        `json:"board_member"`
}

// Backs the member profile page's own "which doors do I have access to"
// widget (self-view only) - a member's currently-held positions, used to
// both derive candidate door-policy roles and to display position names
// instead of raw role strings in the result.
func (q *Queries) ListActivePositionsForMemberByStudentID(ctx context.Context, studentID pgtype.Text) ([]ListActivePositionsForMemberByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listActivePositionsForMemberByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivePositionsForMemberByStudentIDRow{}
	for rows.Next() {
		var i ListActivePositionsForMemberByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.BoardMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoorAccessPoliciesForAdmin = `-- name: ListDoorAccessPoliciesForAdmin :many
SELECT dap.id, dap.door_name, dap.role, dap.student_id, dap.start_datetime,
       dap.end_datetime, dap.is_ban, dap.information,
       m.id AS member_id, m.first_name AS member_first_name,
       m.last_name AS member_last_name, m.nickname AS member_nickname
FROM door_access_policies dap
LEFT JOIN members m ON m.student_id = dap.student_id
WHERE dap.door_name = $1
  AND (dap.end_datetime >= now() OR dap.end_datetime IS NULL)
ORDER BY dap.start_datetime ASC, dap.role ASC, dap.student_id ASC
`

type ListDoorAccessPoliciesForAdminRow struct {
	ID              pgtype.UUID        `json:"id"`
	DoorName        string             `json:"door_name"`
	Role            pgtype.Text        `json:"role"`
	StudentID       pgtype.Text        `json:"student_id"`
	StartDatetime   pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime     pgtype.Timestamptz `json:"end_datetime"`
	IsBan           bool               `json:"is_ban"`
	Information     pgtype.Text        `json:"information"`
	MemberID        pgtype.UUID        `json:"member_id"`
	MemberFirstName pgtype.Text        `json:"member_first_name"`
	MemberLastName  pgtype.Text        `json:"member_last_name"`
	MemberNickname  pgtype.Text        `json:"member_nickname"`
}

// The admin edit-door page's own list: every non-expired policy for a
// door (start in the future is fine, still shown - only end in the past
// is excluded), joined to the member it names if it's a studentId-scoped
// row. Deliberately not filtered by start_datetime, unlike
// ListActiveDoorAccessPoliciesForSalto below - mirrors the old
// edit/[slug]/+page.server.ts load exactly.
func (q *Queries) ListDoorAccessPoliciesForAdmin(ctx context.Context, doorName string) ([]ListDoorAccessPoliciesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listDoorAccessPoliciesForAdmin, doorName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoorAccessPoliciesForAdminRow{}
	for rows.Next() {
		var i ListDoorAccessPoliciesForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.DoorName,
			&i.Role,
			&i.StudentID,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.IsBan,
			&i.Information,
			&i.MemberID,
			&i.MemberFirstName,
			&i.MemberLastName,
			&i.MemberNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoorAccessPoliciesForMemberView = `-- name: ListDoorAccessPoliciesForMemberView :many
SELECT dap.door_name, dor.verbose_name, dap.role, dap.student_id,
       dap.start_datetime, dap.end_datetime
FROM door_access_policies dap
JOIN doors dor ON dor.name = dap.door_name
WHERE dap.is_ban = false
  AND (dap.start_datetime <= now() OR dap.start_datetime IS NULL)
  AND (dap.end_datetime >= now() OR dap.end_datetime IS NULL)
  AND (
    dap.student_id = $1
    OR dap.role = ANY($2::text[])
  )
`

type ListDoorAccessPoliciesForMemberViewParams struct {
	StudentID pgtype.Text `json:"student_id"`
	Roles     []string    `json:"roles"`
}

type ListDoorAccessPoliciesForMemberViewRow struct {
	DoorName      string             `json:"door_name"`
	VerboseName   string             `json:"verbose_name"`
	Role          pgtype.Text        `json:"role"`
	StudentID     pgtype.Text        `json:"student_id"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
}

// The self-view widget's own policy read: non-banned policies either
// naming this member's studentId directly, or naming one of their
// candidate derived roles (every dot-prefix of each held position id, plus
// "*"/"_"/"dsek.styr" as applicable - computed in Go, mirroring
// getDerivedRoles - and passed in as roles). Exact role equality, not a
// prefix LIKE - this is the opposite direction from salto's own matching
// (there, a stored role is a prefix of a position id; here, a candidate
// role is checked for exact membership).
func (q *Queries) ListDoorAccessPoliciesForMemberView(ctx context.Context, arg ListDoorAccessPoliciesForMemberViewParams) ([]ListDoorAccessPoliciesForMemberViewRow, error) {
	rows, err := q.db.Query(ctx, listDoorAccessPoliciesForMemberView, arg.StudentID, arg.Roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDoorAccessPoliciesForMemberViewRow{}
	for rows.Next() {
		var i ListDoorAccessPoliciesForMemberViewRow
		if err := rows.Scan(
			&i.DoorName,
			&i.VerboseName,
			&i.Role,
			&i.StudentID,
			&i.StartDatetime,
			&i.EndDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDoors = `-- name: ListDoors :many
SELECT name, id, verbose_name FROM doors ORDER BY verbose_name
`

func (q *Queries) ListDoors(ctx context.Context) ([]Door, error) {
	rows, err := q.db.Query(ctx, listDoors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Door{}
	for rows.Next() {
		var i Door
		if err := rows.Scan(&i.Name, &i.ID, &i.VerboseName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionIDsMatchingPrefixes = `-- name: ListPositionIDsMatchingPrefixes :many
SELECT id FROM positions WHERE id LIKE ANY($1::text[])
`

// patterns are caller-built "{role}%" LIKE patterns, one per non-wildcard
// role a door policy names - see ExistsPositionWithPrefix's doc comment for
// why this is a real prefix match, not the old app's broken literal one.
func (q *Queries) ListPositionIDsMatchingPrefixes(ctx context.Context, patterns []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPositionIDsMatchingPrefixes, patterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMemberStudentIDs = `-- name: ListRecentMemberStudentIDs :many
SELECT student_id FROM members
WHERE class_year >= $1::int AND student_id IS NOT NULL
`

// Backs the "*" wildcard role (see 2024-11-25's "Added support for
// wildcard roles in door access policies") - every member whose class year
// is within the last ~10 years, matching the old app's
// `classYear: {gte: currentYear - 10}` exactly.
func (q *Queries) ListRecentMemberStudentIDs(ctx context.Context, minClassYear int32) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listRecentMemberStudentIDs, minClassYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var student_id pgtype.Text
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentIDsForActivePositions = `-- name: ListStudentIDsForActivePositions :many
SELECT DISTINCT m.student_id
FROM mandates ma
JOIN members m ON m.id = ma.member_id
WHERE ma.position_id = ANY($1::text[])
  AND ma.start_date <= CURRENT_DATE AND ma.end_date >= CURRENT_DATE
  AND m.student_id IS NOT NULL
`

// Current (start_date <= today <= end_date) mandate holders of any of the
// given positions - the role-based half of salto's allowed-student list.
func (q *Queries) ListStudentIDsForActivePositions(ctx context.Context, positionIds []string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listStudentIDsForActivePositions, positionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var student_id pgtype.Text
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
