// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: elections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createElection = `-- name: CreateElection :one
INSERT INTO elections (committee_id, markdown_sv, markdown_en, link, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, committee_id, markdown_sv, markdown_en, link, created_at, expires_at
`

type CreateElectionParams struct {
	CommitteeID pgtype.UUID        `json:"committee_id"`
	MarkdownSv  string             `json:"markdown_sv"`
	MarkdownEn  pgtype.Text        `json:"markdown_en"`
	Link        string             `json:"link"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateElection(ctx context.Context, arg CreateElectionParams) (Election, error) {
	row := q.db.QueryRow(ctx, createElection,
		arg.CommitteeID,
		arg.MarkdownSv,
		arg.MarkdownEn,
		arg.Link,
		arg.ExpiresAt,
	)
	var i Election
	err := row.Scan(
		&i.ID,
		&i.CommitteeID,
		&i.MarkdownSv,
		&i.MarkdownEn,
		&i.Link,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteElection = `-- name: DeleteElection :execrows
DELETE FROM elections WHERE id = $1
`

// Hard delete - the elections table has no removed_at/deleted_at column at
// all, unlike Song/Article/GoverningDocument.
func (q *Queries) DeleteElection(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteElection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getElectionByID = `-- name: GetElectionByID :one
SELECT
    e.id, e.committee_id, e.markdown_sv, e.markdown_en, e.link, e.created_at, e.expires_at,
    c.name_sv AS committee_name_sv,
    c.name_en AS committee_name_en,
    c.dark_image_url AS committee_dark_image_url,
    c.light_image_url AS committee_light_image_url,
    c.mono_image_url AS committee_mono_image_url
FROM elections e
JOIN committees c ON c.id = e.committee_id
WHERE e.id = $1
`

type GetElectionByIDRow struct {
	ID                     pgtype.UUID        `json:"id"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
	MarkdownSv             string             `json:"markdown_sv"`
	MarkdownEn             pgtype.Text        `json:"markdown_en"`
	Link                   string             `json:"link"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CommitteeNameSv        string             `json:"committee_name_sv"`
	CommitteeNameEn        pgtype.Text        `json:"committee_name_en"`
	CommitteeDarkImageUrl  pgtype.Text        `json:"committee_dark_image_url"`
	CommitteeLightImageUrl pgtype.Text        `json:"committee_light_image_url"`
	CommitteeMonoImageUrl  pgtype.Text        `json:"committee_mono_image_url"`
}

// Unconstrained by expiry (unlike ListOpenElections) - the edit page looks
// up an election by id regardless of whether it has already expired,
// matching prisma.election.findFirst({where: {id}}).
func (q *Queries) GetElectionByID(ctx context.Context, id pgtype.UUID) (GetElectionByIDRow, error) {
	row := q.db.QueryRow(ctx, getElectionByID, id)
	var i GetElectionByIDRow
	err := row.Scan(
		&i.ID,
		&i.CommitteeID,
		&i.MarkdownSv,
		&i.MarkdownEn,
		&i.Link,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.CommitteeNameSv,
		&i.CommitteeNameEn,
		&i.CommitteeDarkImageUrl,
		&i.CommitteeLightImageUrl,
		&i.CommitteeMonoImageUrl,
	)
	return i, err
}

const listOpenElections = `-- name: ListOpenElections :many
SELECT
    e.id, e.committee_id, e.markdown_sv, e.markdown_en, e.link, e.created_at, e.expires_at,
    c.name_sv AS committee_name_sv,
    c.name_en AS committee_name_en,
    c.dark_image_url AS committee_dark_image_url,
    c.light_image_url AS committee_light_image_url,
    c.mono_image_url AS committee_mono_image_url
FROM elections e
JOIN committees c ON c.id = e.committee_id
WHERE e.expires_at >= now()
ORDER BY e.expires_at ASC
`

type ListOpenElectionsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
	MarkdownSv             string             `json:"markdown_sv"`
	MarkdownEn             pgtype.Text        `json:"markdown_en"`
	Link                   string             `json:"link"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	CommitteeNameSv        string             `json:"committee_name_sv"`
	CommitteeNameEn        pgtype.Text        `json:"committee_name_en"`
	CommitteeDarkImageUrl  pgtype.Text        `json:"committee_dark_image_url"`
	CommitteeLightImageUrl pgtype.Text        `json:"committee_light_image_url"`
	CommitteeMonoImageUrl  pgtype.Text        `json:"committee_mono_image_url"`
}

// Only elections that haven't expired yet, soonest-closing first - matches
// the old /elections page's prisma.election.findMany({where: {expiresAt:
// {gte: now()}}, orderBy: [{expiresAt: "asc"}]}) exactly. Joins the small
// slice of committees columns the election card actually renders (icon +
// name), same fields the old page's committee `select` projected.
func (q *Queries) ListOpenElections(ctx context.Context) ([]ListOpenElectionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenElections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenElectionsRow{}
	for rows.Next() {
		var i ListOpenElectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CommitteeID,
			&i.MarkdownSv,
			&i.MarkdownEn,
			&i.Link,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.CommitteeNameSv,
			&i.CommitteeNameEn,
			&i.CommitteeDarkImageUrl,
			&i.CommitteeLightImageUrl,
			&i.CommitteeMonoImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateElection = `-- name: UpdateElection :one
UPDATE elections
SET committee_id = $1,
    markdown_sv  = $2,
    markdown_en  = $3,
    link         = $4,
    expires_at   = $5
WHERE id = $6
RETURNING id, committee_id, markdown_sv, markdown_en, link, created_at, expires_at
`

type UpdateElectionParams struct {
	CommitteeID pgtype.UUID        `json:"committee_id"`
	MarkdownSv  string             `json:"markdown_sv"`
	MarkdownEn  pgtype.Text        `json:"markdown_en"`
	Link        string             `json:"link"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateElection(ctx context.Context, arg UpdateElectionParams) (Election, error) {
	row := q.db.QueryRow(ctx, updateElection,
		arg.CommitteeID,
		arg.MarkdownSv,
		arg.MarkdownEn,
		arg.Link,
		arg.ExpiresAt,
		arg.ID,
	)
	var i Election
	err := row.Scan(
		&i.ID,
		&i.CommitteeID,
		&i.MarkdownSv,
		&i.MarkdownEn,
		&i.Link,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
