// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_aliases.sql

package db

import (
	"context"
)

const listEmailAliasesForPosition = `-- name: ListEmailAliasesForPosition :many
SELECT id, position_id, email FROM email_aliases WHERE position_id = $1 ORDER BY email
`

func (q *Queries) ListEmailAliasesForPosition(ctx context.Context, positionID string) ([]EmailAlias, error) {
	rows, err := q.db.Query(ctx, listEmailAliasesForPosition, positionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailAlias{}
	for rows.Next() {
		var i EmailAlias
		if err := rows.Scan(&i.ID, &i.PositionID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
