// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_attendance.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEventGoing = `-- name: AddEventGoing :exec

INSERT INTO _event_going ("A", "B")
VALUES ($1, $2)
ON CONFLICT ("A", "B") DO NOTHING
`

type AddEventGoingParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

// Going/interested are mutually exclusive in the UI (see
// internal/events.Service.SetGoing/SetInterested/ClearAttendance), but that
// exclusivity isn't a DB constraint - same situation as the old Prisma
// code, which only enforced it by always writing both relations together
// from three fixed call sites. Each pair of queries below is called
// together for that reason.
func (q *Queries) AddEventGoing(ctx context.Context, arg AddEventGoingParams) error {
	_, err := q.db.Exec(ctx, addEventGoing, arg.EventID, arg.MemberID)
	return err
}

const addEventInterested = `-- name: AddEventInterested :exec
INSERT INTO _event_interested ("A", "B")
VALUES ($1, $2)
ON CONFLICT ("A", "B") DO NOTHING
`

type AddEventInterestedParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) AddEventInterested(ctx context.Context, arg AddEventInterestedParams) error {
	_, err := q.db.Exec(ctx, addEventInterested, arg.EventID, arg.MemberID)
	return err
}

const listEventGoing = `-- name: ListEventGoing :many
SELECT m.id, m.student_id, m.first_name, m.last_name, m.nickname, m.picture_path
FROM _event_going g
JOIN members m ON m.id = g."B"
WHERE g."A" = $1
ORDER BY m.first_name
`

type ListEventGoingRow struct {
	ID          pgtype.UUID `json:"id"`
	StudentID   pgtype.Text `json:"student_id"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	Nickname    pgtype.Text `json:"nickname"`
	PicturePath pgtype.Text `json:"picture_path"`
}

func (q *Queries) ListEventGoing(ctx context.Context, eventID pgtype.UUID) ([]ListEventGoingRow, error) {
	rows, err := q.db.Query(ctx, listEventGoing, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventGoingRow{}
	for rows.Next() {
		var i ListEventGoingRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Nickname,
			&i.PicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventInterested = `-- name: ListEventInterested :many
SELECT m.id, m.student_id, m.first_name, m.last_name, m.nickname, m.picture_path
FROM _event_interested i
JOIN members m ON m.id = i."B"
WHERE i."A" = $1
ORDER BY m.first_name
`

type ListEventInterestedRow struct {
	ID          pgtype.UUID `json:"id"`
	StudentID   pgtype.Text `json:"student_id"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	Nickname    pgtype.Text `json:"nickname"`
	PicturePath pgtype.Text `json:"picture_path"`
}

func (q *Queries) ListEventInterested(ctx context.Context, eventID pgtype.UUID) ([]ListEventInterestedRow, error) {
	rows, err := q.db.Query(ctx, listEventInterested, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventInterestedRow{}
	for rows.Next() {
		var i ListEventInterestedRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Nickname,
			&i.PicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEventGoing = `-- name: RemoveEventGoing :exec
DELETE FROM _event_going
WHERE "A" = $1 AND "B" = $2
`

type RemoveEventGoingParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) RemoveEventGoing(ctx context.Context, arg RemoveEventGoingParams) error {
	_, err := q.db.Exec(ctx, removeEventGoing, arg.EventID, arg.MemberID)
	return err
}

const removeEventInterested = `-- name: RemoveEventInterested :exec
DELETE FROM _event_interested
WHERE "A" = $1 AND "B" = $2
`

type RemoveEventInterestedParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) RemoveEventInterested(ctx context.Context, arg RemoveEventInterestedParams) error {
	_, err := q.db.Exec(ctx, removeEventInterested, arg.EventID, arg.MemberID)
	return err
}
