// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEventComment = `-- name: CreateEventComment :one
INSERT INTO event_comments (event_id, member_id, content, published)
VALUES ($1, $2, $3, now())
RETURNING id, published
`

type CreateEventCommentParams struct {
	EventID  pgtype.UUID `json:"event_id"`
	MemberID pgtype.UUID `json:"member_id"`
	Content  pgtype.Text `json:"content"`
}

type CreateEventCommentRow struct {
	ID        pgtype.UUID        `json:"id"`
	Published pgtype.Timestamptz `json:"published"`
}

func (q *Queries) CreateEventComment(ctx context.Context, arg CreateEventCommentParams) (CreateEventCommentRow, error) {
	row := q.db.QueryRow(ctx, createEventComment, arg.EventID, arg.MemberID, arg.Content)
	var i CreateEventCommentRow
	err := row.Scan(&i.ID, &i.Published)
	return i, err
}

const deleteEventComment = `-- name: DeleteEventComment :exec
DELETE FROM event_comments
WHERE id = $1 AND event_id = $2
`

type DeleteEventCommentParams struct {
	CommentID pgtype.UUID `json:"comment_id"`
	EventID   pgtype.UUID `json:"event_id"`
}

func (q *Queries) DeleteEventComment(ctx context.Context, arg DeleteEventCommentParams) error {
	_, err := q.db.Exec(ctx, deleteEventComment, arg.CommentID, arg.EventID)
	return err
}

const listEventComments = `-- name: ListEventComments :many
SELECT
    c.id, c.content, c.published,
    m.id AS member_id, m.student_id AS member_student_id,
    m.first_name AS member_first_name, m.last_name AS member_last_name,
    m.nickname AS member_nickname, m.picture_path AS member_picture_path
FROM event_comments c
JOIN members m ON m.id = c.member_id
WHERE c.event_id = $1
ORDER BY c.published ASC
`

type ListEventCommentsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Content           pgtype.Text        `json:"content"`
	Published         pgtype.Timestamptz `json:"published"`
	MemberID          pgtype.UUID        `json:"member_id"`
	MemberStudentID   pgtype.Text        `json:"member_student_id"`
	MemberFirstName   pgtype.Text        `json:"member_first_name"`
	MemberLastName    pgtype.Text        `json:"member_last_name"`
	MemberNickname    pgtype.Text        `json:"member_nickname"`
	MemberPicturePath pgtype.Text        `json:"member_picture_path"`
}

func (q *Queries) ListEventComments(ctx context.Context, eventID pgtype.UUID) ([]ListEventCommentsRow, error) {
	rows, err := q.db.Query(ctx, listEventComments, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventCommentsRow{}
	for rows.Next() {
		var i ListEventCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Published,
			&i.MemberID,
			&i.MemberStudentID,
			&i.MemberFirstName,
			&i.MemberLastName,
			&i.MemberNickname,
			&i.MemberPicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
