// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventSlugsWithPrefix = `-- name: CountEventSlugsWithPrefix :one
SELECT count(*) FROM events WHERE slug LIKE $1 || '%'
`

func (q *Queries) CountEventSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countEventSlugsWithPrefix, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvents = `-- name: CountEvents :one
SELECT count(*) FROM events e
WHERE (e.removed_at IS NULL OR e.removed_at > now())
  AND (
    (NOT $1::bool AND e.end_datetime >= now())
    OR ($1::bool AND e.end_datetime <= now())
  )
  AND (
    $2::text IS NULL
    OR e.title_sv ILIKE '%' || $2::text || '%'
    OR e.title_en ILIKE '%' || $2::text || '%'
    OR e.short_description_sv ILIKE '%' || $2::text || '%'
    OR e.short_description_en ILIKE '%' || $2::text || '%'
    OR e.description_sv ILIKE '%' || $2::text || '%'
    OR e.description_en ILIKE '%' || $2::text || '%'
  )
  AND (
    $3::uuid[] IS NULL
    OR EXISTS (
        SELECT 1 FROM _event_tags t
        WHERE t."A" = e.id AND t."B" = ANY($3::uuid[])
    )
  )
`

type CountEventsParams struct {
	Past   bool          `json:"past"`
	Search pgtype.Text   `json:"search"`
	TagIds []pgtype.UUID `json:"tag_ids"`
}

func (q *Queries) CountEvents(ctx context.Context, arg CountEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, arg.Past, arg.Search, arg.TagIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    title_sv, title_en, description_sv, description_en, link, location,
    organizer, author_id, short_description_sv, short_description_en,
    start_datetime, end_datetime, slug, "imageUrl", alarm_active,
    is_cancelled, recurring_parent_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
) RETURNING id, slug
`

type CreateEventParams struct {
	TitleSv            string             `json:"title_sv"`
	TitleEn            pgtype.Text        `json:"title_en"`
	DescriptionSv      string             `json:"description_sv"`
	DescriptionEn      pgtype.Text        `json:"description_en"`
	Link               pgtype.Text        `json:"link"`
	Location           pgtype.Text        `json:"location"`
	Organizer          string             `json:"organizer"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	ShortDescriptionSv pgtype.Text        `json:"short_description_sv"`
	ShortDescriptionEn pgtype.Text        `json:"short_description_en"`
	StartDatetime      pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime        pgtype.Timestamptz `json:"end_datetime"`
	Slug               pgtype.Text        `json:"slug"`
	ImageUrl           pgtype.Text        `json:"imageUrl"`
	AlarmActive        pgtype.Bool        `json:"alarm_active"`
	IsCancelled        pgtype.Bool        `json:"is_cancelled"`
	RecurringParentID  pgtype.UUID        `json:"recurring_parent_id"`
}

type CreateEventRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug pgtype.Text `json:"slug"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.TitleSv,
		arg.TitleEn,
		arg.DescriptionSv,
		arg.DescriptionEn,
		arg.Link,
		arg.Location,
		arg.Organizer,
		arg.AuthorID,
		arg.ShortDescriptionSv,
		arg.ShortDescriptionEn,
		arg.StartDatetime,
		arg.EndDatetime,
		arg.Slug,
		arg.ImageUrl,
		arg.AlarmActive,
		arg.IsCancelled,
		arg.RecurringParentID,
	)
	var i CreateEventRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}

const createRecurringEvent = `-- name: CreateRecurringEvent :one
INSERT INTO "RecurringEvent" (
    separation_count, recurring_type, author_id, start_datetime, end_datetime
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id
`

type CreateRecurringEventParams struct {
	SeparationCount int32              `json:"separation_count"`
	RecurringType   RecurringType      `json:"recurring_type"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	StartDatetime   pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime     pgtype.Timestamptz `json:"end_datetime"`
}

func (q *Queries) CreateRecurringEvent(ctx context.Context, arg CreateRecurringEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRecurringEvent,
		arg.SeparationCount,
		arg.RecurringType,
		arg.AuthorID,
		arg.StartDatetime,
		arg.EndDatetime,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT
    e.id, e.title_sv, e.title_en, e.description_sv, e.description_en, e.link,
    e.location, e.organizer, e.author_id, e.short_description_sv,
    e.short_description_en, e.start_datetime, e.end_datetime, e.slug,
    e.alarm_active, e.removed_at, e."imageUrl", e.is_cancelled,
    e.recurring_parent_id,
    m.id AS author_member_id, m.student_id AS author_student_id,
    m.first_name AS author_first_name, m.last_name AS author_last_name,
    m.nickname AS author_nickname, m.picture_path AS author_picture_path,
    COALESCE(cm.n, 0)::int AS comment_count,
    COALESCE(go.n, 0)::int AS going_count,
    COALESCE(it.n, 0)::int AS interested_count
FROM events e
JOIN members m ON m.id = e.author_id
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM event_comments WHERE event_id = e.id
) cm ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _event_going WHERE "A" = e.id
) go ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _event_interested WHERE "A" = e.id
) it ON true
WHERE e.slug = $1
  AND (e.removed_at IS NULL OR e.removed_at > now())
`

type GetEventBySlugRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TitleSv            string             `json:"title_sv"`
	TitleEn            pgtype.Text        `json:"title_en"`
	DescriptionSv      string             `json:"description_sv"`
	DescriptionEn      pgtype.Text        `json:"description_en"`
	Link               pgtype.Text        `json:"link"`
	Location           pgtype.Text        `json:"location"`
	Organizer          string             `json:"organizer"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	ShortDescriptionSv pgtype.Text        `json:"short_description_sv"`
	ShortDescriptionEn pgtype.Text        `json:"short_description_en"`
	StartDatetime      pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime        pgtype.Timestamptz `json:"end_datetime"`
	Slug               pgtype.Text        `json:"slug"`
	AlarmActive        pgtype.Bool        `json:"alarm_active"`
	RemovedAt          pgtype.Timestamptz `json:"removed_at"`
	ImageUrl           pgtype.Text        `json:"imageUrl"`
	IsCancelled        pgtype.Bool        `json:"is_cancelled"`
	RecurringParentID  pgtype.UUID        `json:"recurring_parent_id"`
	AuthorMemberID     pgtype.UUID        `json:"author_member_id"`
	AuthorStudentID    pgtype.Text        `json:"author_student_id"`
	AuthorFirstName    pgtype.Text        `json:"author_first_name"`
	AuthorLastName     pgtype.Text        `json:"author_last_name"`
	AuthorNickname     pgtype.Text        `json:"author_nickname"`
	AuthorPicturePath  pgtype.Text        `json:"author_picture_path"`
	CommentCount       int32              `json:"comment_count"`
	GoingCount         int32              `json:"going_count"`
	InterestedCount    int32              `json:"interested_count"`
}

// Public lookup: hides soft-removed events, same visibility rule as
// ListEvents. The old TS getEvent() applied no such filter at all (see
// DESIGN.md's events section) - fixed here rather than replicated.
func (q *Queries) GetEventBySlug(ctx context.Context, slug pgtype.Text) (GetEventBySlugRow, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i GetEventBySlugRow
	err := row.Scan(
		&i.ID,
		&i.TitleSv,
		&i.TitleEn,
		&i.DescriptionSv,
		&i.DescriptionEn,
		&i.Link,
		&i.Location,
		&i.Organizer,
		&i.AuthorID,
		&i.ShortDescriptionSv,
		&i.ShortDescriptionEn,
		&i.StartDatetime,
		&i.EndDatetime,
		&i.Slug,
		&i.AlarmActive,
		&i.RemovedAt,
		&i.ImageUrl,
		&i.IsCancelled,
		&i.RecurringParentID,
		&i.AuthorMemberID,
		&i.AuthorStudentID,
		&i.AuthorFirstName,
		&i.AuthorLastName,
		&i.AuthorNickname,
		&i.AuthorPicturePath,
		&i.CommentCount,
		&i.GoingCount,
		&i.InterestedCount,
	)
	return i, err
}

const getEventIDBySlug = `-- name: GetEventIDBySlug :one
SELECT id FROM events WHERE slug = $1
`

func (q *Queries) GetEventIDBySlug(ctx context.Context, slug pgtype.Text) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEventIDBySlug, slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEventRowBySlug = `-- name: GetEventRowBySlug :one
SELECT
    e.id, e.title_sv, e.title_en, e.description_sv, e.description_en, e.link,
    e.location, e.organizer, e.author_id, e.short_description_sv,
    e.short_description_en, e.start_datetime, e.end_datetime, e.slug,
    e.alarm_active, e.removed_at, e."imageUrl", e.is_cancelled,
    e.recurring_parent_id,
    m.id AS author_member_id, m.student_id AS author_student_id,
    m.first_name AS author_first_name, m.last_name AS author_last_name,
    m.nickname AS author_nickname, m.picture_path AS author_picture_path,
    COALESCE(cm.n, 0)::int AS comment_count,
    COALESCE(go.n, 0)::int AS going_count,
    COALESCE(it.n, 0)::int AS interested_count
FROM events e
JOIN members m ON m.id = e.author_id
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM event_comments WHERE event_id = e.id
) cm ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _event_going WHERE "A" = e.id
) go ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _event_interested WHERE "A" = e.id
) it ON true
WHERE e.slug = $1
`

type GetEventRowBySlugRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TitleSv            string             `json:"title_sv"`
	TitleEn            pgtype.Text        `json:"title_en"`
	DescriptionSv      string             `json:"description_sv"`
	DescriptionEn      pgtype.Text        `json:"description_en"`
	Link               pgtype.Text        `json:"link"`
	Location           pgtype.Text        `json:"location"`
	Organizer          string             `json:"organizer"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	ShortDescriptionSv pgtype.Text        `json:"short_description_sv"`
	ShortDescriptionEn pgtype.Text        `json:"short_description_en"`
	StartDatetime      pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime        pgtype.Timestamptz `json:"end_datetime"`
	Slug               pgtype.Text        `json:"slug"`
	AlarmActive        pgtype.Bool        `json:"alarm_active"`
	RemovedAt          pgtype.Timestamptz `json:"removed_at"`
	ImageUrl           pgtype.Text        `json:"imageUrl"`
	IsCancelled        pgtype.Bool        `json:"is_cancelled"`
	RecurringParentID  pgtype.UUID        `json:"recurring_parent_id"`
	AuthorMemberID     pgtype.UUID        `json:"author_member_id"`
	AuthorStudentID    pgtype.Text        `json:"author_student_id"`
	AuthorFirstName    pgtype.Text        `json:"author_first_name"`
	AuthorLastName     pgtype.Text        `json:"author_last_name"`
	AuthorNickname     pgtype.Text        `json:"author_nickname"`
	AuthorPicturePath  pgtype.Text        `json:"author_picture_path"`
	CommentCount       int32              `json:"comment_count"`
	GoingCount         int32              `json:"going_count"`
	InterestedCount    int32              `json:"interested_count"`
}

// Unfiltered lookup: no removed_at filter. Used internally after
// create/update, and by GetAny for callers - like an edit page - that need
// to load an event regardless of soft-delete status.
func (q *Queries) GetEventRowBySlug(ctx context.Context, slug pgtype.Text) (GetEventRowBySlugRow, error) {
	row := q.db.QueryRow(ctx, getEventRowBySlug, slug)
	var i GetEventRowBySlugRow
	err := row.Scan(
		&i.ID,
		&i.TitleSv,
		&i.TitleEn,
		&i.DescriptionSv,
		&i.DescriptionEn,
		&i.Link,
		&i.Location,
		&i.Organizer,
		&i.AuthorID,
		&i.ShortDescriptionSv,
		&i.ShortDescriptionEn,
		&i.StartDatetime,
		&i.EndDatetime,
		&i.Slug,
		&i.AlarmActive,
		&i.RemovedAt,
		&i.ImageUrl,
		&i.IsCancelled,
		&i.RecurringParentID,
		&i.AuthorMemberID,
		&i.AuthorStudentID,
		&i.AuthorFirstName,
		&i.AuthorLastName,
		&i.AuthorNickname,
		&i.AuthorPicturePath,
		&i.CommentCount,
		&i.GoingCount,
		&i.InterestedCount,
	)
	return i, err
}

const getRecurringEvent = `-- name: GetRecurringEvent :one
SELECT id, separation_count, recurring_type, author_id, start_datetime, end_datetime
FROM "RecurringEvent"
WHERE id = $1
`

func (q *Queries) GetRecurringEvent(ctx context.Context, id pgtype.UUID) (RecurringEvent, error) {
	row := q.db.QueryRow(ctx, getRecurringEvent, id)
	var i RecurringEvent
	err := row.Scan(
		&i.ID,
		&i.SeparationCount,
		&i.RecurringType,
		&i.AuthorID,
		&i.StartDatetime,
		&i.EndDatetime,
	)
	return i, err
}

const listEventSiblings = `-- name: ListEventSiblings :many
SELECT id, slug, start_datetime, end_datetime
FROM events
WHERE recurring_parent_id = $1
  AND (
    $2::timestamptz IS NULL
    OR start_datetime >= $2::timestamptz
  )
ORDER BY start_datetime
`

type ListEventSiblingsParams struct {
	RecurringParentID pgtype.UUID        `json:"recurring_parent_id"`
	MinStartDatetime  pgtype.Timestamptz `json:"min_start_datetime"`
}

type ListEventSiblingsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Slug          pgtype.Text        `json:"slug"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
}

// Every other occurrence in a recurring series, for a FUTURE/ALL edit or
// delete. min_start_datetime narg'd out entirely (not just NULL) for ALL,
// set for FUTURE (see internal/events.Service.Update/Delete).
func (q *Queries) ListEventSiblings(ctx context.Context, arg ListEventSiblingsParams) ([]ListEventSiblingsRow, error) {
	rows, err := q.db.Query(ctx, listEventSiblings, arg.RecurringParentID, arg.MinStartDatetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventSiblingsRow{}
	for rows.Next() {
		var i ListEventSiblingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.StartDatetime,
			&i.EndDatetime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many

SELECT
    e.id, e.title_sv, e.title_en, e.description_sv, e.description_en, e.link,
    e.location, e.organizer, e.author_id, e.short_description_sv,
    e.short_description_en, e.start_datetime, e.end_datetime, e.slug,
    e.alarm_active, e.removed_at, e."imageUrl", e.is_cancelled,
    e.recurring_parent_id,
    m.id AS author_member_id, m.student_id AS author_student_id,
    m.first_name AS author_first_name, m.last_name AS author_last_name,
    m.nickname AS author_nickname, m.picture_path AS author_picture_path,
    COALESCE(cm.n, 0)::int AS comment_count,
    COALESCE(go.n, 0)::int AS going_count,
    COALESCE(it.n, 0)::int AS interested_count
FROM events e
JOIN members m ON m.id = e.author_id
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM event_comments WHERE event_id = e.id
) cm ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _event_going WHERE "A" = e.id
) go ON true
LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM _event_interested WHERE "A" = e.id
) it ON true
WHERE (e.removed_at IS NULL OR e.removed_at > now())
  AND (
    (NOT $1::bool AND e.end_datetime >= now())
    OR ($1::bool AND e.end_datetime <= now())
  )
  AND (
    $2::text IS NULL
    OR e.title_sv ILIKE '%' || $2::text || '%'
    OR e.title_en ILIKE '%' || $2::text || '%'
    OR e.short_description_sv ILIKE '%' || $2::text || '%'
    OR e.short_description_en ILIKE '%' || $2::text || '%'
    OR e.description_sv ILIKE '%' || $2::text || '%'
    OR e.description_en ILIKE '%' || $2::text || '%'
  )
  AND (
    $3::uuid[] IS NULL
    OR EXISTS (
        SELECT 1 FROM _event_tags t
        WHERE t."A" = e.id AND t."B" = ANY($3::uuid[])
    )
  )
ORDER BY
    (CASE WHEN $1::bool THEN e.start_datetime END) DESC NULLS LAST,
    (CASE WHEN NOT $1::bool THEN e.start_datetime END) ASC NULLS LAST
LIMIT $5 OFFSET $4
`

type ListEventsParams struct {
	Past   bool          `json:"past"`
	Search pgtype.Text   `json:"search"`
	TagIds []pgtype.UUID `json:"tag_ids"`
	Offset int32         `json:"offset"`
	Limit  int32         `json:"limit"`
}

type ListEventsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	TitleSv            string             `json:"title_sv"`
	TitleEn            pgtype.Text        `json:"title_en"`
	DescriptionSv      string             `json:"description_sv"`
	DescriptionEn      pgtype.Text        `json:"description_en"`
	Link               pgtype.Text        `json:"link"`
	Location           pgtype.Text        `json:"location"`
	Organizer          string             `json:"organizer"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	ShortDescriptionSv pgtype.Text        `json:"short_description_sv"`
	ShortDescriptionEn pgtype.Text        `json:"short_description_en"`
	StartDatetime      pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime        pgtype.Timestamptz `json:"end_datetime"`
	Slug               pgtype.Text        `json:"slug"`
	AlarmActive        pgtype.Bool        `json:"alarm_active"`
	RemovedAt          pgtype.Timestamptz `json:"removed_at"`
	ImageUrl           pgtype.Text        `json:"imageUrl"`
	IsCancelled        pgtype.Bool        `json:"is_cancelled"`
	RecurringParentID  pgtype.UUID        `json:"recurring_parent_id"`
	AuthorMemberID     pgtype.UUID        `json:"author_member_id"`
	AuthorStudentID    pgtype.Text        `json:"author_student_id"`
	AuthorFirstName    pgtype.Text        `json:"author_first_name"`
	AuthorLastName     pgtype.Text        `json:"author_last_name"`
	AuthorNickname     pgtype.Text        `json:"author_nickname"`
	AuthorPicturePath  pgtype.Text        `json:"author_picture_path"`
	CommentCount       int32              `json:"comment_count"`
	GoingCount         int32              `json:"going_count"`
	InterestedCount    int32              `json:"interested_count"`
}

// Shared column list for the "joined event" shape: event + author (plain
// member - events have no mandate/custom-author byline, see internal/events
// doc comments) + comment/going/interested counts. Duplicated across
// ListEvents/GetEventBySlug/GetEventRowBySlug because sqlc has no
// macro/fragment support (same situation as articles.sql).
// Ordering direction depends on 'past': upcoming events sort soonest-first
// (ASC), past events sort most-recent-first (DESC). sqlc can't parameterize
// ORDER BY directly, so both directions are expressed as CASE'd sort keys -
// exactly one is non-null per row depending on 'past', the other ties (NULL)
// and is ignored.
func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.Past,
		arg.Search,
		arg.TagIds,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TitleSv,
			&i.TitleEn,
			&i.DescriptionSv,
			&i.DescriptionEn,
			&i.Link,
			&i.Location,
			&i.Organizer,
			&i.AuthorID,
			&i.ShortDescriptionSv,
			&i.ShortDescriptionEn,
			&i.StartDatetime,
			&i.EndDatetime,
			&i.Slug,
			&i.AlarmActive,
			&i.RemovedAt,
			&i.ImageUrl,
			&i.IsCancelled,
			&i.RecurringParentID,
			&i.AuthorMemberID,
			&i.AuthorStudentID,
			&i.AuthorFirstName,
			&i.AuthorLastName,
			&i.AuthorNickname,
			&i.AuthorPicturePath,
			&i.CommentCount,
			&i.GoingCount,
			&i.InterestedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEvent = `-- name: SoftDeleteEvent :exec
UPDATE events SET removed_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEvent, id)
	return err
}

const softDeleteEventSeries = `-- name: SoftDeleteEventSeries :exec
UPDATE events SET removed_at = now()
WHERE recurring_parent_id = $1
  AND (
    $2::timestamptz IS NULL
    OR start_datetime >= $2::timestamptz
  )
`

type SoftDeleteEventSeriesParams struct {
	RecurringParentID pgtype.UUID        `json:"recurring_parent_id"`
	MinStartDatetime  pgtype.Timestamptz `json:"min_start_datetime"`
}

// Powers both FUTURE (min_start_datetime set) and ALL (narg'd out) series
// deletes in one statement, unlike the per-row loop UpdateEvent needs (a
// plain removed_at write has no per-row content to vary).
func (q *Queries) SoftDeleteEventSeries(ctx context.Context, arg SoftDeleteEventSeriesParams) error {
	_, err := q.db.Exec(ctx, softDeleteEventSeries, arg.RecurringParentID, arg.MinStartDatetime)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title_sv = $2,
    title_en = $3,
    description_sv = $4,
    description_en = $5,
    link = $6,
    location = $7,
    organizer = $8,
    short_description_sv = $9,
    short_description_en = $10,
    start_datetime = $11,
    end_datetime = $12,
    "imageUrl" = $13,
    alarm_active = $14,
    is_cancelled = $15
WHERE id = $1
RETURNING id, slug
`

type UpdateEventParams struct {
	ID                 pgtype.UUID        `json:"id"`
	TitleSv            string             `json:"title_sv"`
	TitleEn            pgtype.Text        `json:"title_en"`
	DescriptionSv      string             `json:"description_sv"`
	DescriptionEn      pgtype.Text        `json:"description_en"`
	Link               pgtype.Text        `json:"link"`
	Location           pgtype.Text        `json:"location"`
	Organizer          string             `json:"organizer"`
	ShortDescriptionSv pgtype.Text        `json:"short_description_sv"`
	ShortDescriptionEn pgtype.Text        `json:"short_description_en"`
	StartDatetime      pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime        pgtype.Timestamptz `json:"end_datetime"`
	ImageUrl           pgtype.Text        `json:"imageUrl"`
	AlarmActive        pgtype.Bool        `json:"alarm_active"`
	IsCancelled        pgtype.Bool        `json:"is_cancelled"`
}

type UpdateEventRow struct {
	ID   pgtype.UUID `json:"id"`
	Slug pgtype.Text `json:"slug"`
}

// Full-replace of content fields (same PUT-not-PATCH convention as
// articles), plus this occurrence's own start/end datetime. author_id is
// deliberately never reassigned here - see internal/events doc comments on
// why events diverge from articles' "always re-attribute to the editor"
// rule.
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.TitleSv,
		arg.TitleEn,
		arg.DescriptionSv,
		arg.DescriptionEn,
		arg.Link,
		arg.Location,
		arg.Organizer,
		arg.ShortDescriptionSv,
		arg.ShortDescriptionEn,
		arg.StartDatetime,
		arg.EndDatetime,
		arg.ImageUrl,
		arg.AlarmActive,
		arg.IsCancelled,
	)
	var i UpdateEventRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}
