// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEventTags = `-- name: AddEventTags :exec
INSERT INTO _event_tags ("A", "B")
SELECT $1, unnest($2::uuid[])
ON CONFLICT ("A", "B") DO NOTHING
`

type AddEventTagsParams struct {
	EventID pgtype.UUID   `json:"event_id"`
	TagIds  []pgtype.UUID `json:"tag_ids"`
}

func (q *Queries) AddEventTags(ctx context.Context, arg AddEventTagsParams) error {
	_, err := q.db.Exec(ctx, addEventTags, arg.EventID, arg.TagIds)
	return err
}

const clearEventTags = `-- name: ClearEventTags :exec
DELETE FROM _event_tags WHERE "A" = $1
`

func (q *Queries) ClearEventTags(ctx context.Context, eventID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearEventTags, eventID)
	return err
}

const listTagsForEvents = `-- name: ListTagsForEvents :many
SELECT t."A" AS event_id, tags.id, tags.name_sv, tags.name_en, tags.color, tags.is_default
FROM _event_tags t
JOIN tags ON tags.id = t."B"
WHERE t."A" = ANY($1::uuid[])
ORDER BY tags.name_sv
`

type ListTagsForEventsRow struct {
	EventID   pgtype.UUID `json:"event_id"`
	ID        pgtype.UUID `json:"id"`
	NameSv    string      `json:"name_sv"`
	NameEn    pgtype.Text `json:"name_en"`
	Color     pgtype.Text `json:"color"`
	IsDefault pgtype.Bool `json:"is_default"`
}

func (q *Queries) ListTagsForEvents(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListTagsForEventsRow, error) {
	rows, err := q.db.Query(ctx, listTagsForEvents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForEventsRow{}
	for rows.Next() {
		var i ListTagsForEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.Color,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
