// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: governing_documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoverningDocument = `-- name: CreateGoverningDocument :one
INSERT INTO documents (title, url, type)
VALUES ($1, $2, $3)
RETURNING id, title, url, type, created_at, updated_at, deleted_at
`

type CreateGoverningDocumentParams struct {
	Title string       `json:"title"`
	Url   string       `json:"url"`
	Type  DocumentType `json:"type"`
}

func (q *Queries) CreateGoverningDocument(ctx context.Context, arg CreateGoverningDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createGoverningDocument, arg.Title, arg.Url, arg.Type)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAnyGoverningDocumentByID = `-- name: GetAnyGoverningDocumentByID :one
SELECT id, title, url, type, created_at, updated_at, deleted_at
FROM documents
WHERE id = $1 AND deleted_at IS NULL
`

// Unconstrained by type, unlike GetGoverningDocumentByID above - the list
// page's delete action operates on any document by id regardless of type
// (MEETING/OTHER/etc. included), matching the old app's
// prisma.document.delete({where:{id}}) exactly.
func (q *Queries) GetAnyGoverningDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getAnyGoverningDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoverningDocumentByID = `-- name: GetGoverningDocumentByID :one
SELECT id, title, url, type, created_at, updated_at, deleted_at
FROM documents
WHERE id = $1 AND deleted_at IS NULL AND type IN ('POLICY', 'GUIDELINE')
`

// Constrained to POLICY/GUIDELINE, matching the old app's edit-lookup
// query - the other enum values have no create/edit UI anywhere.
func (q *Queries) GetGoverningDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getGoverningDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGoverningDocuments = `-- name: ListGoverningDocuments :many
SELECT id, title, url, type, created_at, updated_at, deleted_at
FROM documents
WHERE deleted_at IS NULL
ORDER BY title ASC
`

func (q *Queries) ListGoverningDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.Query(ctx, listGoverningDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGoverningDocument = `-- name: SoftDeleteGoverningDocument :exec
UPDATE documents SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteGoverningDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteGoverningDocument, id)
	return err
}

const updateGoverningDocument = `-- name: UpdateGoverningDocument :one
UPDATE documents
SET title = $2, url = $3, type = $4, updated_at = now()
WHERE id = $1
RETURNING id, title, url, type, created_at, updated_at, deleted_at
`

type UpdateGoverningDocumentParams struct {
	ID    pgtype.UUID  `json:"id"`
	Title string       `json:"title"`
	Url   string       `json:"url"`
	Type  DocumentType `json:"type"`
}

func (q *Queries) UpdateGoverningDocument(ctx context.Context, arg UpdateGoverningDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateGoverningDocument,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Type,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
