// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addArticleLike = `-- name: AddArticleLike :exec
INSERT INTO _article_likes ("A", "B")
VALUES ($1, $2)
ON CONFLICT ("A", "B") DO NOTHING
`

type AddArticleLikeParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	MemberID  pgtype.UUID `json:"member_id"`
}

func (q *Queries) AddArticleLike(ctx context.Context, arg AddArticleLikeParams) error {
	_, err := q.db.Exec(ctx, addArticleLike, arg.ArticleID, arg.MemberID)
	return err
}

const removeArticleLike = `-- name: RemoveArticleLike :exec
DELETE FROM _article_likes
WHERE "A" = $1 AND "B" = $2
`

type RemoveArticleLikeParams struct {
	ArticleID pgtype.UUID `json:"article_id"`
	MemberID  pgtype.UUID `json:"member_id"`
}

func (q *Queries) RemoveArticleLike(ctx context.Context, arg RemoveArticleLikeParams) error {
	_, err := q.db.Exec(ctx, removeArticleLike, arg.ArticleID, arg.MemberID)
	return err
}
