// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mandates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveMandatesForMember = `-- name: ListActiveMandatesForMember :many
SELECT m.id, p.id AS position_id, p.name_sv AS position_name_sv, p.name_en AS position_name_en
FROM mandates m
JOIN positions p ON p.id = m.position_id
WHERE m.member_id = $1
  AND m.start_date <= CURRENT_DATE
  AND m.end_date >= CURRENT_DATE
ORDER BY p.name_sv
`

type ListActiveMandatesForMemberRow struct {
	ID             pgtype.UUID `json:"id"`
	PositionID     string      `json:"position_id"`
	PositionNameSv string      `json:"position_name_sv"`
	PositionNameEn pgtype.Text `json:"position_name_en"`
}

// "Active" mirrors the old TS backend's author-options query: currently
// within the mandate's start/end date range.
func (q *Queries) ListActiveMandatesForMember(ctx context.Context, memberID pgtype.UUID) ([]ListActiveMandatesForMemberRow, error) {
	rows, err := q.db.Query(ctx, listActiveMandatesForMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveMandatesForMemberRow{}
	for rows.Next() {
		var i ListActiveMandatesForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.PositionNameSv,
			&i.PositionNameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
