// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markdowns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMarkdown = `-- name: GetMarkdown :one
SELECT name, markdown_sv, markdown_en FROM markdowns WHERE name = $1
`

func (q *Queries) GetMarkdown(ctx context.Context, name string) (Markdown, error) {
	row := q.db.QueryRow(ctx, getMarkdown, name)
	var i Markdown
	err := row.Scan(&i.Name, &i.MarkdownSv, &i.MarkdownEn)
	return i, err
}

const upsertMarkdown = `-- name: UpsertMarkdown :one
INSERT INTO markdowns (name, markdown_sv, markdown_en)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE SET markdown_sv = $2, markdown_en = $3
RETURNING name, markdown_sv, markdown_en
`

type UpsertMarkdownParams struct {
	Name       string      `json:"name"`
	MarkdownSv string      `json:"markdown_sv"`
	MarkdownEn pgtype.Text `json:"markdown_en"`
}

func (q *Queries) UpsertMarkdown(ctx context.Context, arg UpsertMarkdownParams) (Markdown, error) {
	row := q.db.QueryRow(ctx, upsertMarkdown, arg.Name, arg.MarkdownSv, arg.MarkdownEn)
	var i Markdown
	err := row.Scan(&i.Name, &i.MarkdownSv, &i.MarkdownEn)
	return i, err
}
