// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: medals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCommitteesWithMedals = `-- name: ListCommitteesWithMedals :many
SELECT id, name_sv, name_en
FROM committees
WHERE short_name IS NULL OR short_name NOT IN ('valb', 'other', 'dchip', 'medalj')
`

type ListCommitteesWithMedalsRow struct {
	ID     pgtype.UUID `json:"id"`
	NameSv string      `json:"name_sv"`
	NameEn pgtype.Text `json:"name_en"`
}

// Committees eligible for a committee medal - excludes the same fixed
// short_name set the old app hardcoded (valb/other/dchip/medalj).
func (q *Queries) ListCommitteesWithMedals(ctx context.Context) ([]ListCommitteesWithMedalsRow, error) {
	rows, err := q.db.Query(ctx, listCommitteesWithMedals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommitteesWithMedalsRow{}
	for rows.Next() {
		var i ListCommitteesWithMedalsRow
		if err := rows.Scan(&i.ID, &i.NameSv, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMandatesForMembersBefore = `-- name: ListMandatesForMembersBefore :many
SELECT mn.member_id, mn.start_date, mn.end_date, p.board_member, p.committee_id
FROM mandates mn
JOIN positions p ON p.id = mn.position_id
WHERE mn.member_id = ANY($1::uuid[])
  AND mn.start_date < $2::date
`

type ListMandatesForMembersBeforeParams struct {
	MemberIds []pgtype.UUID `json:"member_ids"`
	Cutoff    pgtype.Date   `json:"cutoff"`
}

type ListMandatesForMembersBeforeRow struct {
	MemberID    pgtype.UUID `json:"member_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	BoardMember bool        `json:"board_member"`
	CommitteeID pgtype.UUID `json:"committee_id"`
}

// All mandates (not just active-during-the-window ones) for a given member
// set, that started before the cutoff - mirrors the old app's allMandates
// query, which only bounds start_date (no end_date filter) since award
// semesters are computed by intersecting with "after" in Go, not in SQL.
func (q *Queries) ListMandatesForMembersBefore(ctx context.Context, arg ListMandatesForMembersBeforeParams) ([]ListMandatesForMembersBeforeRow, error) {
	rows, err := q.db.Query(ctx, listMandatesForMembersBefore, arg.MemberIds, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMandatesForMembersBeforeRow{}
	for rows.Next() {
		var i ListMandatesForMembersBeforeRow
		if err := rows.Scan(
			&i.MemberID,
			&i.StartDate,
			&i.EndDate,
			&i.BoardMember,
			&i.CommitteeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberIDsWithMandateActiveDuring = `-- name: ListMemberIDsWithMandateActiveDuring :many
SELECT DISTINCT member_id
FROM mandates
WHERE start_date < $1::date AND end_date >= $2::date
`

type ListMemberIDsWithMandateActiveDuringParams struct {
	WindowEnd   pgtype.Date `json:"window_end"`
	WindowStart pgtype.Date `json:"window_start"`
}

// Distinct members who held any mandate active during [start, end) - the
// candidate set medalRecipients scopes its per-member computation to,
// mirroring the old app's mandatesInAfter query exactly.
func (q *Queries) ListMemberIDsWithMandateActiveDuring(ctx context.Context, arg ListMemberIDsWithMandateActiveDuringParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMemberIDsWithMandateActiveDuring, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var member_id pgtype.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberMandatesWithPosition = `-- name: ListMemberMandatesWithPosition :many
SELECT m.start_date, m.end_date, p.board_member, p.committee_id
FROM mandates m
JOIN positions p ON p.id = m.position_id
WHERE m.member_id = $1
`

type ListMemberMandatesWithPositionRow struct {
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	BoardMember bool        `json:"board_member"`
	CommitteeID pgtype.UUID `json:"committee_id"`
}

// Full mandate history for one member, joined to board_member/committee_id
// - everything memberMedals (src/lib/server/medals/medals.ts) needs to
// compute that member's own medal semesters.
func (q *Queries) ListMemberMandatesWithPosition(ctx context.Context, memberID pgtype.UUID) ([]ListMemberMandatesWithPositionRow, error) {
	rows, err := q.db.Query(ctx, listMemberMandatesWithPosition, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberMandatesWithPositionRow{}
	for rows.Next() {
		var i ListMemberMandatesWithPositionRow
		if err := rows.Scan(
			&i.StartDate,
			&i.EndDate,
			&i.BoardMember,
			&i.CommitteeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByIDs = `-- name: ListMembersByIDs :many
SELECT id, student_id, first_name, last_name
FROM members
WHERE id = ANY($1::uuid[])
`

type ListMembersByIDsRow struct {
	ID        pgtype.UUID `json:"id"`
	StudentID pgtype.Text `json:"student_id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
}

func (q *Queries) ListMembersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListMembersByIDsRow, error) {
	rows, err := q.db.Query(ctx, listMembersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByIDsRow{}
	for rows.Next() {
		var i ListMembersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
