// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (student_id, first_name, last_name, email, class_year)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, student_id, first_name, last_name, email, class_year, class_programme
`

type CreateMemberParams struct {
	StudentID pgtype.Text `json:"student_id"`
	FirstName pgtype.Text `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
	Email     pgtype.Text `json:"email"`
	ClassYear pgtype.Int4 `json:"class_year"`
}

type CreateMemberRow struct {
	ID             pgtype.UUID `json:"id"`
	StudentID      pgtype.Text `json:"student_id"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	Email          pgtype.Text `json:"email"`
	ClassYear      pgtype.Int4 `json:"class_year"`
	ClassProgramme pgtype.Text `json:"class_programme"`
}

// Minimal port of src/lib/utils/member.ts's createMember: this backend
// doesn't own subscription_settings or tag subscriptions (nollning-period
// defaults included), so this only creates the bare Member row those
// features would otherwise hang off of - a deliberate gap, not an
// oversight, consistent with nollning being out of scope elsewhere in this
// rewrite (see DESIGN.md).
func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (CreateMemberRow, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.StudentID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ClassYear,
	)
	var i CreateMemberRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ClassYear,
		&i.ClassProgramme,
	)
	return i, err
}

const getAnyMember = `-- name: GetAnyMember :one
SELECT id, student_id FROM members WHERE student_id IS NOT NULL ORDER BY id LIMIT 1
`

type GetAnyMemberRow struct {
	ID        pgtype.UUID `json:"id"`
	StudentID pgtype.Text `json:"student_id"`
}

// Used only to seed the mock auth identity in dev when no specific member
// is configured (see internal/auth, main.go). Arbitrary but deterministic
// enough for local dev: whichever member sorts first by id.
func (q *Queries) GetAnyMember(ctx context.Context) (GetAnyMemberRow, error) {
	row := q.db.QueryRow(ctx, getAnyMember)
	var i GetAnyMemberRow
	err := row.Scan(&i.ID, &i.StudentID)
	return i, err
}

const getMemberByStudentID = `-- name: GetMemberByStudentID :one
SELECT id, student_id, first_name, last_name, email, class_year, class_programme
FROM members
WHERE student_id = $1
`

type GetMemberByStudentIDRow struct {
	ID             pgtype.UUID `json:"id"`
	StudentID      pgtype.Text `json:"student_id"`
	FirstName      pgtype.Text `json:"first_name"`
	LastName       pgtype.Text `json:"last_name"`
	Email          pgtype.Text `json:"email"`
	ClassYear      pgtype.Int4 `json:"class_year"`
	ClassProgramme pgtype.Text `json:"class_programme"`
}

func (q *Queries) GetMemberByStudentID(ctx context.Context, studentID pgtype.Text) (GetMemberByStudentIDRow, error) {
	row := q.db.QueryRow(ctx, getMemberByStudentID, studentID)
	var i GetMemberByStudentIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ClassYear,
		&i.ClassProgramme,
	)
	return i, err
}
