// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BookingRequestStatus string

const (
	BookingRequestStatusACCEPTED BookingRequestStatus = "ACCEPTED"
	BookingRequestStatusDENIED   BookingRequestStatus = "DENIED"
	BookingRequestStatusPENDING  BookingRequestStatus = "PENDING"
)

func (e *BookingRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingRequestStatus(s)
	case string:
		*e = BookingRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingRequestStatus: %T", src)
	}
	return nil
}

type NullBookingRequestStatus struct {
	BookingRequestStatus BookingRequestStatus `json:"BookingRequestStatus"`
	Valid                bool                 `json:"valid"` // Valid is true if BookingRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingRequestStatus), nil
}

type DocumentType string

const (
	DocumentTypePOLICY           DocumentType = "POLICY"
	DocumentTypeGUIDELINE        DocumentType = "GUIDELINE"
	DocumentTypeMEETING          DocumentType = "MEETING"
	DocumentTypeOTHER            DocumentType = "OTHER"
	DocumentTypePLANOFOPERATIONS DocumentType = "PLAN_OF_OPERATIONS"
	DocumentTypeFRAMEWORKBUDGET  DocumentType = "FRAMEWORK_BUDGET"
	DocumentTypeSTRATEGICGOALS   DocumentType = "STRATEGIC_GOALS"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType `json:"document_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type RecurringType string

const (
	RecurringTypeDAILY   RecurringType = "DAILY"
	RecurringTypeWEEKLY  RecurringType = "WEEKLY"
	RecurringTypeMONTHLY RecurringType = "MONTHLY"
	RecurringTypeYEARLY  RecurringType = "YEARLY"
)

func (e *RecurringType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecurringType(s)
	case string:
		*e = RecurringType(s)
	default:
		return fmt.Errorf("unsupported scan type for RecurringType: %T", src)
	}
	return nil
}

type NullRecurringType struct {
	RecurringType RecurringType `json:"recurringType"`
	Valid         bool          `json:"valid"` // Valid is true if RecurringType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecurringType) Scan(value interface{}) error {
	if value == nil {
		ns.RecurringType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecurringType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecurringType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecurringType), nil
}

type TimeSlots string

const (
	TimeSlotsDAYMANAGER TimeSlots = "DAYMANAGER"
	TimeSlotsSHIFT1     TimeSlots = "SHIFT_1"
	TimeSlotsSHIFT2     TimeSlots = "SHIFT_2"
	TimeSlotsSHIFT3     TimeSlots = "SHIFT_3"
)

func (e *TimeSlots) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimeSlots(s)
	case string:
		*e = TimeSlots(s)
	default:
		return fmt.Errorf("unsupported scan type for TimeSlots: %T", src)
	}
	return nil
}

type NullTimeSlots struct {
	TimeSlots TimeSlots `json:"time_slots"`
	Valid     bool      `json:"valid"` // Valid is true if TimeSlots is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimeSlots) Scan(value interface{}) error {
	if value == nil {
		ns.TimeSlots, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimeSlots.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimeSlots) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimeSlots), nil
}

type AdminSetting struct {
	Key       string             `json:"key"`
	Value     pgtype.Text        `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Alert struct {
	ID        pgtype.UUID        `json:"id"`
	Severity  string             `json:"severity"`
	MessageSv string             `json:"message_sv"`
	MessageEn string             `json:"message_en"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RemovedAt pgtype.Timestamptz `json:"removed_at"`
}

type AlertsClosedBy struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type ApiAccessPolicy struct {
	ID        pgtype.UUID        `json:"id"`
	ApiName   string             `json:"api_name"`
	Role      pgtype.Text        `json:"role"`
	StudentID pgtype.Text        `json:"student_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Article struct {
	ID                     pgtype.UUID        `json:"id"`
	HeaderSv               string             `json:"header_sv"`
	HeaderEn               pgtype.Text        `json:"header_en"`
	BodySv                 string             `json:"body_sv"`
	BodyEn                 pgtype.Text        `json:"body_en"`
	ImageUrl               pgtype.Text        `json:"image_url"`
	AuthorID               pgtype.UUID        `json:"author_id"`
	PublishedDatetime      pgtype.Timestamptz `json:"published_datetime"`
	LatestEditDatetime     pgtype.Timestamptz `json:"latest_edit_datetime"`
	Slug                   string             `json:"slug"`
	RemovedAt              pgtype.Timestamptz `json:"removed_at"`
	Status                 pgtype.Text        `json:"status"`
	CreatedDatetime        pgtype.Timestamptz `json:"created_datetime"`
	YoutubeUrl             pgtype.Text        `json:"youtube_url"`
	ImageUrls              []string           `json:"image_urls"`
	NotificationText       pgtype.Text        `json:"notification_text"`
	ScheduledID            pgtype.Text        `json:"scheduled_id"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
	NollningSeasonID       pgtype.UUID        `json:"nollning_season_id"`
}

type ArticleComment struct {
	ID        pgtype.UUID        `json:"id"`
	ArticleID pgtype.UUID        `json:"article_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	Content   pgtype.Text        `json:"content"`
	Published pgtype.Timestamptz `json:"published"`
}

type ArticleLike struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type ArticleRequest struct {
	ID                     pgtype.UUID        `json:"id"`
	ArticleID              pgtype.UUID        `json:"article_id"`
	ApprovedDatetime       pgtype.Timestamptz `json:"approved_datetime"`
	RejectedDatetime       pgtype.Timestamptz `json:"rejected_datetime"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	HandledBy              pgtype.UUID        `json:"handled_by"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	NotificationBodySv     pgtype.Text        `json:"notification_body_sv"`
	NotificationBodyEn     pgtype.Text        `json:"notification_body_en"`
}

type ArticleTag struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type Author struct {
	ID        pgtype.UUID        `json:"id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	MandateID pgtype.UUID        `json:"mandate_id"`
	CustomID  pgtype.UUID        `json:"custom_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Type      pgtype.Text        `json:"type"`
}

type Bookable struct {
	ID         pgtype.UUID `json:"id"`
	NameSv     string      `json:"name_sv"`
	NameEn     pgtype.Text `json:"name_en"`
	IsDisabled bool        `json:"isDisabled"`
	CategoryID pgtype.UUID `json:"category_id"`
	Door       pgtype.Text `json:"door"`
}

type BookableCategory struct {
	ID     pgtype.UUID `json:"id"`
	NameSv string      `json:"name_sv"`
	NameEn pgtype.Text `json:"name_en"`
}

type BookingRequest struct {
	ID       pgtype.UUID          `json:"id"`
	BookerID pgtype.UUID          `json:"booker_id"`
	Start    pgtype.Timestamptz   `json:"start"`
	End      pgtype.Timestamptz   `json:"end"`
	Created  pgtype.Timestamptz   `json:"created"`
	Event    pgtype.Text          `json:"event"`
	Status   BookingRequestStatus `json:"status"`
}

type BookingRequestsBookable struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type CafeShift struct {
	ID       pgtype.UUID      `json:"id"`
	Date     pgtype.Timestamp `json:"date"`
	WorkerId pgtype.UUID      `json:"workerId"`
	TimeSlot TimeSlots        `json:"time_slot"`
}

type CiabattaOfTheWeek struct {
	ID   pgtype.UUID `json:"id"`
	Year int32       `json:"year"`
	Week int32       `json:"week"`
	Name string      `json:"name"`
}

type Committee struct {
	ID                pgtype.UUID `json:"id"`
	NameSv            string      `json:"name_sv"`
	NameEn            pgtype.Text `json:"name_en"`
	ShortName         pgtype.Text `json:"short_name"`
	DescriptionSv     pgtype.Text `json:"description_sv"`
	DescriptionEn     pgtype.Text `json:"description_en"`
	DarkImageUrl      pgtype.Text `json:"dark_image_url"`
	LightImageUrl     pgtype.Text `json:"light_image_url"`
	MonoImageUrl      pgtype.Text `json:"mono_image_url"`
	SymbolUrl         pgtype.Text `json:"symbol_url"`
	BannerUrl         pgtype.Text `json:"banner_url"`
	IsBannerTextLight bool        `json:"is_banner_text_light"`
	PreviewUrl        pgtype.Text `json:"preview_url"`
}

type CustomAuthor struct {
	ID        pgtype.UUID        `json:"id"`
	NameSv    string             `json:"name_sv"`
	NameEn    pgtype.Text        `json:"name_en"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CustomAuthorRole struct {
	ID             pgtype.UUID        `json:"id"`
	CustomAuthorID pgtype.UUID        `json:"custom_author_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Url       string             `json:"url"`
	Type      DocumentType       `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Door struct {
	Name        string      `json:"name"`
	ID          pgtype.Text `json:"id"`
	VerboseName string      `json:"verbose_name"`
}

type DoorAccessPolicy struct {
	ID            pgtype.UUID        `json:"id"`
	DoorName      string             `json:"door_name"`
	Role          pgtype.Text        `json:"role"`
	StudentID     pgtype.Text        `json:"student_id"`
	StartDatetime pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime   pgtype.Timestamptz `json:"end_datetime"`
	IsBan         bool               `json:"is_ban"`
	Information   pgtype.Text        `json:"information"`
}

type Election struct {
	ID          pgtype.UUID        `json:"id"`
	CommitteeID pgtype.UUID        `json:"committee_id"`
	MarkdownSv  string             `json:"markdown_sv"`
	MarkdownEn  pgtype.Text        `json:"markdown_en"`
	Link        string             `json:"link"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type EmailAlias struct {
	ID         pgtype.UUID `json:"id"`
	PositionID string      `json:"position_id"`
	Email      string      `json:"email"`
}

type Event struct {
	ID                 pgtype.UUID        `json:"id"`
	TitleSv            string             `json:"title_sv"`
	TitleEn            pgtype.Text        `json:"title_en"`
	DescriptionSv      string             `json:"description_sv"`
	DescriptionEn      pgtype.Text        `json:"description_en"`
	Link               pgtype.Text        `json:"link"`
	Location           pgtype.Text        `json:"location"`
	Organizer          string             `json:"organizer"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	ShortDescriptionSv pgtype.Text        `json:"short_description_sv"`
	ShortDescriptionEn pgtype.Text        `json:"short_description_en"`
	StartDatetime      pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime        pgtype.Timestamptz `json:"end_datetime"`
	NumberOfUpdates    pgtype.Int4        `json:"number_of_updates"`
	Slug               pgtype.Text        `json:"slug"`
	AlarmActive        pgtype.Bool        `json:"alarm_active"`
	RemovedAt          pgtype.Timestamptz `json:"removed_at"`
	ImageUrl           pgtype.Text        `json:"imageUrl"`
	IsDetatched        bool               `json:"is_detatched"`
	RecurringParentID  pgtype.UUID        `json:"recurring_parent_id"`
	IsCancelled        pgtype.Bool        `json:"is_cancelled"`
	NollningSeasonID   pgtype.UUID        `json:"nollning_season_id"`
}

type EventComment struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	Content   pgtype.Text        `json:"content"`
	Published pgtype.Timestamptz `json:"published"`
}

type EventGoing struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type EventInterested struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type EventTag struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type ExpoToken struct {
	ID        pgtype.UUID `json:"id"`
	MemberID  pgtype.UUID `json:"member_id"`
	ExpoToken string      `json:"expo_token"`
}

type Mandate struct {
	ID          pgtype.UUID `json:"id"`
	MemberID    pgtype.UUID `json:"member_id"`
	PositionID  string      `json:"position_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	PhadderInId pgtype.UUID `json:"phadderInId"`
	LastSynced  pgtype.Date `json:"last_synced"`
}

type Markdown struct {
	Name       string      `json:"name"`
	MarkdownSv string      `json:"markdown_sv"`
	MarkdownEn pgtype.Text `json:"markdown_en"`
}

type Member struct {
	ID               pgtype.UUID `json:"id"`
	StudentID        pgtype.Text `json:"student_id"`
	FirstName        pgtype.Text `json:"first_name"`
	Nickname         pgtype.Text `json:"nickname"`
	LastName         pgtype.Text `json:"last_name"`
	PicturePath      pgtype.Text `json:"picture_path"`
	ClassProgramme   pgtype.Text `json:"class_programme"`
	ClassYear        pgtype.Int4 `json:"class_year"`
	Visible          bool        `json:"visible"`
	FoodPreference   pgtype.Text `json:"food_preference"`
	Bio              pgtype.Text `json:"bio"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
	Email            pgtype.Text `json:"email"`
	NollningGroupID  pgtype.UUID `json:"nollning_group_id"`
	GraduationYear   pgtype.Int4 `json:"graduation_year"`
	Language         pgtype.Text `json:"language"`
}

type MemberTagSubscription struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type NollningSeason struct {
	ID                    pgtype.UUID        `json:"id"`
	Year                  int32              `json:"year"`
	NollaStartAt          pgtype.Timestamptz `json:"nolla_start_at"`
	RevealAt              pgtype.Timestamptz `json:"reveal_at"`
	EndAt                 pgtype.Timestamptz `json:"end_at"`
	OrganizingCommitteeID pgtype.UUID        `json:"organizing_committee_id"`
}

type Notification struct {
	ID           int32              `json:"id"`
	Title        string             `json:"title"`
	Message      string             `json:"message"`
	Type         string             `json:"type"`
	Link         string             `json:"link"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
	MemberID     pgtype.UUID        `json:"member_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	FromAuthorID pgtype.UUID        `json:"from_author_id"`
}

type PhadderGroup struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	SeasonID    pgtype.UUID      `json:"season_id"`
}

type Position struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	CommitteeID   pgtype.UUID `json:"committee_id"`
	Email         pgtype.Text `json:"email"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	EndMonth      int32       `json:"end_month"`
	StartMonth    int32       `json:"start_month"`
}

type RecurringEvent struct {
	ID              pgtype.UUID        `json:"id"`
	SeparationCount int32              `json:"separation_count"`
	RecurringType   RecurringType      `json:"recurring_type"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	StartDatetime   pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime     pgtype.Timestamptz `json:"end_datetime"`
}

type Song struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Lyrics    string             `json:"lyrics"`
	Melody    pgtype.Text        `json:"melody"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Slug      string             `json:"slug"`
	Video     pgtype.Text        `json:"video"`
}

type SubscriptionSetting struct {
	ID               pgtype.UUID `json:"id"`
	MemberID         pgtype.UUID `json:"member_id"`
	Type             string      `json:"type"`
	PushNotification bool        `json:"push_notification"`
}

type Tag struct {
	ID        pgtype.UUID `json:"id"`
	NameSv    string      `json:"name_sv"`
	NameEn    pgtype.Text `json:"name_en"`
	Color     pgtype.Text `json:"color"`
	IsDefault pgtype.Bool `json:"is_default"`
}
