// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RecurringType string

const (
	RecurringTypeDAILY   RecurringType = "DAILY"
	RecurringTypeWEEKLY  RecurringType = "WEEKLY"
	RecurringTypeMONTHLY RecurringType = "MONTHLY"
	RecurringTypeYEARLY  RecurringType = "YEARLY"
)

func (e *RecurringType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecurringType(s)
	case string:
		*e = RecurringType(s)
	default:
		return fmt.Errorf("unsupported scan type for RecurringType: %T", src)
	}
	return nil
}

type NullRecurringType struct {
	RecurringType RecurringType `json:"recurringType"`
	Valid         bool          `json:"valid"` // Valid is true if RecurringType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecurringType) Scan(value interface{}) error {
	if value == nil {
		ns.RecurringType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecurringType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecurringType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecurringType), nil
}

type ApiAccessPolicy struct {
	ID        pgtype.UUID        `json:"id"`
	ApiName   string             `json:"api_name"`
	Role      pgtype.Text        `json:"role"`
	StudentID pgtype.Text        `json:"student_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Article struct {
	ID                     pgtype.UUID        `json:"id"`
	HeaderSv               string             `json:"header_sv"`
	HeaderEn               pgtype.Text        `json:"header_en"`
	BodySv                 string             `json:"body_sv"`
	BodyEn                 pgtype.Text        `json:"body_en"`
	ImageUrl               pgtype.Text        `json:"image_url"`
	AuthorID               pgtype.UUID        `json:"author_id"`
	PublishedDatetime      pgtype.Timestamptz `json:"published_datetime"`
	LatestEditDatetime     pgtype.Timestamptz `json:"latest_edit_datetime"`
	Slug                   string             `json:"slug"`
	RemovedAt              pgtype.Timestamptz `json:"removed_at"`
	Status                 pgtype.Text        `json:"status"`
	CreatedDatetime        pgtype.Timestamptz `json:"created_datetime"`
	YoutubeUrl             pgtype.Text        `json:"youtube_url"`
	ImageUrls              []string           `json:"image_urls"`
	NotificationText       pgtype.Text        `json:"notification_text"`
	ScheduledID            pgtype.Text        `json:"scheduled_id"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	CommitteeID            pgtype.UUID        `json:"committee_id"`
}

type ArticleComment struct {
	ID        pgtype.UUID        `json:"id"`
	ArticleID pgtype.UUID        `json:"article_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	Content   pgtype.Text        `json:"content"`
	Published pgtype.Timestamptz `json:"published"`
}

type ArticleLike struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type ArticleRequest struct {
	ID                     pgtype.UUID        `json:"id"`
	ArticleID              pgtype.UUID        `json:"article_id"`
	ApprovedDatetime       pgtype.Timestamptz `json:"approved_datetime"`
	RejectedDatetime       pgtype.Timestamptz `json:"rejected_datetime"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
	HandledBy              pgtype.UUID        `json:"handled_by"`
	ShouldSendNotification pgtype.Bool        `json:"should_send_notification"`
	NotificationBodySv     pgtype.Text        `json:"notification_body_sv"`
	NotificationBodyEn     pgtype.Text        `json:"notification_body_en"`
}

type ArticleTag struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type Author struct {
	ID        pgtype.UUID        `json:"id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	MandateID pgtype.UUID        `json:"mandate_id"`
	CustomID  pgtype.UUID        `json:"custom_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Type      pgtype.Text        `json:"type"`
}

type Committee struct {
	ID                pgtype.UUID `json:"id"`
	NameSv            string      `json:"name_sv"`
	NameEn            pgtype.Text `json:"name_en"`
	ShortName         pgtype.Text `json:"short_name"`
	DescriptionSv     pgtype.Text `json:"description_sv"`
	DescriptionEn     pgtype.Text `json:"description_en"`
	DarkImageUrl      pgtype.Text `json:"dark_image_url"`
	LightImageUrl     pgtype.Text `json:"light_image_url"`
	MonoImageUrl      pgtype.Text `json:"mono_image_url"`
	SymbolUrl         pgtype.Text `json:"symbol_url"`
	BannerUrl         pgtype.Text `json:"banner_url"`
	IsBannerTextLight bool        `json:"is_banner_text_light"`
	PreviewUrl        pgtype.Text `json:"preview_url"`
}

type CustomAuthor struct {
	ID        pgtype.UUID        `json:"id"`
	NameSv    string             `json:"name_sv"`
	NameEn    pgtype.Text        `json:"name_en"`
	ImageUrl  pgtype.Text        `json:"image_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CustomAuthorRole struct {
	ID             pgtype.UUID        `json:"id"`
	CustomAuthorID pgtype.UUID        `json:"custom_author_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID                 pgtype.UUID        `json:"id"`
	TitleSv            string             `json:"title_sv"`
	TitleEn            pgtype.Text        `json:"title_en"`
	DescriptionSv      string             `json:"description_sv"`
	DescriptionEn      pgtype.Text        `json:"description_en"`
	Link               pgtype.Text        `json:"link"`
	Location           pgtype.Text        `json:"location"`
	Organizer          string             `json:"organizer"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	ShortDescriptionSv pgtype.Text        `json:"short_description_sv"`
	ShortDescriptionEn pgtype.Text        `json:"short_description_en"`
	StartDatetime      pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime        pgtype.Timestamptz `json:"end_datetime"`
	NumberOfUpdates    pgtype.Int4        `json:"number_of_updates"`
	Slug               pgtype.Text        `json:"slug"`
	AlarmActive        pgtype.Bool        `json:"alarm_active"`
	RemovedAt          pgtype.Timestamptz `json:"removed_at"`
	ImageUrl           pgtype.Text        `json:"imageUrl"`
	IsDetatched        bool               `json:"is_detatched"`
	RecurringParentID  pgtype.UUID        `json:"recurring_parent_id"`
	IsCancelled        pgtype.Bool        `json:"is_cancelled"`
}

type EventComment struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	Content   pgtype.Text        `json:"content"`
	Published pgtype.Timestamptz `json:"published"`
}

type EventGoing struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type EventInterested struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type EventTag struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

type Mandate struct {
	ID          pgtype.UUID `json:"id"`
	MemberID    pgtype.UUID `json:"member_id"`
	PositionID  string      `json:"position_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	PhadderInId pgtype.UUID `json:"phadderInId"`
	LastSynced  pgtype.Date `json:"last_synced"`
}

type Member struct {
	ID               pgtype.UUID `json:"id"`
	StudentID        pgtype.Text `json:"student_id"`
	FirstName        pgtype.Text `json:"first_name"`
	Nickname         pgtype.Text `json:"nickname"`
	LastName         pgtype.Text `json:"last_name"`
	PicturePath      pgtype.Text `json:"picture_path"`
	ClassProgramme   pgtype.Text `json:"class_programme"`
	ClassYear        pgtype.Int4 `json:"class_year"`
	Visible          bool        `json:"visible"`
	FoodPreference   pgtype.Text `json:"food_preference"`
	Bio              pgtype.Text `json:"bio"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
	Email            pgtype.Text `json:"email"`
	NollningGroupID  pgtype.UUID `json:"nollning_group_id"`
	GraduationYear   pgtype.Int4 `json:"graduation_year"`
	Language         pgtype.Text `json:"language"`
}

type PhadderGroup struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	Year        int32            `json:"year"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

type Position struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	CommitteeID   pgtype.UUID `json:"committee_id"`
	Email         pgtype.Text `json:"email"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	EndMonth      int32       `json:"end_month"`
	StartMonth    int32       `json:"start_month"`
}

type RecurringEvent struct {
	ID              pgtype.UUID        `json:"id"`
	SeparationCount int32              `json:"separation_count"`
	RecurringType   RecurringType      `json:"recurring_type"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	StartDatetime   pgtype.Timestamptz `json:"start_datetime"`
	EndDatetime     pgtype.Timestamptz `json:"end_datetime"`
}

type Tag struct {
	ID        pgtype.UUID `json:"id"`
	NameSv    string      `json:"name_sv"`
	NameEn    pgtype.Text `json:"name_en"`
	Color     pgtype.Text `json:"color"`
	IsDefault pgtype.Bool `json:"is_default"`
}
