// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nollning.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMandatePhadderGroupForMember = `-- name: ClearMandatePhadderGroupForMember :exec
UPDATE mandates
SET "phadderInId" = NULL
WHERE member_id = $1
  AND "phadderInId" = $2
  AND position_id IN ('dsek.noll.phadder', 'dsek.noll.uppdrag')
`

type ClearMandatePhadderGroupForMemberParams struct {
	MemberID    pgtype.UUID `json:"member_id"`
	PhadderInId pgtype.UUID `json:"phadderInId"`
}

// Mirrors the old removePhadder action: clears every one of this member's
// mandates currently tagged to this group (not just the single "active"
// one FindActivePhadderMandate would pick), matching the old code's
// `mandates.map(...)` bulk-disconnect over every matching mandate.
func (q *Queries) ClearMandatePhadderGroupForMember(ctx context.Context, arg ClearMandatePhadderGroupForMemberParams) error {
	_, err := q.db.Exec(ctx, clearMandatePhadderGroupForMember, arg.MemberID, arg.PhadderInId)
	return err
}

const clearMemberPhadderGroup = `-- name: ClearMemberPhadderGroup :exec
UPDATE members SET nollning_group_id = NULL WHERE id = $1 AND nollning_group_id = $2
`

type ClearMemberPhadderGroupParams struct {
	ID              pgtype.UUID `json:"id"`
	NollningGroupID pgtype.UUID `json:"nollning_group_id"`
}

// Only clears if the member is currently in exactly this group - mirrors
// the old Prisma `disconnect`, which is a no-op unless the relation
// actually exists.
func (q *Queries) ClearMemberPhadderGroup(ctx context.Context, arg ClearMemberPhadderGroupParams) error {
	_, err := q.db.Exec(ctx, clearMemberPhadderGroup, arg.ID, arg.NollningGroupID)
	return err
}

const createPhadderGroup = `-- name: CreatePhadderGroup :one
INSERT INTO phadder_groups (name, description, image_url, season_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, image_url, "createdAt", season_id
`

type CreatePhadderGroupParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ImageUrl    pgtype.Text `json:"image_url"`
	SeasonID    pgtype.UUID `json:"season_id"`
}

func (q *Queries) CreatePhadderGroup(ctx context.Context, arg CreatePhadderGroupParams) (PhadderGroup, error) {
	row := q.db.QueryRow(ctx, createPhadderGroup,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.SeasonID,
	)
	var i PhadderGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.SeasonID,
	)
	return i, err
}

const createSeason = `-- name: CreateSeason :one
INSERT INTO nollning_seasons (year, nolla_start_at, reveal_at, end_at, organizing_committee_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, year, nolla_start_at, reveal_at, end_at, organizing_committee_id
`

type CreateSeasonParams struct {
	Year                  int32              `json:"year"`
	NollaStartAt          pgtype.Timestamptz `json:"nolla_start_at"`
	RevealAt              pgtype.Timestamptz `json:"reveal_at"`
	EndAt                 pgtype.Timestamptz `json:"end_at"`
	OrganizingCommitteeID pgtype.UUID        `json:"organizing_committee_id"`
}

func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (NollningSeason, error) {
	row := q.db.QueryRow(ctx, createSeason,
		arg.Year,
		arg.NollaStartAt,
		arg.RevealAt,
		arg.EndAt,
		arg.OrganizingCommitteeID,
	)
	var i NollningSeason
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.NollaStartAt,
		&i.RevealAt,
		&i.EndAt,
		&i.OrganizingCommitteeID,
	)
	return i, err
}

const deletePhadderGroup = `-- name: DeletePhadderGroup :exec
DELETE FROM phadder_groups WHERE id = $1
`

func (q *Queries) DeletePhadderGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePhadderGroup, id)
	return err
}

const findActivePhadderMandate = `-- name: FindActivePhadderMandate :one
SELECT id, position_id, start_date, end_date
FROM mandates
WHERE member_id = $1
  AND position_id IN ('dsek.noll.phadder', 'dsek.noll.uppdrag')
  AND start_date <= $2
  AND end_date >= $3
ORDER BY position_id ASC, start_date ASC
LIMIT 1
`

type FindActivePhadderMandateParams struct {
	MemberID  pgtype.UUID `json:"member_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type FindActivePhadderMandateRow struct {
	ID         pgtype.UUID `json:"id"`
	PositionID string      `json:"position_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

// The member's phadder/uppdrag mandate overlapping the group's season
// window, ordered like the old getPhadderMandates (position id asc, i.e.
// "phadder" before "uppdrag", then start_date asc) so the first row is the
// same one the old TS picked with `mandates?.[0]`.
func (q *Queries) FindActivePhadderMandate(ctx context.Context, arg FindActivePhadderMandateParams) (FindActivePhadderMandateRow, error) {
	row := q.db.QueryRow(ctx, findActivePhadderMandate, arg.MemberID, arg.StartDate, arg.EndDate)
	var i FindActivePhadderMandateRow
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getCurrentSeason = `-- name: GetCurrentSeason :one
SELECT id, year, nolla_start_at, reveal_at, end_at, organizing_committee_id
FROM nollning_seasons
WHERE nolla_start_at <= now() AND now() <= end_at
ORDER BY nolla_start_at DESC
LIMIT 1
`

// The season whose window covers right now, if any - internal/nollning
// treats "at most one season active at a time" as an invariant (not
// enforced at the DB level, since overlapping seasons would be an admin
// data error, not a normal state).
func (q *Queries) GetCurrentSeason(ctx context.Context) (NollningSeason, error) {
	row := q.db.QueryRow(ctx, getCurrentSeason)
	var i NollningSeason
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.NollaStartAt,
		&i.RevealAt,
		&i.EndAt,
		&i.OrganizingCommitteeID,
	)
	return i, err
}

const getMemberNollaGroupID = `-- name: GetMemberNollaGroupID :one
SELECT nollning_group_id FROM members WHERE id = $1
`

// Backs PhadderRoleFor's "nolla" branch.
func (q *Queries) GetMemberNollaGroupID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMemberNollaGroupID, id)
	var nollning_group_id pgtype.UUID
	err := row.Scan(&nollning_group_id)
	return nollning_group_id, err
}

const getMemberPhadderGroupID = `-- name: GetMemberPhadderGroupID :one
SELECT "phadderInId"
FROM mandates
WHERE member_id = $1
  AND position_id IN ('dsek.noll.phadder', 'dsek.noll.uppdrag')
  AND "phadderInId" IS NOT NULL
ORDER BY position_id ASC, start_date ASC
LIMIT 1
`

// Backs PhadderRoleFor's "phadder" branch: which group (if any) this
// member holds an active phadder/uppdrag mandate pointed at.
func (q *Queries) GetMemberPhadderGroupID(ctx context.Context, memberID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMemberPhadderGroupID, memberID)
	var phadderInId pgtype.UUID
	err := row.Scan(&phadderInId)
	return phadderInId, err
}

const getPhadderGroup = `-- name: GetPhadderGroup :one
SELECT id, name, description, image_url, "createdAt", season_id
FROM phadder_groups
WHERE id = $1
`

func (q *Queries) GetPhadderGroup(ctx context.Context, id pgtype.UUID) (PhadderGroup, error) {
	row := q.db.QueryRow(ctx, getPhadderGroup, id)
	var i PhadderGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.SeasonID,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT id, year, nolla_start_at, reveal_at, end_at, organizing_committee_id
FROM nollning_seasons
WHERE id = $1
`

func (q *Queries) GetSeason(ctx context.Context, id pgtype.UUID) (NollningSeason, error) {
	row := q.db.QueryRow(ctx, getSeason, id)
	var i NollningSeason
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.NollaStartAt,
		&i.RevealAt,
		&i.EndAt,
		&i.OrganizingCommitteeID,
	)
	return i, err
}

const isMemberActiveOnCommittee = `-- name: IsMemberActiveOnCommittee :one
SELECT EXISTS (
    SELECT 1
    FROM mandates m
    JOIN positions p ON p.id = m.position_id
    WHERE m.member_id = $1
      AND p.committee_id = $2
      AND m.start_date <= CURRENT_DATE
      AND m.end_date >= CURRENT_DATE
)
`

type IsMemberActiveOnCommitteeParams struct {
	MemberID    pgtype.UUID `json:"member_id"`
	CommitteeID pgtype.UUID `json:"committee_id"`
}

// Backs IsStaben: does memberID hold a mandate, active today, on a position
// belonging to committeeID.
func (q *Queries) IsMemberActiveOnCommittee(ctx context.Context, arg IsMemberActiveOnCommitteeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMemberActiveOnCommittee, arg.MemberID, arg.CommitteeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listNollorForGroup = `-- name: ListNollorForGroup :many
SELECT id, student_id, first_name, nickname, last_name, picture_path
FROM members
WHERE nollning_group_id = $1
ORDER BY last_name, first_name
`

type ListNollorForGroupRow struct {
	ID          pgtype.UUID `json:"id"`
	StudentID   pgtype.Text `json:"student_id"`
	FirstName   pgtype.Text `json:"first_name"`
	Nickname    pgtype.Text `json:"nickname"`
	LastName    pgtype.Text `json:"last_name"`
	PicturePath pgtype.Text `json:"picture_path"`
}

func (q *Queries) ListNollorForGroup(ctx context.Context, nollningGroupID pgtype.UUID) ([]ListNollorForGroupRow, error) {
	rows, err := q.db.Query(ctx, listNollorForGroup, nollningGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNollorForGroupRow{}
	for rows.Next() {
		var i ListNollorForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FirstName,
			&i.Nickname,
			&i.LastName,
			&i.PicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhadderGroups = `-- name: ListPhadderGroups :many
SELECT g.id, g.name, g.description, g.image_url, g."createdAt", g.season_id,
       count(DISTINCT nolla.id) AS nolla_count,
       count(DISTINCT phadder_mandate.id) AS phadder_count
FROM phadder_groups g
LEFT JOIN members nolla ON nolla.nollning_group_id = g.id
LEFT JOIN mandates phadder_mandate ON phadder_mandate."phadderInId" = g.id
WHERE $1::uuid IS NULL OR g.season_id = $1::uuid
GROUP BY g.id
ORDER BY g."createdAt"
`

type ListPhadderGroupsRow struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Description  pgtype.Text      `json:"description"`
	ImageUrl     pgtype.Text      `json:"image_url"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	SeasonID     pgtype.UUID      `json:"season_id"`
	NollaCount   int64            `json:"nolla_count"`
	PhadderCount int64            `json:"phadder_count"`
}

// Nolla/phadder counts alongside each group, mirroring
// ListCommitteesWithCounts' count-subquery pattern.
func (q *Queries) ListPhadderGroups(ctx context.Context, seasonID pgtype.UUID) ([]ListPhadderGroupsRow, error) {
	rows, err := q.db.Query(ctx, listPhadderGroups, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhadderGroupsRow{}
	for rows.Next() {
		var i ListPhadderGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.SeasonID,
			&i.NollaCount,
			&i.PhadderCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhaddrarForGroup = `-- name: ListPhaddrarForGroup :many
SELECT DISTINCT mem.id, mem.student_id, mem.first_name, mem.nickname, mem.last_name, mem.picture_path
FROM mandates m
JOIN members mem ON mem.id = m.member_id
WHERE m."phadderInId" = $1
ORDER BY mem.last_name, mem.first_name
`

type ListPhaddrarForGroupRow struct {
	ID          pgtype.UUID `json:"id"`
	StudentID   pgtype.Text `json:"student_id"`
	FirstName   pgtype.Text `json:"first_name"`
	Nickname    pgtype.Text `json:"nickname"`
	LastName    pgtype.Text `json:"last_name"`
	PicturePath pgtype.Text `json:"picture_path"`
}

// Distinct members holding a mandate tagged to this group (a member can in
// principle hold more than one such mandate - see FindActivePhadderMandate).
func (q *Queries) ListPhaddrarForGroup(ctx context.Context, phadderinid pgtype.UUID) ([]ListPhaddrarForGroupRow, error) {
	rows, err := q.db.Query(ctx, listPhaddrarForGroup, phadderinid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPhaddrarForGroupRow{}
	for rows.Next() {
		var i ListPhaddrarForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FirstName,
			&i.Nickname,
			&i.LastName,
			&i.PicturePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, year, nolla_start_at, reveal_at, end_at, organizing_committee_id
FROM nollning_seasons
ORDER BY year DESC
`

func (q *Queries) ListSeasons(ctx context.Context) ([]NollningSeason, error) {
	rows, err := q.db.Query(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NollningSeason{}
	for rows.Next() {
		var i NollningSeason
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.NollaStartAt,
			&i.RevealAt,
			&i.EndAt,
			&i.OrganizingCommitteeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMandatePhadderGroup = `-- name: SetMandatePhadderGroup :exec
UPDATE mandates SET "phadderInId" = $2 WHERE id = $1
`

type SetMandatePhadderGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	PhadderInId pgtype.UUID `json:"phadderInId"`
}

func (q *Queries) SetMandatePhadderGroup(ctx context.Context, arg SetMandatePhadderGroupParams) error {
	_, err := q.db.Exec(ctx, setMandatePhadderGroup, arg.ID, arg.PhadderInId)
	return err
}

const setMemberPhadderGroup = `-- name: SetMemberPhadderGroup :exec
UPDATE members SET nollning_group_id = $2 WHERE id = $1
`

type SetMemberPhadderGroupParams struct {
	ID              pgtype.UUID `json:"id"`
	NollningGroupID pgtype.UUID `json:"nollning_group_id"`
}

func (q *Queries) SetMemberPhadderGroup(ctx context.Context, arg SetMemberPhadderGroupParams) error {
	_, err := q.db.Exec(ctx, setMemberPhadderGroup, arg.ID, arg.NollningGroupID)
	return err
}

const updatePhadderGroup = `-- name: UpdatePhadderGroup :one
UPDATE phadder_groups
SET name = $2, description = $3, image_url = $4, season_id = $5
WHERE id = $1
RETURNING id, name, description, image_url, "createdAt", season_id
`

type UpdatePhadderGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ImageUrl    pgtype.Text `json:"image_url"`
	SeasonID    pgtype.UUID `json:"season_id"`
}

func (q *Queries) UpdatePhadderGroup(ctx context.Context, arg UpdatePhadderGroupParams) (PhadderGroup, error) {
	row := q.db.QueryRow(ctx, updatePhadderGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.SeasonID,
	)
	var i PhadderGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.SeasonID,
	)
	return i, err
}

const updateSeason = `-- name: UpdateSeason :one
UPDATE nollning_seasons
SET year = $2, nolla_start_at = $3, reveal_at = $4, end_at = $5, organizing_committee_id = $6
WHERE id = $1
RETURNING id, year, nolla_start_at, reveal_at, end_at, organizing_committee_id
`

type UpdateSeasonParams struct {
	ID                    pgtype.UUID        `json:"id"`
	Year                  int32              `json:"year"`
	NollaStartAt          pgtype.Timestamptz `json:"nolla_start_at"`
	RevealAt              pgtype.Timestamptz `json:"reveal_at"`
	EndAt                 pgtype.Timestamptz `json:"end_at"`
	OrganizingCommitteeID pgtype.UUID        `json:"organizing_committee_id"`
}

func (q *Queries) UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (NollningSeason, error) {
	row := q.db.QueryRow(ctx, updateSeason,
		arg.ID,
		arg.Year,
		arg.NollaStartAt,
		arg.RevealAt,
		arg.EndAt,
		arg.OrganizingCommitteeID,
	)
	var i NollningSeason
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.NollaStartAt,
		&i.RevealAt,
		&i.EndAt,
		&i.OrganizingCommitteeID,
	)
	return i, err
}
