// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE member_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, memberID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, memberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotifications = `-- name: CreateNotifications :exec
INSERT INTO notifications (title, message, type, link, member_id, from_author_id)
SELECT $1::text, $2::text, $3::text,
       $4::text, unnest($5::uuid[]),
       $6::uuid
`

type CreateNotificationsParams struct {
	Title        string        `json:"title"`
	Message      string        `json:"message"`
	Type         string        `json:"type"`
	Link         string        `json:"link"`
	MemberIds    []pgtype.UUID `json:"member_ids"`
	FromAuthorID pgtype.UUID   `json:"from_author_id"`
}

// title/message/type/link/from_author_id are constant across one Send call
// - only member_id varies per recipient - same "constant column + unnest"
// shape as AddArticleTags.
func (q *Queries) CreateNotifications(ctx context.Context, arg CreateNotificationsParams) error {
	_, err := q.db.Exec(ctx, createNotifications,
		arg.Title,
		arg.Message,
		arg.Type,
		arg.Link,
		arg.MemberIds,
		arg.FromAuthorID,
	)
	return err
}

const deleteNotifications = `-- name: DeleteNotifications :exec
DELETE FROM notifications
WHERE member_id = $1
  AND ($2::int IS NULL OR id = $2)
  AND ($3::int[] IS NULL OR id = ANY($3::int[]))
`

type DeleteNotificationsParams struct {
	MemberID pgtype.UUID `json:"member_id"`
	ID       pgtype.Int4 `json:"id"`
	Ids      []int32     `json:"ids"`
}

func (q *Queries) DeleteNotifications(ctx context.Context, arg DeleteNotificationsParams) error {
	_, err := q.db.Exec(ctx, deleteNotifications, arg.MemberID, arg.ID, arg.Ids)
	return err
}

const getAdminSettings = `-- name: GetAdminSettings :many
SELECT key, value FROM admin_settings WHERE key = ANY($1::text[])
`

type GetAdminSettingsRow struct {
	Key   string      `json:"key"`
	Value pgtype.Text `json:"value"`
}

func (q *Queries) GetAdminSettings(ctx context.Context, keys []string) ([]GetAdminSettingsRow, error) {
	rows, err := q.db.Query(ctx, getAdminSettings, keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdminSettingsRow{}
	for rows.Next() {
		var i GetAdminSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorForNotification = `-- name: GetAuthorForNotification :one
SELECT a.id, m.first_name, m.nickname, m.last_name, m.picture_path,
       p.name_sv AS position_name_sv, p.name_en AS position_name_en
FROM authors a
JOIN members m ON m.id = a.member_id
LEFT JOIN mandates ma ON ma.id = a.mandate_id
LEFT JOIN positions p ON p.id = ma.position_id
WHERE a.id = $1
`

type GetAuthorForNotificationRow struct {
	ID             pgtype.UUID `json:"id"`
	FirstName      pgtype.Text `json:"first_name"`
	Nickname       pgtype.Text `json:"nickname"`
	LastName       pgtype.Text `json:"last_name"`
	PicturePath    pgtype.Text `json:"picture_path"`
	PositionNameSv pgtype.Text `json:"position_name_sv"`
	PositionNameEn pgtype.Text `json:"position_name_en"`
}

// Resolves the display identity of a notification's sender: the plain
// member fields, plus (if the author acted via a mandate) that mandate's
// position name - mirrors getAuthorName's "Mandate" branch. Custom-author
// bylines never send notifications in practice (no call site does), so
// that branch isn't modeled here.
func (q *Queries) GetAuthorForNotification(ctx context.Context, id pgtype.UUID) (GetAuthorForNotificationRow, error) {
	row := q.db.QueryRow(ctx, getAuthorForNotification, id)
	var i GetAuthorForNotificationRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.Nickname,
		&i.LastName,
		&i.PicturePath,
		&i.PositionNameSv,
		&i.PositionNameEn,
	)
	return i, err
}

const getMemberNameForNotification = `-- name: GetMemberNameForNotification :one
SELECT first_name, nickname, last_name FROM members WHERE id = $1
`

type GetMemberNameForNotificationRow struct {
	FirstName pgtype.Text `json:"first_name"`
	Nickname  pgtype.Text `json:"nickname"`
	LastName  pgtype.Text `json:"last_name"`
}

// Resolves a member's display name for message text the real Notifier
// synthesizes itself (e.g. "X har gillat din nyhet") - mirrors getFullName's
// inputs exactly (fullName in service.go is the Go port of getFullName).
func (q *Queries) GetMemberNameForNotification(ctx context.Context, id pgtype.UUID) (GetMemberNameForNotificationRow, error) {
	row := q.db.QueryRow(ctx, getMemberNameForNotification, id)
	var i GetMemberNameForNotificationRow
	err := row.Scan(&i.FirstName, &i.Nickname, &i.LastName)
	return i, err
}

const getSubscribedTagIDsForMember = `-- name: GetSubscribedTagIDsForMember :many
SELECT "B" FROM _member_tag_subscriptions WHERE "A" = $1
`

func (q *Queries) GetSubscribedTagIDsForMember(ctx context.Context, a pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getSubscribedTagIDsForMember, a)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var B pgtype.UUID
		if err := rows.Scan(&B); err != nil {
			return nil, err
		}
		items = append(items, B)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionSettingsForMember = `-- name: GetSubscriptionSettingsForMember :many
SELECT id, member_id, type, push_notification FROM subscription_settings WHERE member_id = $1
`

func (q *Queries) GetSubscriptionSettingsForMember(ctx context.Context, memberID pgtype.UUID) ([]SubscriptionSetting, error) {
	rows, err := q.db.Query(ctx, getSubscriptionSettingsForMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionSetting{}
	for rows.Next() {
		var i SubscriptionSetting
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Type,
			&i.PushNotification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSubscribedTag = `-- name: InsertSubscribedTag :exec
INSERT INTO _member_tag_subscriptions ("A", "B") VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertSubscribedTagParams struct {
	A pgtype.UUID `json:"A"`
	B pgtype.UUID `json:"B"`
}

func (q *Queries) InsertSubscribedTag(ctx context.Context, arg InsertSubscribedTagParams) error {
	_, err := q.db.Exec(ctx, insertSubscribedTag, arg.A, arg.B)
	return err
}

const insertSubscriptionSetting = `-- name: InsertSubscriptionSetting :exec
INSERT INTO subscription_settings (member_id, type, push_notification) VALUES ($1, $2, $3)
`

type InsertSubscriptionSettingParams struct {
	MemberID         pgtype.UUID `json:"member_id"`
	Type             string      `json:"type"`
	PushNotification bool        `json:"push_notification"`
}

func (q *Queries) InsertSubscriptionSetting(ctx context.Context, arg InsertSubscriptionSettingParams) error {
	_, err := q.db.Exec(ctx, insertSubscriptionSetting, arg.MemberID, arg.Type, arg.PushNotification)
	return err
}

const listAllMemberIDs = `-- name: ListAllMemberIDs :many
SELECT id FROM members
WHERE ($1::uuid[] IS NULL OR id = ANY($1::uuid[]))
  AND ($2::uuid IS NULL OR id != $2::uuid)
`

type ListAllMemberIDsParams struct {
	CandidateIds    []pgtype.UUID `json:"candidate_ids"`
	ExcludeMemberID pgtype.UUID   `json:"exclude_member_id"`
}

// Every member id - used for the ALWAYS_ON settingType bucket, which
// (per SUBSCRIPTION_SETTINGS_MAP) has no subscription_settings row
// requirement at all.
func (q *Queries) ListAllMemberIDs(ctx context.Context, arg ListAllMemberIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAllMemberIDs, arg.CandidateIds, arg.ExcludeMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefaultTagIDs = `-- name: ListDefaultTagIDs :many
SELECT id FROM tags WHERE is_default = true
`

func (q *Queries) ListDefaultTagIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listDefaultTagIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpoTokensWithUnreadCount = `-- name: ListExpoTokensWithUnreadCount :many
SELECT et.expo_token,
       (SELECT count(*) FROM notifications n WHERE n.member_id = et.member_id AND n.read_at IS NULL) AS unread_count
FROM expo_tokens et
WHERE et.member_id = ANY($1::uuid[])
`

type ListExpoTokensWithUnreadCountRow struct {
	ExpoToken   string `json:"expo_token"`
	UnreadCount int64  `json:"unread_count"`
}

func (q *Queries) ListExpoTokensWithUnreadCount(ctx context.Context, memberIds []pgtype.UUID) ([]ListExpoTokensWithUnreadCountRow, error) {
	rows, err := q.db.Query(ctx, listExpoTokensWithUnreadCount, memberIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpoTokensWithUnreadCountRow{}
	for rows.Next() {
		var i ListExpoTokensWithUnreadCountRow
		if err := rows.Scan(&i.ExpoToken, &i.UnreadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersSubscribedToAnyTag = `-- name: ListMembersSubscribedToAnyTag :many
SELECT DISTINCT "A" AS member_id FROM _member_tag_subscriptions WHERE "B" = ANY($1::uuid[])
`

func (q *Queries) ListMembersSubscribedToAnyTag(ctx context.Context, tagIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMembersSubscribedToAnyTag, tagIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var member_id pgtype.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersWithSubscriptionSetting = `-- name: ListMembersWithSubscriptionSetting :many
SELECT DISTINCT m.id
FROM members m
JOIN subscription_settings ss ON ss.member_id = m.id AND ss.type = $1
WHERE ($2::uuid[] IS NULL OR m.id = ANY($2::uuid[]))
  AND ($3::uuid IS NULL OR m.id != $3::uuid)
  AND (
    $4::bool
    OR NOT EXISTS (
      SELECT 1 FROM notifications n
      WHERE n.member_id = m.id AND n.type = $5
        AND n.link = $6
        AND n.from_author_id IS NOT DISTINCT FROM $7::uuid
    )
  )
`

type ListMembersWithSubscriptionSettingParams struct {
	SettingType     string        `json:"setting_type"`
	CandidateIds    []pgtype.UUID `json:"candidate_ids"`
	ExcludeMemberID pgtype.UUID   `json:"exclude_member_id"`
	AllowDuplicates bool          `json:"allow_duplicates"`
	NotifType       string        `json:"notif_type"`
	Link            string        `json:"link"`
	FromAuthorID    pgtype.UUID   `json:"from_author_id"`
}

// Members subscribed to settingType, optionally narrowed to a specific
// candidate id list (mirrors sendNotification's memberIds intersection).
// Excludes fromMemberID (the sender) and any member already notified about
// this exact (type, link, fromAuthorId) unless allowDuplicates.
func (q *Queries) ListMembersWithSubscriptionSetting(ctx context.Context, arg ListMembersWithSubscriptionSettingParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMembersWithSubscriptionSetting,
		arg.SettingType,
		arg.CandidateIds,
		arg.ExcludeMemberID,
		arg.AllowDuplicates,
		arg.NotifType,
		arg.Link,
		arg.FromAuthorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNollaNotificationsForMember = `-- name: ListNollaNotificationsForMember :many
SELECT id, title, message, type, link, read_at, member_id, created_at,
       updated_at, from_author_id
FROM notifications
WHERE member_id = $1
  AND created_at > $2
  AND (type = 'NEW_ARTICLE' OR link LIKE '/nollning%')
ORDER BY created_at DESC
`

type ListNollaNotificationsForMemberParams struct {
	MemberID pgtype.UUID        `json:"member_id"`
	Since    pgtype.Timestamptz `json:"since"`
}

func (q *Queries) ListNollaNotificationsForMember(ctx context.Context, arg ListNollaNotificationsForMemberParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNollaNotificationsForMember, arg.MemberID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Link,
			&i.ReadAt,
			&i.MemberID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromAuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNollningTagIDs = `-- name: ListNollningTagIDs :many
SELECT id FROM tags WHERE name_sv LIKE '[NOLLNING]%'
`

func (q *Queries) ListNollningTagIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listNollningTagIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForMember = `-- name: ListNotificationsForMember :many
SELECT id, title, message, type, link, read_at, member_id, created_at,
       updated_at, from_author_id
FROM notifications
WHERE member_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNotificationsForMember(ctx context.Context, memberID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Link,
			&i.ReadAt,
			&i.MemberID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromAuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushEnabledMemberIDs = `-- name: ListPushEnabledMemberIDs :many
SELECT member_id FROM subscription_settings
WHERE type = $1 AND push_notification = true
  AND member_id = ANY($2::uuid[])
`

type ListPushEnabledMemberIDsParams struct {
	SettingType string        `json:"setting_type"`
	MemberIds   []pgtype.UUID `json:"member_ids"`
}

func (q *Queries) ListPushEnabledMemberIDs(ctx context.Context, arg ListPushEnabledMemberIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPushEnabledMemberIDs, arg.SettingType, arg.MemberIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var member_id pgtype.UUID
		if err := rows.Scan(&member_id); err != nil {
			return nil, err
		}
		items = append(items, member_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByIDs = `-- name: ListTagsByIDs :many
SELECT id, name_sv, name_en, color FROM tags WHERE id = ANY($1::uuid[])
`

type ListTagsByIDsRow struct {
	ID     pgtype.UUID `json:"id"`
	NameSv string      `json:"name_sv"`
	NameEn pgtype.Text `json:"name_en"`
	Color  pgtype.Text `json:"color"`
}

// Used by the Discord webhook to check for a NOLLNING-prefixed tag and pick
// the embed's color/footer from the article's first tag.
func (q *Queries) ListTagsByIDs(ctx context.Context, ids []pgtype.UUID) ([]ListTagsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listTagsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsByIDsRow{}
	for rows.Next() {
		var i ListTagsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE member_id = $1 AND read_at IS NULL
  AND ($2::int IS NULL OR id = $2)
  AND ($3::int[] IS NULL OR id = ANY($3::int[]))
`

type MarkNotificationsReadParams struct {
	MemberID pgtype.UUID `json:"member_id"`
	ID       pgtype.Int4 `json:"id"`
	Ids      []int32     `json:"ids"`
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, arg.MemberID, arg.ID, arg.Ids)
	return err
}

const replaceSubscribedTags = `-- name: ReplaceSubscribedTags :exec
DELETE FROM _member_tag_subscriptions WHERE "A" = $1
`

func (q *Queries) ReplaceSubscribedTags(ctx context.Context, a pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceSubscribedTags, a)
	return err
}

const replaceSubscriptionSettings = `-- name: ReplaceSubscriptionSettings :exec
DELETE FROM subscription_settings WHERE member_id = $1
`

func (q *Queries) ReplaceSubscriptionSettings(ctx context.Context, memberID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceSubscriptionSettings, memberID)
	return err
}

const upsertExpoToken = `-- name: UpsertExpoToken :exec
INSERT INTO expo_tokens (member_id, expo_token) VALUES ($1, $2)
ON CONFLICT (expo_token) DO UPDATE SET member_id = EXCLUDED.member_id
`

type UpsertExpoTokenParams struct {
	MemberID  pgtype.UUID `json:"member_id"`
	ExpoToken string      `json:"expo_token"`
}

func (q *Queries) UpsertExpoToken(ctx context.Context, arg UpsertExpoTokenParams) error {
	_, err := q.db.Exec(ctx, upsertExpoToken, arg.MemberID, arg.ExpoToken)
	return err
}
