// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPosition = `-- name: GetPosition :one
SELECT p.id, p.name_sv, p.name_en, p.committee_id, p.email, p.active, p.board_member,
       p.description_sv, p.description_en, p.start_month, p.end_month,
       c.name_sv AS committee_name_sv, c.name_en AS committee_name_en, c.short_name AS committee_short_name
FROM positions p
LEFT JOIN committees c ON c.id = p.committee_id
WHERE p.id = $1
`

type GetPositionRow struct {
	ID                 string      `json:"id"`
	NameSv             string      `json:"name_sv"`
	NameEn             pgtype.Text `json:"name_en"`
	CommitteeID        pgtype.UUID `json:"committee_id"`
	Email              pgtype.Text `json:"email"`
	Active             bool        `json:"active"`
	BoardMember        bool        `json:"board_member"`
	DescriptionSv      pgtype.Text `json:"description_sv"`
	DescriptionEn      pgtype.Text `json:"description_en"`
	StartMonth         int32       `json:"start_month"`
	EndMonth           int32       `json:"end_month"`
	CommitteeNameSv    pgtype.Text `json:"committee_name_sv"`
	CommitteeNameEn    pgtype.Text `json:"committee_name_en"`
	CommitteeShortName pgtype.Text `json:"committee_short_name"`
}

// Joins the committee (name/shortName), unlike ListPositions/UpdatePosition -
// the position detail page links/displays the committee without a second
// request.
func (q *Queries) GetPosition(ctx context.Context, id string) (GetPositionRow, error) {
	row := q.db.QueryRow(ctx, getPosition, id)
	var i GetPositionRow
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.CommitteeID,
		&i.Email,
		&i.Active,
		&i.BoardMember,
		&i.DescriptionSv,
		&i.DescriptionEn,
		&i.StartMonth,
		&i.EndMonth,
		&i.CommitteeNameSv,
		&i.CommitteeNameEn,
		&i.CommitteeShortName,
	)
	return i, err
}

const listBoard = `-- name: ListBoard :many
SELECT p.id, p.name_sv, p.name_en, p.committee_id, p.email, p.active, p.board_member,
       p.description_sv, p.description_en, p.start_month, p.end_month,
       mem.id AS member_id, mem.student_id, mem.first_name, mem.nickname,
       mem.last_name, mem.picture_path, mem.class_year, mem.class_programme
FROM positions p
LEFT JOIN LATERAL (
    SELECT m.member_id
    FROM mandates m
    WHERE m.position_id = p.id
      AND m.start_date <= CURRENT_DATE AND m.end_date >= CURRENT_DATE
    ORDER BY m.start_date DESC
    LIMIT 1
) active_mandate ON true
LEFT JOIN members mem ON mem.id = active_mandate.member_id
WHERE p.board_member = true AND p.active = true
ORDER BY p.id
`

type ListBoardRow struct {
	ID             string      `json:"id"`
	NameSv         string      `json:"name_sv"`
	NameEn         pgtype.Text `json:"name_en"`
	CommitteeID    pgtype.UUID `json:"committee_id"`
	Email          pgtype.Text `json:"email"`
	Active         bool        `json:"active"`
	BoardMember    bool        `json:"board_member"`
	DescriptionSv  pgtype.Text `json:"description_sv"`
	DescriptionEn  pgtype.Text `json:"description_en"`
	StartMonth     int32       `json:"start_month"`
	EndMonth       int32       `json:"end_month"`
	MemberID       pgtype.UUID `json:"member_id"`
	StudentID      pgtype.Text `json:"student_id"`
	FirstName      pgtype.Text `json:"first_name"`
	Nickname       pgtype.Text `json:"nickname"`
	LastName       pgtype.Text `json:"last_name"`
	PicturePath    pgtype.Text `json:"picture_path"`
	ClassYear      pgtype.Int4 `json:"class_year"`
	ClassProgramme pgtype.Text `json:"class_programme"`
}

// Board positions (board_member=true, active=true) with their current
// holder, one row per position (LEFT JOIN LATERAL picks at most the most
// recently-started active mandate; NULL member fields mean vacant) - backs
// GET /board. Staben redaction (hiding organizing-committee positions from
// viewers without MemberSeeStaben) happens in committees.Service.ListBoard,
// not here - this query returns the unredacted set.
func (q *Queries) ListBoard(ctx context.Context) ([]ListBoardRow, error) {
	rows, err := q.db.Query(ctx, listBoard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardRow{}
	for rows.Next() {
		var i ListBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.CommitteeID,
			&i.Email,
			&i.Active,
			&i.BoardMember,
			&i.DescriptionSv,
			&i.DescriptionEn,
			&i.StartMonth,
			&i.EndMonth,
			&i.MemberID,
			&i.StudentID,
			&i.FirstName,
			&i.Nickname,
			&i.LastName,
			&i.PicturePath,
			&i.ClassYear,
			&i.ClassProgramme,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, name_sv, name_en, committee_id, email, active, board_member,
       description_sv, description_en, start_month, end_month
FROM positions
ORDER BY name_sv
`

type ListPositionsRow struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	CommitteeID   pgtype.UUID `json:"committee_id"`
	Email         pgtype.Text `json:"email"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	StartMonth    int32       `json:"start_month"`
	EndMonth      int32       `json:"end_month"`
}

func (q *Queries) ListPositions(ctx context.Context) ([]ListPositionsRow, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionsRow{}
	for rows.Next() {
		var i ListPositionsRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.CommitteeID,
			&i.Email,
			&i.Active,
			&i.BoardMember,
			&i.DescriptionSv,
			&i.DescriptionEn,
			&i.StartMonth,
			&i.EndMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET name_sv = $2, name_en = $3, email = $4, description_sv = $5, description_en = $6,
    active = $7, board_member = $8
WHERE id = $1
RETURNING id, name_sv, name_en, committee_id, email, active, board_member,
          description_sv, description_en, start_month, end_month
`

type UpdatePositionParams struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	Email         pgtype.Text `json:"email"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
}

type UpdatePositionRow struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	CommitteeID   pgtype.UUID `json:"committee_id"`
	Email         pgtype.Text `json:"email"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	StartMonth    int32       `json:"start_month"`
	EndMonth      int32       `json:"end_month"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (UpdatePositionRow, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.ID,
		arg.NameSv,
		arg.NameEn,
		arg.Email,
		arg.DescriptionSv,
		arg.DescriptionEn,
		arg.Active,
		arg.BoardMember,
	)
	var i UpdatePositionRow
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.CommitteeID,
		&i.Email,
		&i.Active,
		&i.BoardMember,
		&i.DescriptionSv,
		&i.DescriptionEn,
		&i.StartMonth,
		&i.EndMonth,
	)
	return i, err
}
