// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: positions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPosition = `-- name: GetPosition :one
SELECT id, name_sv, name_en, committee_id, email, active, board_member,
       description_sv, description_en, start_month, end_month
FROM positions
WHERE id = $1
`

type GetPositionRow struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	CommitteeID   pgtype.UUID `json:"committee_id"`
	Email         pgtype.Text `json:"email"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	StartMonth    int32       `json:"start_month"`
	EndMonth      int32       `json:"end_month"`
}

func (q *Queries) GetPosition(ctx context.Context, id string) (GetPositionRow, error) {
	row := q.db.QueryRow(ctx, getPosition, id)
	var i GetPositionRow
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.CommitteeID,
		&i.Email,
		&i.Active,
		&i.BoardMember,
		&i.DescriptionSv,
		&i.DescriptionEn,
		&i.StartMonth,
		&i.EndMonth,
	)
	return i, err
}

const listPositions = `-- name: ListPositions :many
SELECT id, name_sv, name_en, committee_id, email, active, board_member,
       description_sv, description_en, start_month, end_month
FROM positions
ORDER BY name_sv
`

type ListPositionsRow struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	CommitteeID   pgtype.UUID `json:"committee_id"`
	Email         pgtype.Text `json:"email"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	StartMonth    int32       `json:"start_month"`
	EndMonth      int32       `json:"end_month"`
}

func (q *Queries) ListPositions(ctx context.Context) ([]ListPositionsRow, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPositionsRow{}
	for rows.Next() {
		var i ListPositionsRow
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.CommitteeID,
			&i.Email,
			&i.Active,
			&i.BoardMember,
			&i.DescriptionSv,
			&i.DescriptionEn,
			&i.StartMonth,
			&i.EndMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET name_sv = $2, name_en = $3, email = $4, description_sv = $5, description_en = $6,
    active = $7, board_member = $8
WHERE id = $1
RETURNING id, name_sv, name_en, committee_id, email, active, board_member,
          description_sv, description_en, start_month, end_month
`

type UpdatePositionParams struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	Email         pgtype.Text `json:"email"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
}

type UpdatePositionRow struct {
	ID            string      `json:"id"`
	NameSv        string      `json:"name_sv"`
	NameEn        pgtype.Text `json:"name_en"`
	CommitteeID   pgtype.UUID `json:"committee_id"`
	Email         pgtype.Text `json:"email"`
	Active        bool        `json:"active"`
	BoardMember   bool        `json:"board_member"`
	DescriptionSv pgtype.Text `json:"description_sv"`
	DescriptionEn pgtype.Text `json:"description_en"`
	StartMonth    int32       `json:"start_month"`
	EndMonth      int32       `json:"end_month"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (UpdatePositionRow, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.ID,
		arg.NameSv,
		arg.NameEn,
		arg.Email,
		arg.DescriptionSv,
		arg.DescriptionEn,
		arg.Active,
		arg.BoardMember,
	)
	var i UpdatePositionRow
	err := row.Scan(
		&i.ID,
		&i.NameSv,
		&i.NameEn,
		&i.CommitteeID,
		&i.Email,
		&i.Active,
		&i.BoardMember,
		&i.DescriptionSv,
		&i.DescriptionEn,
		&i.StartMonth,
		&i.EndMonth,
	)
	return i, err
}
