// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddArticleLike(ctx context.Context, arg AddArticleLikeParams) error
	AddArticleTags(ctx context.Context, arg AddArticleTagsParams) error
	AddBookingRequestBookables(ctx context.Context, arg AddBookingRequestBookablesParams) error
	// Going/interested are mutually exclusive in the UI (see
	// internal/events.Service.SetGoing/SetInterested/ClearAttendance), but that
	// exclusivity isn't a DB constraint - same situation as the old Prisma
	// code, which only enforced it by always writing both relations together
	// from three fixed call sites. Each pair of queries below is called
	// together for that reason.
	AddEventGoing(ctx context.Context, arg AddEventGoingParams) error
	AddEventInterested(ctx context.Context, arg AddEventInterestedParams) error
	AddEventTags(ctx context.Context, arg AddEventTagsParams) error
	// Atomically applies a signed adjustment to quantity_available/nr_bottles,
	// guarded so neither can go negative (returns zero rows, not an error, if
	// the guard would be violated - the caller distinguishes "not found" from
	// "insufficient stock" itself). Used by every stocklist write path that
	// touches an item's running totals: CreateBatch (the delta itself),
	// UpdateBatch/DeleteBatch (the net difference between old and new/removed
	// delta) - unifying what the old app implemented as three separate
	// ad-hoc Prisma transactions into one atomic SQL statement.
	AdjustDrinkItemQuantity(ctx context.Context, arg AdjustDrinkItemQuantityParams) (Drinkitem, error)
	ClearArticleTags(ctx context.Context, articleID pgtype.UUID) error
	ClearBookingRequestBookables(ctx context.Context, bookingRequestID pgtype.UUID) error
	ClearEventTags(ctx context.Context, eventID pgtype.UUID) error
	// Mirrors the old removePhadder action: clears every one of this member's
	// mandates currently tagged to this group (not just the single "active"
	// one FindActivePhadderMandate would pick), matching the old code's
	// `mandates.map(...)` bulk-disconnect over every matching mandate.
	ClearMandatePhadderGroupForMember(ctx context.Context, arg ClearMandatePhadderGroupForMemberParams) error
	// Only clears if the member is currently in exactly this group - mirrors
	// the old Prisma `disconnect`, which is a no-op unless the relation
	// actually exists.
	ClearMemberPhadderGroup(ctx context.Context, arg ClearMemberPhadderGroupParams) error
	CloseAlertForMember(ctx context.Context, arg CloseAlertForMemberParams) error
	CountArticleSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error)
	CountEventSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)
	CountSongSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountSongs(ctx context.Context, arg CountSongsParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, memberID pgtype.UUID) (int64, error)
	CreateAccessPolicy(ctx context.Context, arg CreateAccessPolicyParams) (ApiAccessPolicy, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error)
	CreateArticleComment(ctx context.Context, arg CreateArticleCommentParams) (CreateArticleCommentRow, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (pgtype.UUID, error)
	CreateBookable(ctx context.Context, arg CreateBookableParams) (CreateBookableRow, error)
	CreateBookableCategory(ctx context.Context, arg CreateBookableCategoryParams) (BookableCategory, error)
	CreateBookingRequest(ctx context.Context, arg CreateBookingRequestParams) (BookingRequest, error)
	CreateCafeShift(ctx context.Context, arg CreateCafeShiftParams) (CafeShift, error)
	CreateDoorAccessPolicy(ctx context.Context, arg CreateDoorAccessPolicyParams) (DoorAccessPolicy, error)
	CreateDrinkItem(ctx context.Context, arg CreateDrinkItemParams) (Drinkitem, error)
	CreateDrinkItemBatch(ctx context.Context, arg CreateDrinkItemBatchParams) (Drinkitembatch, error)
	CreateElection(ctx context.Context, arg CreateElectionParams) (Election, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error)
	CreateEventComment(ctx context.Context, arg CreateEventCommentParams) (CreateEventCommentRow, error)
	CreateGoverningDocument(ctx context.Context, arg CreateGoverningDocumentParams) (Document, error)
	CreateMandate(ctx context.Context, arg CreateMandateParams) (CreateMandateRow, error)
	// Minimal port of src/lib/utils/member.ts's createMember: just the bare
	// Member row. Default subscription_settings/tag-subscription seeding
	// (previously a documented gap here) now happens as a separate step right
	// after this insert - see internal/auth's resolveOrCreateMember and
	// internal/notifications.Service.SeedDefaults (Phase 9).
	CreateMember(ctx context.Context, arg CreateMemberParams) (CreateMemberRow, error)
	// title/message/type/link/from_author_id are constant across one Send call
	// - only member_id varies per recipient - same "constant column + unnest"
	// shape as AddArticleTags.
	CreateNotifications(ctx context.Context, arg CreateNotificationsParams) error
	CreatePhadderGroup(ctx context.Context, arg CreatePhadderGroupParams) (PhadderGroup, error)
	CreateRecurringEvent(ctx context.Context, arg CreateRecurringEventParams) (pgtype.UUID, error)
	CreateSeason(ctx context.Context, arg CreateSeasonParams) (NollningSeason, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	DeleteAccessPolicy(ctx context.Context, id pgtype.UUID) error
	DeleteAdminSetting(ctx context.Context, key string) (int64, error)
	DeleteArticleComment(ctx context.Context, arg DeleteArticleCommentParams) error
	DeleteBookingRequest(ctx context.Context, id pgtype.UUID) error
	DeleteCafeShift(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteDoorAccessPolicy(ctx context.Context, id pgtype.UUID) error
	DeleteDrinkItem(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteDrinkItemBatch(ctx context.Context, id pgtype.UUID) (int64, error)
	// Hard delete - the elections table has no removed_at/deleted_at column at
	// all, unlike Song/Article/GoverningDocument.
	DeleteElection(ctx context.Context, id pgtype.UUID) (int64, error)
	DeleteEventComment(ctx context.Context, arg DeleteEventCommentParams) error
	DeleteMandate(ctx context.Context, id pgtype.UUID) error
	DeleteNotifications(ctx context.Context, arg DeleteNotificationsParams) error
	DeletePhadderGroup(ctx context.Context, id pgtype.UUID) error
	// pattern is built by the caller as "{prefix}%" - a real SQL LIKE
	// wildcard, unlike the old TS's `startsWith(`${p}%`)`, which (per Prisma's
	// literal-escaping of startsWith) only ever matched a position id that
	// literally contained a "%" character, i.e. never. User-confirmed fix
	// (2026-09-03, see DESIGN.md's Phase 10 entry): role-based door/create-form
	// validation now does a real prefix match.
	ExistsPositionWithPrefix(ctx context.Context, pattern string) (bool, error)
	// The member's phadder/uppdrag mandate overlapping the group's season
	// window, ordered like the old getPhadderMandates (position id asc, i.e.
	// "phadder" before "uppdrag", then start_date asc) so the first row is the
	// same one the old TS picked with `mandates?.[0]`.
	FindActivePhadderMandate(ctx context.Context, arg FindActivePhadderMandateParams) (FindActivePhadderMandateRow, error)
	// Authors are reused across articles: an author row is the (member,
	// mandate, custom-author) triple, so the same byline is only created once.
	FindAuthor(ctx context.Context, arg FindAuthorParams) (pgtype.UUID, error)
	GetAdminSettings(ctx context.Context, keys []string) ([]GetAdminSettingsRow, error)
	// Unconstrained by type, unlike GetGoverningDocumentByID above - the list
	// page's delete action operates on any document by id regardless of type
	// (MEETING/OTHER/etc. included), matching the old app's
	// prisma.document.delete({where:{id}}) exactly.
	GetAnyGoverningDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	// Used only to seed the mock auth identity in dev when no specific member
	// is configured (see internal/auth, main.go). Arbitrary but deterministic
	// enough for local dev: whichever member sorts first by id.
	GetAnyMember(ctx context.Context) (GetAnyMemberRow, error)
	// Public lookup: only published, not (currently) removed articles.
	GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error)
	GetArticleIDBySlug(ctx context.Context, slug string) (pgtype.UUID, error)
	// Unfiltered lookup: no publish/removed filter. Used internally after
	// create/update (so the caller gets back exactly what it just wrote even if
	// it's a future scheduled draft), and by the ArticleByAnySlug service method
	// for callers - like the SvelteKit edit page - that need to load a draft or
	// future-scheduled article by its own author. There's no auth on this API,
	// so this is no more exposed than the existing unauthenticated mutations;
	// see backend/CLAUDE.md.
	GetArticleRowBySlug(ctx context.Context, slug string) (GetArticleRowBySlugRow, error)
	// Resolves the display identity of a notification's sender: the plain
	// member fields, plus (if the author acted via a mandate) that mandate's
	// position name - mirrors getAuthorName's "Mandate" branch. Custom-author
	// bylines never send notifications in practice (no call site does), so
	// that branch isn't modeled here.
	GetAuthorForNotification(ctx context.Context, id pgtype.UUID) (GetAuthorForNotificationRow, error)
	GetBookableByID(ctx context.Context, id pgtype.UUID) (GetBookableByIDRow, error)
	GetBookableCategoryByID(ctx context.Context, id pgtype.UUID) (BookableCategory, error)
	GetBookingRequestByID(ctx context.Context, id pgtype.UUID) (GetBookingRequestByIDRow, error)
	// Re-fetches a single shift with its worker joined, after
	// CreateCafeShift/UpdateCafeShiftWorker's own RETURNING (which has no room
	// for the join) - used to build the full Shift (with nickname/picture)
	// SetShift returns.
	GetCafeShiftByID(ctx context.Context, id pgtype.UUID) (GetCafeShiftByIDRow, error)
	GetCiabattaByYearWeek(ctx context.Context, arg GetCiabattaByYearWeekParams) (CiabattaOfTheWeek, error)
	// Currently-active mandate/unique-member counts, same as
	// ListCommitteesWithCounts - the committee detail page shows these too.
	GetCommitteeByShortName(ctx context.Context, shortName pgtype.Text) (GetCommitteeByShortNameRow, error)
	// The building-manager position holder, notified on every new booking
	// request - a hardcoded position slug in the old app too (dsek.km.mastare),
	// not configurable.
	GetCurrentKarhusmastare(ctx context.Context) (GetCurrentKarhusmastareRow, error)
	// The season whose window covers right now, if any - internal/nollning
	// treats "at most one season active at a time" as an invariant (not
	// enforced at the DB level, since overlapping seasons would be an admin
	// data error, not a normal state).
	GetCurrentSeason(ctx context.Context) (NollningSeason, error)
	GetDoorByName(ctx context.Context, name string) (Door, error)
	GetDrinkItemBatchByID(ctx context.Context, id pgtype.UUID) (Drinkitembatch, error)
	// Unconstrained by expiry (unlike ListOpenElections) - the edit page looks
	// up an election by id regardless of whether it has already expired,
	// matching prisma.election.findFirst({where: {id}}).
	GetElectionByID(ctx context.Context, id pgtype.UUID) (GetElectionByIDRow, error)
	// Public lookup: hides soft-removed events, same visibility rule as
	// ListEvents. The old TS getEvent() applied no such filter at all (see
	// DESIGN.md's events section) - fixed here rather than replicated.
	GetEventBySlug(ctx context.Context, slug pgtype.Text) (GetEventBySlugRow, error)
	// Phase 9: setAttendance needs the organizer/title/slug to notify on
	// going/interested (see integrations.EventNotification), not just the id
	// GetEventIDBySlug returns.
	GetEventForAttendance(ctx context.Context, slug pgtype.Text) (GetEventForAttendanceRow, error)
	GetEventIDBySlug(ctx context.Context, slug pgtype.Text) (pgtype.UUID, error)
	// Unfiltered lookup: no removed_at filter. Used internally after
	// create/update, and by GetAny for callers - like an edit page - that need
	// to load an event regardless of soft-delete status.
	GetEventRowBySlug(ctx context.Context, slug pgtype.Text) (GetEventRowBySlugRow, error)
	// Constrained to POLICY/GUIDELINE, matching the old app's edit-lookup
	// query - the other enum values have no create/edit UI anywhere.
	GetGoverningDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	// Used to verify a caller posting "as" a mandate actually holds it.
	// custom_authors has no owner column in the schema (they're shared
	// personas, e.g. "Styrelsen"), so there's no equivalent check for those.
	GetMandateMemberID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetMarkdown(ctx context.Context, name string) (Markdown, error)
	GetMemberByStudentID(ctx context.Context, studentID pgtype.Text) (GetMemberByStudentIDRow, error)
	// Resolves a member's display name for message text the real Notifier
	// synthesizes itself (e.g. "X har gillat din nyhet") - mirrors getFullName's
	// inputs exactly (fullName in service.go is the Go port of getFullName).
	GetMemberNameForNotification(ctx context.Context, id pgtype.UUID) (GetMemberNameForNotificationRow, error)
	// Backs PhadderRoleFor's "nolla" branch.
	GetMemberNollaGroupID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Backs PhadderRoleFor's "phadder" branch: which group (if any) this
	// member holds an active phadder/uppdrag mandate pointed at.
	GetMemberPhadderGroupID(ctx context.Context, memberID pgtype.UUID) (pgtype.UUID, error)
	// Full column set for a member's own profile page, unlike
	// GetMemberByStudentID's minimal projection (built only for author
	// resolution).
	GetMemberProfile(ctx context.Context, studentID pgtype.Text) (GetMemberProfileRow, error)
	GetPhadderGroup(ctx context.Context, id pgtype.UUID) (PhadderGroup, error)
	// Joins the committee (name/shortName), unlike ListPositions/UpdatePosition -
	// the position detail page links/displays the committee without a second
	// request.
	GetPosition(ctx context.Context, id string) (GetPositionRow, error)
	GetRecurringEvent(ctx context.Context, id pgtype.UUID) (RecurringEvent, error)
	GetSeason(ctx context.Context, id pgtype.UUID) (NollningSeason, error)
	// include_deleted here means "also visible if deleted" (a union, unlike
	// ListSongs' show_deleted above, which is an exclusive toggle) - mirrors the
	// old app's detail-page load, which bypasses the deletedAt filter entirely
	// for a caller holding song:delete rather than requiring a separate
	// "viewing the trash" mode.
	GetSongBySlug(ctx context.Context, arg GetSongBySlugParams) (Song, error)
	GetSubscribedTagIDsForMember(ctx context.Context, a pgtype.UUID) ([]pgtype.UUID, error)
	GetSubscriptionSettingsForMember(ctx context.Context, memberID pgtype.UUID) ([]SubscriptionSetting, error)
	InsertSubscribedTag(ctx context.Context, arg InsertSubscribedTagParams) error
	InsertSubscriptionSetting(ctx context.Context, arg InsertSubscriptionSettingParams) error
	// Backs IsStaben: does memberID hold a mandate, active today, on a position
	// belonging to committeeID.
	IsMemberActiveOnCommittee(ctx context.Context, arg IsMemberActiveOnCommitteeParams) (bool, error)
	// Optional apiName filter; joins member first/last name for studentId-scoped
	// rows (role-scoped rows have no member to join).
	ListAccessPolicies(ctx context.Context, apiName pgtype.Text) ([]ListAccessPoliciesRow, error)
	ListActiveAlerts(ctx context.Context) ([]Alert, error)
	// The real security-relevant read: policies currently in their active
	// window (both start and end), for GET /salto/{door} to resolve into an
	// allowed-student list. Unlike ListDoorAccessPoliciesForAdmin, a
	// not-yet-started policy is excluded here - matches the old +server.ts's
	// own filter exactly.
	ListActiveDoorAccessPoliciesForSalto(ctx context.Context, doorName string) ([]ListActiveDoorAccessPoliciesForSaltoRow, error)
	// "Active" mirrors the old TS backend's author-options query: currently
	// within the mandate's start/end date range.
	ListActiveMandatesForMember(ctx context.Context, memberID pgtype.UUID) ([]ListActiveMandatesForMemberRow, error)
	// Backs the member profile page's own "which doors do I have access to"
	// widget (self-view only) - a member's currently-held positions, used to
	// both derive candidate door-policy roles and to display position names
	// instead of raw role strings in the result.
	ListActivePositionsForMemberByStudentID(ctx context.Context, studentID pgtype.Text) ([]ListActivePositionsForMemberByStudentIDRow, error)
	ListAdminSettings(ctx context.Context) ([]AdminSetting, error)
	// Unscoped (full history, not year-scoped) - the position detail page
	// groups a position's entire mandate history client-side by year for
	// historical study-year statistics, unlike the committee detail page's
	// single-year view. Includes class_year/class_programme for that stats
	// computation and the member's programme badge.
	ListAllMandatesForPosition(ctx context.Context, positionID string) ([]ListAllMandatesForPositionRow, error)
	// Every member id - used for the ALWAYS_ON settingType bucket, which
	// (per SUBSCRIPTION_SETTINGS_MAP) has no subscription_settings row
	// requirement at all.
	ListAllMemberIDs(ctx context.Context, arg ListAllMemberIDsParams) ([]pgtype.UUID, error)
	ListArticleComments(ctx context.Context, articleID pgtype.UUID) ([]ListArticleCommentsRow, error)
	// Shared column list for the "joined article" shape: article + committee +
	// author (member / mandate+position / custom author) + comment & like
	// counts. Duplicated across ListArticles/GetArticleBySlug/GetArticleRowBySlug
	// because sqlc has no macro/fragment support.
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error)
	ListAvailableDrinkItems(ctx context.Context) ([]Drinkitem, error)
	// Board positions (board_member=true, active=true) with their current
	// holder, one row per position (LEFT JOIN LATERAL picks at most the most
	// recently-started active mandate; NULL member fields mean vacant) - backs
	// GET /board. Staben redaction (hiding organizing-committee positions from
	// viewers without MemberSeeStaben) happens in committees.Service.ListBoard,
	// not here - this query returns the unredacted set.
	ListBoard(ctx context.Context) ([]ListBoardRow, error)
	ListBookableCategories(ctx context.Context) ([]BookableCategory, error)
	ListBookables(ctx context.Context) ([]ListBookablesRow, error)
	ListBookablesForBookingRequests(ctx context.Context, bookingRequestIds []pgtype.UUID) ([]ListBookablesForBookingRequestsRow, error)
	// Every shift (with its worker) in [start_date, end_date] inclusive -
	// start_date/end_date share the same TIMESTAMP(3) precision as the
	// column, so callers pass day-aligned bounds. Used both for a week's
	// worth of shifts (ListShifts) and for a single day's shifts (the
	// toggle logic in SetShift, which needs every slot for one date at once,
	// mirroring the old updateSchedule action's single dayShifts query).
	ListCafeShiftsInRange(ctx context.Context, arg ListCafeShiftsInRangeParams) ([]ListCafeShiftsInRangeRow, error)
	ListClosedAlertIDsForMember(ctx context.Context, b pgtype.UUID) ([]pgtype.UUID, error)
	// Full fields + currently-active mandate/unique-member counts, for the
	// committee overview page (mirrors the old "about" page's query).
	ListCommitteesWithCounts(ctx context.Context) ([]ListCommitteesWithCountsRow, error)
	// Committees eligible for a committee medal - excludes the same fixed
	// short_name set the old app hardcoded (valb/other/dchip/medalj).
	ListCommitteesWithMedals(ctx context.Context) ([]ListCommitteesWithMedalsRow, error)
	// Non-blocking overlap warning (2026-09-02 decision, see DESIGN.md's
	// Booking section) - the old app never checked this at all; Go surfaces it
	// as a warning on create/update rather than rejecting the request outright.
	// DENIED requests never conflict; exclude_id lets an edit ignore its own
	// pre-existing row (NULL/unset on create, where nothing to exclude yet).
	ListConflictingBookingRequests(ctx context.Context, arg ListConflictingBookingRequestsParams) ([]ListConflictingBookingRequestsRow, error)
	// Unfiltered: the old TS backend restricted this list to custom authors
	// whose custom_author_roles matched one of the member's Keycloak-derived
	// roles (getDerivedRoles) - that role-derivation system isn't ported to Go
	// (see ../../DESIGN.md's Auth section on the mock RBAC gap), so for now
	// every member can choose from every custom author. Revisit once real
	// roles exist.
	ListCustomAuthors(ctx context.Context) ([]ListCustomAuthorsRow, error)
	ListDefaultTagIDs(ctx context.Context) ([]pgtype.UUID, error)
	ListDistinctAPINames(ctx context.Context) ([]string, error)
	ListDistinctSongCategories(ctx context.Context, includeDeleted pgtype.Bool) ([]pgtype.Text, error)
	ListDistinctSongMelodies(ctx context.Context, includeDeleted pgtype.Bool) ([]pgtype.Text, error)
	// The admin edit-door page's own list: every non-expired policy for a
	// door (start in the future is fine, still shown - only end in the past
	// is excluded), joined to the member it names if it's a studentId-scoped
	// row. Deliberately not filtered by start_datetime, unlike
	// ListActiveDoorAccessPoliciesForSalto below - mirrors the old
	// edit/[slug]/+page.server.ts load exactly.
	ListDoorAccessPoliciesForAdmin(ctx context.Context, doorName string) ([]ListDoorAccessPoliciesForAdminRow, error)
	// The self-view widget's own policy read: non-banned policies either
	// naming this member's studentId directly, or naming one of their
	// candidate derived roles (every dot-prefix of each held position id, plus
	// "*"/"_"/"dsek.styr" as applicable - computed in Go, mirroring
	// getDerivedRoles - and passed in as roles). Exact role equality, not a
	// prefix LIKE - this is the opposite direction from salto's own matching
	// (there, a stored role is a prefix of a position id; here, a candidate
	// role is checked for exact membership).
	ListDoorAccessPoliciesForMemberView(ctx context.Context, arg ListDoorAccessPoliciesForMemberViewParams) ([]ListDoorAccessPoliciesForMemberViewRow, error)
	ListDoors(ctx context.Context) ([]Door, error)
	// Every batch entry (optionally only those on/before before_date), joined
	// with its item, newest first - matches treasury/+page.server.ts's load
	// exactly (before_date unset = every entry).
	ListDrinkItemBatches(ctx context.Context, beforeDate pgtype.Timestamp) ([]ListDrinkItemBatchesRow, error)
	ListDrinkItems(ctx context.Context) ([]Drinkitem, error)
	ListEmailAliasesForPosition(ctx context.Context, positionID string) ([]EmailAlias, error)
	ListEventComments(ctx context.Context, eventID pgtype.UUID) ([]ListEventCommentsRow, error)
	ListEventGoing(ctx context.Context, eventID pgtype.UUID) ([]ListEventGoingRow, error)
	ListEventInterested(ctx context.Context, eventID pgtype.UUID) ([]ListEventInterestedRow, error)
	// Every other occurrence in a recurring series, for a FUTURE/ALL edit or
	// delete. min_start_datetime narg'd out entirely (not just NULL) for ALL,
	// set for FUTURE (see internal/events.Service.Update/Delete).
	ListEventSiblings(ctx context.Context, arg ListEventSiblingsParams) ([]ListEventSiblingsRow, error)
	// Shared column list for the "joined event" shape: event + author (plain
	// member - events have no mandate/custom-author byline, see internal/events
	// doc comments) + comment/going/interested counts. Duplicated across
	// ListEvents/GetEventBySlug/GetEventRowBySlug because sqlc has no
	// macro/fragment support (same situation as articles.sql).
	// Ordering direction depends on 'past': upcoming events sort soonest-first
	// (ASC), past events sort most-recent-first (DESC). sqlc can't parameterize
	// ORDER BY directly, so both directions are expressed as CASE'd sort keys -
	// exactly one is non-null per row depending on 'past', the other ties (NULL)
	// and is ignored.
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListExpoTokensWithUnreadCount(ctx context.Context, memberIds []pgtype.UUID) ([]ListExpoTokensWithUnreadCountRow, error)
	ListGoverningDocuments(ctx context.Context) ([]Document, error)
	// Full mandate history (not just currently-active, unlike
	// ListActiveMandatesForMember) for a member's profile page, joined to
	// position+committee for display.
	ListMandatesForMember(ctx context.Context, memberID pgtype.UUID) ([]ListMandatesForMemberRow, error)
	// All mandates (not just active-during-the-window ones) for a given member
	// set, that started before the cutoff - mirrors the old app's allMandates
	// query, which only bounds start_date (no end_date filter) since award
	// semesters are computed by intersecting with "after" in Go, not in SQL.
	ListMandatesForMembersBefore(ctx context.Context, arg ListMandatesForMembersBeforeParams) ([]ListMandatesForMembersBeforeRow, error)
	// Year-scoped (overlapping [year-01-01, year-12-31]), joined to member -
	// mirrors the committee detail page's year filter (GET /committees/{shortName}?year=).
	ListMandatesForPosition(ctx context.Context, arg ListMandatesForPositionParams) ([]ListMandatesForPositionRow, error)
	// Lists every markdowns row whose name matches prefix (a plain LIKE
	// pattern, e.g. "cafe:open%") - internal/cafe's own private reuse of the
	// markdowns table, same pattern as internal/committees' direct
	// GetMarkdown call. internal/markdown itself only ever fetches one named
	// page at a time, so this doesn't belong there.
	ListMarkdownsByPrefix(ctx context.Context, prefix string) ([]Markdown, error)
	// Distinct members who held any mandate active during [start, end) - the
	// candidate set medalRecipients scopes its per-member computation to,
	// mirroring the old app's mandatesInAfter query exactly.
	ListMemberIDsWithMandateActiveDuring(ctx context.Context, arg ListMemberIDsWithMandateActiveDuringParams) ([]pgtype.UUID, error)
	// Full mandate history for one member, joined to board_member/committee_id
	// - everything memberMedals (src/lib/server/medals/medals.ts) needs to
	// compute that member's own medal semesters.
	ListMemberMandatesWithPosition(ctx context.Context, memberID pgtype.UUID) ([]ListMemberMandatesWithPositionRow, error)
	// Mirrors the old members-directory page's filter: both params are
	// optional (a NULL narg matches everything) - the old TS route required
	// classYear, but that was a SvelteKit-page UX constraint (it needed a
	// value to pre-fill a dropdown), not an intentional API restriction.
	ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error)
	ListMembersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListMembersByIDsRow, error)
	ListMembersSubscribedToAnyTag(ctx context.Context, tagIds []pgtype.UUID) ([]pgtype.UUID, error)
	// Members subscribed to settingType, optionally narrowed to a specific
	// candidate id list (mirrors sendNotification's memberIds intersection).
	// Excludes fromMemberID (the sender) and any member already notified about
	// this exact (type, link, fromAuthorId) unless allowDuplicates.
	ListMembersWithSubscriptionSetting(ctx context.Context, arg ListMembersWithSubscriptionSettingParams) ([]pgtype.UUID, error)
	ListNollaNotificationsForMember(ctx context.Context, arg ListNollaNotificationsForMemberParams) ([]Notification, error)
	ListNollningTagIDs(ctx context.Context) ([]pgtype.UUID, error)
	ListNollorForGroup(ctx context.Context, nollningGroupID pgtype.UUID) ([]ListNollorForGroupRow, error)
	ListNotificationsForMember(ctx context.Context, memberID pgtype.UUID) ([]Notification, error)
	// Only elections that haven't expired yet, soonest-closing first - matches
	// the old /elections page's prisma.election.findMany({where: {expiresAt:
	// {gte: now()}}, orderBy: [{expiresAt: "asc"}]}) exactly. Joins the small
	// slice of committees columns the election card actually renders (icon +
	// name), same fields the old page's committee `select` projected.
	ListOpenElections(ctx context.Context) ([]ListOpenElectionsRow, error)
	// Nolla/phadder counts alongside each group, mirroring
	// ListCommitteesWithCounts' count-subquery pattern.
	ListPhadderGroups(ctx context.Context, seasonID pgtype.UUID) ([]ListPhadderGroupsRow, error)
	// Distinct members holding a mandate tagged to this group (a member can in
	// principle hold more than one such mandate - see FindActivePhadderMandate).
	ListPhaddrarForGroup(ctx context.Context, phadderinid pgtype.UUID) ([]ListPhaddrarForGroupRow, error)
	// Mirrors hooks.server.helpers.ts's getAccessPolicies: a policy applies if
	// it's granted to any of the caller's derived roles, or to their
	// student_id specifically. Pass a NULL student_id for an anonymous caller
	// (no derived roles are ever real student ids) - "student_id = NULL" never
	// matches, which is the same no-op the old code got from Prisma ignoring
	// an undefined filter.
	ListPoliciesForRolesOrStudentID(ctx context.Context, arg ListPoliciesForRolesOrStudentIDParams) ([]string, error)
	// patterns are caller-built "{role}%" LIKE patterns, one per non-wildcard
	// role a door policy names - see ExistsPositionWithPrefix's doc comment for
	// why this is a real prefix match, not the old app's broken literal one.
	ListPositionIDsMatchingPrefixes(ctx context.Context, patterns []string) ([]string, error)
	ListPositions(ctx context.Context) ([]ListPositionsRow, error)
	ListPushEnabledMemberIDs(ctx context.Context, arg ListPushEnabledMemberIDsParams) ([]pgtype.UUID, error)
	// Backs the "*" wildcard role (see 2024-11-25's "Added support for
	// wildcard roles in door access policies") - every member whose class year
	// is within the last ~10 years, matching the old app's
	// `classYear: {gte: currentYear - 10}` exactly.
	ListRecentMemberStudentIDs(ctx context.Context, minClassYear int32) ([]pgtype.Text, error)
	ListSeasons(ctx context.Context) ([]NollningSeason, error)
	// show_deleted toggles between two mutually exclusive views (mirroring the
	// old app's "show-deleted" query param on the songbook list page): the
	// normal active-songs list (false/unset) or the trash view of only
	// soft-deleted songs (true) - never both at once, unlike GetSongBySlug's
	// include_deleted below, which unions.
	ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error)
	// Current (start_date <= today <= end_date) mandate holders of any of the
	// given positions - the role-based half of salto's allowed-student list.
	ListStudentIDsForActivePositions(ctx context.Context, positionIds []string) ([]pgtype.Text, error)
	ListTags(ctx context.Context) ([]Tag, error)
	// Used by the Discord webhook to check for a NOLLNING-prefixed tag and pick
	// the embed's color/footer from the article's first tag.
	ListTagsByIDs(ctx context.Context, ids []pgtype.UUID) ([]ListTagsByIDsRow, error)
	ListTagsForArticles(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListTagsForArticlesRow, error)
	ListTagsForEvents(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListTagsForEventsRow, error)
	// Mirrors the old app's getUpcomingBookingRequests: every request starting
	// on or after `since` (callers pass now-1week, matching the old hardcoded
	// window), regardless of booker - visibility is gated at the service layer
	// (booking_request:read), not per-row ownership.
	ListUpcomingBookingRequests(ctx context.Context, since pgtype.Timestamptz) ([]ListUpcomingBookingRequestsRow, error)
	MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error
	RemoveArticleLike(ctx context.Context, arg RemoveArticleLikeParams) error
	RemoveEventGoing(ctx context.Context, arg RemoveEventGoingParams) error
	RemoveEventInterested(ctx context.Context, arg RemoveEventInterestedParams) error
	ReplaceSubscribedTags(ctx context.Context, a pgtype.UUID) error
	ReplaceSubscriptionSettings(ctx context.Context, memberID pgtype.UUID) error
	RestoreSong(ctx context.Context, id pgtype.UUID) error
	// Targeted single-field write: the caller's external scheduler task id,
	// recorded after scheduling a future publish succeeds. Deliberately
	// separate from UpdateArticle (which is full-replace) since this needs to
	// happen without the caller re-submitting the whole article.
	SetArticleScheduledID(ctx context.Context, arg SetArticleScheduledIDParams) error
	SetMandatePhadderGroup(ctx context.Context, arg SetMandatePhadderGroupParams) error
	SetMemberPhadderGroup(ctx context.Context, arg SetMemberPhadderGroupParams) error
	SoftDeleteAlert(ctx context.Context, id pgtype.UUID) error
	SoftDeleteArticle(ctx context.Context, slug string) error
	SoftDeleteEvent(ctx context.Context, id pgtype.UUID) error
	// Powers both FUTURE (min_start_datetime set) and ALL (narg'd out) series
	// deletes in one statement, unlike the per-row loop UpdateEvent needs (a
	// plain removed_at write has no per-row content to vary).
	SoftDeleteEventSeries(ctx context.Context, arg SoftDeleteEventSeriesParams) error
	SoftDeleteGoverningDocument(ctx context.Context, id pgtype.UUID) error
	SoftDeleteSong(ctx context.Context, id pgtype.UUID) error
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error)
	UpdateBookable(ctx context.Context, arg UpdateBookableParams) (UpdateBookableRow, error)
	UpdateBookableCategory(ctx context.Context, arg UpdateBookableCategoryParams) (BookableCategory, error)
	// Full-replace of the editable fields, same PUT-dressed-as-PATCH
	// convention as articles/events/songs. Status is passed through explicitly
	// rather than left untouched - the service decides whether to reset it to
	// PENDING (non-admin edit) or keep the caller-supplied value (admin edit),
	// mirroring the old app's isAdmin branch exactly.
	UpdateBookingRequest(ctx context.Context, arg UpdateBookingRequestParams) (BookingRequest, error)
	UpdateBookingRequestStatus(ctx context.Context, arg UpdateBookingRequestStatusParams) (BookingRequest, error)
	// Reassigns an existing shift to a different worker - the admin-only
	// "there's already a shift here, but not this member's" branch.
	UpdateCafeShiftWorker(ctx context.Context, arg UpdateCafeShiftWorkerParams) (CafeShift, error)
	UpdateCommittee(ctx context.Context, arg UpdateCommitteeParams) (Committee, error)
	// Mirrors showproducts' updateSchema exactly - quantityType is not
	// editable via this action (only set at creation), matching the old form's
	// own field set.
	UpdateDrinkItem(ctx context.Context, arg UpdateDrinkItemParams) (Drinkitem, error)
	UpdateDrinkItemBatch(ctx context.Context, arg UpdateDrinkItemBatchParams) (Drinkitembatch, error)
	UpdateElection(ctx context.Context, arg UpdateElectionParams) (Election, error)
	// Full-replace of content fields (same PUT-not-PATCH convention as
	// articles), plus this occurrence's own start/end datetime. author_id is
	// deliberately never reassigned here - see internal/events doc comments on
	// why events diverge from articles' "always re-attribute to the editor"
	// rule.
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error)
	UpdateGoverningDocument(ctx context.Context, arg UpdateGoverningDocumentParams) (Document, error)
	UpdateMandate(ctx context.Context, arg UpdateMandateParams) (UpdateMandateRow, error)
	UpdateMemberFoodPreference(ctx context.Context, arg UpdateMemberFoodPreferenceParams) (UpdateMemberFoodPreferenceRow, error)
	UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) (UpdateMemberProfileRow, error)
	UpdatePhadderGroup(ctx context.Context, arg UpdatePhadderGroupParams) (PhadderGroup, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (UpdatePositionRow, error)
	UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (NollningSeason, error)
	UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error)
	UpsertAdminSetting(ctx context.Context, arg UpsertAdminSettingParams) (AdminSetting, error)
	UpsertCiabatta(ctx context.Context, arg UpsertCiabattaParams) (CiabattaOfTheWeek, error)
	UpsertExpoToken(ctx context.Context, arg UpsertExpoTokenParams) error
	UpsertMarkdown(ctx context.Context, arg UpsertMarkdownParams) (Markdown, error)
}

var _ Querier = (*Queries)(nil)
