// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddArticleLike(ctx context.Context, arg AddArticleLikeParams) error
	AddArticleTags(ctx context.Context, arg AddArticleTagsParams) error
	// Going/interested are mutually exclusive in the UI (see
	// internal/events.Service.SetGoing/SetInterested/ClearAttendance), but that
	// exclusivity isn't a DB constraint - same situation as the old Prisma
	// code, which only enforced it by always writing both relations together
	// from three fixed call sites. Each pair of queries below is called
	// together for that reason.
	AddEventGoing(ctx context.Context, arg AddEventGoingParams) error
	AddEventInterested(ctx context.Context, arg AddEventInterestedParams) error
	AddEventTags(ctx context.Context, arg AddEventTagsParams) error
	ClearArticleTags(ctx context.Context, articleID pgtype.UUID) error
	ClearEventTags(ctx context.Context, eventID pgtype.UUID) error
	// Mirrors the old removePhadder action: clears every one of this member's
	// mandates currently tagged to this group (not just the single "active"
	// one FindActivePhadderMandate would pick), matching the old code's
	// `mandates.map(...)` bulk-disconnect over every matching mandate.
	ClearMandatePhadderGroupForMember(ctx context.Context, arg ClearMandatePhadderGroupForMemberParams) error
	// Only clears if the member is currently in exactly this group - mirrors
	// the old Prisma `disconnect`, which is a no-op unless the relation
	// actually exists.
	ClearMemberPhadderGroup(ctx context.Context, arg ClearMemberPhadderGroupParams) error
	CloseAlertForMember(ctx context.Context, arg CloseAlertForMemberParams) error
	CountArticleSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error)
	CountEventSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountEvents(ctx context.Context, arg CountEventsParams) (int64, error)
	CountSongSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountSongs(ctx context.Context, arg CountSongsParams) (int64, error)
	CreateAccessPolicy(ctx context.Context, arg CreateAccessPolicyParams) (ApiAccessPolicy, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error)
	CreateArticleComment(ctx context.Context, arg CreateArticleCommentParams) (CreateArticleCommentRow, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (pgtype.UUID, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error)
	CreateEventComment(ctx context.Context, arg CreateEventCommentParams) (CreateEventCommentRow, error)
	CreateGoverningDocument(ctx context.Context, arg CreateGoverningDocumentParams) (Document, error)
	CreateMandate(ctx context.Context, arg CreateMandateParams) (CreateMandateRow, error)
	// Minimal port of src/lib/utils/member.ts's createMember: this backend
	// doesn't own subscription_settings or tag subscriptions (nollning-period
	// defaults included), so this only creates the bare Member row those
	// features would otherwise hang off of - a deliberate gap, not an
	// oversight, consistent with nollning being out of scope elsewhere in this
	// rewrite (see DESIGN.md).
	CreateMember(ctx context.Context, arg CreateMemberParams) (CreateMemberRow, error)
	CreatePhadderGroup(ctx context.Context, arg CreatePhadderGroupParams) (PhadderGroup, error)
	CreateRecurringEvent(ctx context.Context, arg CreateRecurringEventParams) (pgtype.UUID, error)
	CreateSeason(ctx context.Context, arg CreateSeasonParams) (NollningSeason, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	DeleteAccessPolicy(ctx context.Context, id pgtype.UUID) error
	DeleteArticleComment(ctx context.Context, arg DeleteArticleCommentParams) error
	DeleteEventComment(ctx context.Context, arg DeleteEventCommentParams) error
	DeleteMandate(ctx context.Context, id pgtype.UUID) error
	DeletePhadderGroup(ctx context.Context, id pgtype.UUID) error
	// The member's phadder/uppdrag mandate overlapping the group's season
	// window, ordered like the old getPhadderMandates (position id asc, i.e.
	// "phadder" before "uppdrag", then start_date asc) so the first row is the
	// same one the old TS picked with `mandates?.[0]`.
	FindActivePhadderMandate(ctx context.Context, arg FindActivePhadderMandateParams) (FindActivePhadderMandateRow, error)
	// Authors are reused across articles: an author row is the (member,
	// mandate, custom-author) triple, so the same byline is only created once.
	FindAuthor(ctx context.Context, arg FindAuthorParams) (pgtype.UUID, error)
	// Unconstrained by type, unlike GetGoverningDocumentByID above - the list
	// page's delete action operates on any document by id regardless of type
	// (MEETING/OTHER/etc. included), matching the old app's
	// prisma.document.delete({where:{id}}) exactly.
	GetAnyGoverningDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	// Used only to seed the mock auth identity in dev when no specific member
	// is configured (see internal/auth, main.go). Arbitrary but deterministic
	// enough for local dev: whichever member sorts first by id.
	GetAnyMember(ctx context.Context) (GetAnyMemberRow, error)
	// Public lookup: only published, not (currently) removed articles.
	GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error)
	GetArticleIDBySlug(ctx context.Context, slug string) (pgtype.UUID, error)
	// Unfiltered lookup: no publish/removed filter. Used internally after
	// create/update (so the caller gets back exactly what it just wrote even if
	// it's a future scheduled draft), and by the ArticleByAnySlug service method
	// for callers - like the SvelteKit edit page - that need to load a draft or
	// future-scheduled article by its own author. There's no auth on this API,
	// so this is no more exposed than the existing unauthenticated mutations;
	// see backend/CLAUDE.md.
	GetArticleRowBySlug(ctx context.Context, slug string) (GetArticleRowBySlugRow, error)
	// Currently-active mandate/unique-member counts, same as
	// ListCommitteesWithCounts - the committee detail page shows these too.
	GetCommitteeByShortName(ctx context.Context, shortName pgtype.Text) (GetCommitteeByShortNameRow, error)
	// The season whose window covers right now, if any - internal/nollning
	// treats "at most one season active at a time" as an invariant (not
	// enforced at the DB level, since overlapping seasons would be an admin
	// data error, not a normal state).
	GetCurrentSeason(ctx context.Context) (NollningSeason, error)
	// Public lookup: hides soft-removed events, same visibility rule as
	// ListEvents. The old TS getEvent() applied no such filter at all (see
	// DESIGN.md's events section) - fixed here rather than replicated.
	GetEventBySlug(ctx context.Context, slug pgtype.Text) (GetEventBySlugRow, error)
	GetEventIDBySlug(ctx context.Context, slug pgtype.Text) (pgtype.UUID, error)
	// Unfiltered lookup: no removed_at filter. Used internally after
	// create/update, and by GetAny for callers - like an edit page - that need
	// to load an event regardless of soft-delete status.
	GetEventRowBySlug(ctx context.Context, slug pgtype.Text) (GetEventRowBySlugRow, error)
	// Constrained to POLICY/GUIDELINE, matching the old app's edit-lookup
	// query - the other enum values have no create/edit UI anywhere.
	GetGoverningDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	// Used to verify a caller posting "as" a mandate actually holds it.
	// custom_authors has no owner column in the schema (they're shared
	// personas, e.g. "Styrelsen"), so there's no equivalent check for those.
	GetMandateMemberID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetMarkdown(ctx context.Context, name string) (Markdown, error)
	GetMemberByStudentID(ctx context.Context, studentID pgtype.Text) (GetMemberByStudentIDRow, error)
	// Backs PhadderRoleFor's "nolla" branch.
	GetMemberNollaGroupID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Backs PhadderRoleFor's "phadder" branch: which group (if any) this
	// member holds an active phadder/uppdrag mandate pointed at.
	GetMemberPhadderGroupID(ctx context.Context, memberID pgtype.UUID) (pgtype.UUID, error)
	// Full column set for a member's own profile page, unlike
	// GetMemberByStudentID's minimal projection (built only for author
	// resolution).
	GetMemberProfile(ctx context.Context, studentID pgtype.Text) (GetMemberProfileRow, error)
	GetPhadderGroup(ctx context.Context, id pgtype.UUID) (PhadderGroup, error)
	// Joins the committee (name/shortName), unlike ListPositions/UpdatePosition -
	// the position detail page links/displays the committee without a second
	// request.
	GetPosition(ctx context.Context, id string) (GetPositionRow, error)
	GetRecurringEvent(ctx context.Context, id pgtype.UUID) (RecurringEvent, error)
	GetSeason(ctx context.Context, id pgtype.UUID) (NollningSeason, error)
	// include_deleted here means "also visible if deleted" (a union, unlike
	// ListSongs' show_deleted above, which is an exclusive toggle) - mirrors the
	// old app's detail-page load, which bypasses the deletedAt filter entirely
	// for a caller holding song:delete rather than requiring a separate
	// "viewing the trash" mode.
	GetSongBySlug(ctx context.Context, arg GetSongBySlugParams) (Song, error)
	// Backs IsStaben: does memberID hold a mandate, active today, on a position
	// belonging to committeeID.
	IsMemberActiveOnCommittee(ctx context.Context, arg IsMemberActiveOnCommitteeParams) (bool, error)
	// Optional apiName filter; joins member first/last name for studentId-scoped
	// rows (role-scoped rows have no member to join).
	ListAccessPolicies(ctx context.Context, apiName pgtype.Text) ([]ListAccessPoliciesRow, error)
	ListActiveAlerts(ctx context.Context) ([]Alert, error)
	// "Active" mirrors the old TS backend's author-options query: currently
	// within the mandate's start/end date range.
	ListActiveMandatesForMember(ctx context.Context, memberID pgtype.UUID) ([]ListActiveMandatesForMemberRow, error)
	// Unscoped (full history, not year-scoped) - the position detail page
	// groups a position's entire mandate history client-side by year for
	// historical study-year statistics, unlike the committee detail page's
	// single-year view. Includes class_year/class_programme for that stats
	// computation and the member's programme badge.
	ListAllMandatesForPosition(ctx context.Context, positionID string) ([]ListAllMandatesForPositionRow, error)
	ListArticleComments(ctx context.Context, articleID pgtype.UUID) ([]ListArticleCommentsRow, error)
	// Shared column list for the "joined article" shape: article + committee +
	// author (member / mandate+position / custom author) + comment & like
	// counts. Duplicated across ListArticles/GetArticleBySlug/GetArticleRowBySlug
	// because sqlc has no macro/fragment support.
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error)
	// Board positions (board_member=true, active=true) with their current
	// holder, one row per position (LEFT JOIN LATERAL picks at most the most
	// recently-started active mandate; NULL member fields mean vacant) - backs
	// GET /board. Staben redaction (hiding organizing-committee positions from
	// viewers without MemberSeeStaben) happens in committees.Service.ListBoard,
	// not here - this query returns the unredacted set.
	ListBoard(ctx context.Context) ([]ListBoardRow, error)
	ListClosedAlertIDsForMember(ctx context.Context, b pgtype.UUID) ([]pgtype.UUID, error)
	// Full fields + currently-active mandate/unique-member counts, for the
	// committee overview page (mirrors the old "about" page's query).
	ListCommitteesWithCounts(ctx context.Context) ([]ListCommitteesWithCountsRow, error)
	// Committees eligible for a committee medal - excludes the same fixed
	// short_name set the old app hardcoded (valb/other/dchip/medalj).
	ListCommitteesWithMedals(ctx context.Context) ([]ListCommitteesWithMedalsRow, error)
	// Unfiltered: the old TS backend restricted this list to custom authors
	// whose custom_author_roles matched one of the member's Keycloak-derived
	// roles (getDerivedRoles) - that role-derivation system isn't ported to Go
	// (see ../../DESIGN.md's Auth section on the mock RBAC gap), so for now
	// every member can choose from every custom author. Revisit once real
	// roles exist.
	ListCustomAuthors(ctx context.Context) ([]ListCustomAuthorsRow, error)
	ListDistinctAPINames(ctx context.Context) ([]string, error)
	ListDistinctSongCategories(ctx context.Context, includeDeleted pgtype.Bool) ([]pgtype.Text, error)
	ListDistinctSongMelodies(ctx context.Context, includeDeleted pgtype.Bool) ([]pgtype.Text, error)
	ListEmailAliasesForPosition(ctx context.Context, positionID string) ([]EmailAlias, error)
	ListEventComments(ctx context.Context, eventID pgtype.UUID) ([]ListEventCommentsRow, error)
	ListEventGoing(ctx context.Context, eventID pgtype.UUID) ([]ListEventGoingRow, error)
	ListEventInterested(ctx context.Context, eventID pgtype.UUID) ([]ListEventInterestedRow, error)
	// Every other occurrence in a recurring series, for a FUTURE/ALL edit or
	// delete. min_start_datetime narg'd out entirely (not just NULL) for ALL,
	// set for FUTURE (see internal/events.Service.Update/Delete).
	ListEventSiblings(ctx context.Context, arg ListEventSiblingsParams) ([]ListEventSiblingsRow, error)
	// Shared column list for the "joined event" shape: event + author (plain
	// member - events have no mandate/custom-author byline, see internal/events
	// doc comments) + comment/going/interested counts. Duplicated across
	// ListEvents/GetEventBySlug/GetEventRowBySlug because sqlc has no
	// macro/fragment support (same situation as articles.sql).
	// Ordering direction depends on 'past': upcoming events sort soonest-first
	// (ASC), past events sort most-recent-first (DESC). sqlc can't parameterize
	// ORDER BY directly, so both directions are expressed as CASE'd sort keys -
	// exactly one is non-null per row depending on 'past', the other ties (NULL)
	// and is ignored.
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListGoverningDocuments(ctx context.Context) ([]Document, error)
	// Full mandate history (not just currently-active, unlike
	// ListActiveMandatesForMember) for a member's profile page, joined to
	// position+committee for display.
	ListMandatesForMember(ctx context.Context, memberID pgtype.UUID) ([]ListMandatesForMemberRow, error)
	// All mandates (not just active-during-the-window ones) for a given member
	// set, that started before the cutoff - mirrors the old app's allMandates
	// query, which only bounds start_date (no end_date filter) since award
	// semesters are computed by intersecting with "after" in Go, not in SQL.
	ListMandatesForMembersBefore(ctx context.Context, arg ListMandatesForMembersBeforeParams) ([]ListMandatesForMembersBeforeRow, error)
	// Year-scoped (overlapping [year-01-01, year-12-31]), joined to member -
	// mirrors the committee detail page's year filter (GET /committees/{shortName}?year=).
	ListMandatesForPosition(ctx context.Context, arg ListMandatesForPositionParams) ([]ListMandatesForPositionRow, error)
	// Distinct members who held any mandate active during [start, end) - the
	// candidate set medalRecipients scopes its per-member computation to,
	// mirroring the old app's mandatesInAfter query exactly.
	ListMemberIDsWithMandateActiveDuring(ctx context.Context, arg ListMemberIDsWithMandateActiveDuringParams) ([]pgtype.UUID, error)
	// Full mandate history for one member, joined to board_member/committee_id
	// - everything memberMedals (src/lib/server/medals/medals.ts) needs to
	// compute that member's own medal semesters.
	ListMemberMandatesWithPosition(ctx context.Context, memberID pgtype.UUID) ([]ListMemberMandatesWithPositionRow, error)
	// Mirrors the old members-directory page's filter: both params are
	// optional (a NULL narg matches everything) - the old TS route required
	// classYear, but that was a SvelteKit-page UX constraint (it needed a
	// value to pre-fill a dropdown), not an intentional API restriction.
	ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error)
	ListMembersByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListMembersByIDsRow, error)
	ListNollorForGroup(ctx context.Context, nollningGroupID pgtype.UUID) ([]ListNollorForGroupRow, error)
	// Nolla/phadder counts alongside each group, mirroring
	// ListCommitteesWithCounts' count-subquery pattern.
	ListPhadderGroups(ctx context.Context, seasonID pgtype.UUID) ([]ListPhadderGroupsRow, error)
	// Distinct members holding a mandate tagged to this group (a member can in
	// principle hold more than one such mandate - see FindActivePhadderMandate).
	ListPhaddrarForGroup(ctx context.Context, phadderinid pgtype.UUID) ([]ListPhaddrarForGroupRow, error)
	// Mirrors hooks.server.helpers.ts's getAccessPolicies: a policy applies if
	// it's granted to any of the caller's derived roles, or to their
	// student_id specifically. Pass a NULL student_id for an anonymous caller
	// (no derived roles are ever real student ids) - "student_id = NULL" never
	// matches, which is the same no-op the old code got from Prisma ignoring
	// an undefined filter.
	ListPoliciesForRolesOrStudentID(ctx context.Context, arg ListPoliciesForRolesOrStudentIDParams) ([]string, error)
	ListPositions(ctx context.Context) ([]ListPositionsRow, error)
	ListSeasons(ctx context.Context) ([]NollningSeason, error)
	// show_deleted toggles between two mutually exclusive views (mirroring the
	// old app's "show-deleted" query param on the songbook list page): the
	// normal active-songs list (false/unset) or the trash view of only
	// soft-deleted songs (true) - never both at once, unlike GetSongBySlug's
	// include_deleted below, which unions.
	ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsForArticles(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListTagsForArticlesRow, error)
	ListTagsForEvents(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListTagsForEventsRow, error)
	RemoveArticleLike(ctx context.Context, arg RemoveArticleLikeParams) error
	RemoveEventGoing(ctx context.Context, arg RemoveEventGoingParams) error
	RemoveEventInterested(ctx context.Context, arg RemoveEventInterestedParams) error
	RestoreSong(ctx context.Context, id pgtype.UUID) error
	// Targeted single-field write: the caller's external scheduler task id,
	// recorded after scheduling a future publish succeeds. Deliberately
	// separate from UpdateArticle (which is full-replace) since this needs to
	// happen without the caller re-submitting the whole article.
	SetArticleScheduledID(ctx context.Context, arg SetArticleScheduledIDParams) error
	SetMandatePhadderGroup(ctx context.Context, arg SetMandatePhadderGroupParams) error
	SetMemberPhadderGroup(ctx context.Context, arg SetMemberPhadderGroupParams) error
	SoftDeleteAlert(ctx context.Context, id pgtype.UUID) error
	SoftDeleteArticle(ctx context.Context, slug string) error
	SoftDeleteEvent(ctx context.Context, id pgtype.UUID) error
	// Powers both FUTURE (min_start_datetime set) and ALL (narg'd out) series
	// deletes in one statement, unlike the per-row loop UpdateEvent needs (a
	// plain removed_at write has no per-row content to vary).
	SoftDeleteEventSeries(ctx context.Context, arg SoftDeleteEventSeriesParams) error
	SoftDeleteGoverningDocument(ctx context.Context, id pgtype.UUID) error
	SoftDeleteSong(ctx context.Context, id pgtype.UUID) error
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error)
	UpdateCommittee(ctx context.Context, arg UpdateCommitteeParams) (Committee, error)
	// Full-replace of content fields (same PUT-not-PATCH convention as
	// articles), plus this occurrence's own start/end datetime. author_id is
	// deliberately never reassigned here - see internal/events doc comments on
	// why events diverge from articles' "always re-attribute to the editor"
	// rule.
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (UpdateEventRow, error)
	UpdateGoverningDocument(ctx context.Context, arg UpdateGoverningDocumentParams) (Document, error)
	UpdateMandate(ctx context.Context, arg UpdateMandateParams) (UpdateMandateRow, error)
	UpdateMemberFoodPreference(ctx context.Context, arg UpdateMemberFoodPreferenceParams) (UpdateMemberFoodPreferenceRow, error)
	UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) (UpdateMemberProfileRow, error)
	UpdatePhadderGroup(ctx context.Context, arg UpdatePhadderGroupParams) (PhadderGroup, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (UpdatePositionRow, error)
	UpdateSeason(ctx context.Context, arg UpdateSeasonParams) (NollningSeason, error)
	UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error)
	UpsertMarkdown(ctx context.Context, arg UpsertMarkdownParams) (Markdown, error)
}

var _ Querier = (*Queries)(nil)
