// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddArticleLike(ctx context.Context, arg AddArticleLikeParams) error
	AddArticleTags(ctx context.Context, arg AddArticleTagsParams) error
	ClearArticleTags(ctx context.Context, articleID pgtype.UUID) error
	CountArticleSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountArticles(ctx context.Context, arg CountArticlesParams) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error)
	CreateArticleComment(ctx context.Context, arg CreateArticleCommentParams) (CreateArticleCommentRow, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (pgtype.UUID, error)
	// Minimal port of src/lib/utils/member.ts's createMember: this backend
	// doesn't own subscription_settings or tag subscriptions (nollning-period
	// defaults included), so this only creates the bare Member row those
	// features would otherwise hang off of - a deliberate gap, not an
	// oversight, consistent with nollning being out of scope elsewhere in this
	// rewrite (see DESIGN.md).
	CreateMember(ctx context.Context, arg CreateMemberParams) (CreateMemberRow, error)
	DeleteArticleComment(ctx context.Context, arg DeleteArticleCommentParams) error
	// Authors are reused across articles: an author row is the (member,
	// mandate, custom-author) triple, so the same byline is only created once.
	FindAuthor(ctx context.Context, arg FindAuthorParams) (pgtype.UUID, error)
	// Used only to seed the mock auth identity in dev when no specific member
	// is configured (see internal/auth, main.go). Arbitrary but deterministic
	// enough for local dev: whichever member sorts first by id.
	GetAnyMember(ctx context.Context) (GetAnyMemberRow, error)
	// Public lookup: only published, not (currently) removed articles.
	GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error)
	GetArticleIDBySlug(ctx context.Context, slug string) (pgtype.UUID, error)
	// Unfiltered lookup: no publish/removed filter. Used internally after
	// create/update (so the caller gets back exactly what it just wrote even if
	// it's a future scheduled draft), and by the ArticleByAnySlug service method
	// for callers - like the SvelteKit edit page - that need to load a draft or
	// future-scheduled article by its own author. There's no auth on this API,
	// so this is no more exposed than the existing unauthenticated mutations;
	// see backend/CLAUDE.md.
	GetArticleRowBySlug(ctx context.Context, slug string) (GetArticleRowBySlugRow, error)
	// Used to verify a caller posting "as" a mandate actually holds it.
	// custom_authors has no owner column in the schema (they're shared
	// personas, e.g. "Styrelsen"), so there's no equivalent check for those.
	GetMandateMemberID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetMemberByStudentID(ctx context.Context, studentID pgtype.Text) (GetMemberByStudentIDRow, error)
	// "Active" mirrors the old TS backend's author-options query: currently
	// within the mandate's start/end date range.
	ListActiveMandatesForMember(ctx context.Context, memberID pgtype.UUID) ([]ListActiveMandatesForMemberRow, error)
	ListArticleComments(ctx context.Context, articleID pgtype.UUID) ([]ListArticleCommentsRow, error)
	// Shared column list for the "joined article" shape: article + committee +
	// author (member / mandate+position / custom author) + comment & like
	// counts. Duplicated across ListArticles/GetArticleBySlug/GetArticleRowBySlug
	// because sqlc has no macro/fragment support.
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error)
	ListCommittees(ctx context.Context, shortName pgtype.Text) ([]ListCommitteesRow, error)
	// Unfiltered: the old TS backend restricted this list to custom authors
	// whose custom_author_roles matched one of the member's Keycloak-derived
	// roles (getDerivedRoles) - that role-derivation system isn't ported to Go
	// (see ../../DESIGN.md's Auth section on the mock RBAC gap), so for now
	// every member can choose from every custom author. Revisit once real
	// roles exist.
	ListCustomAuthors(ctx context.Context) ([]ListCustomAuthorsRow, error)
	// Mirrors hooks.server.helpers.ts's getAccessPolicies: a policy applies if
	// it's granted to any of the caller's derived roles, or to their
	// student_id specifically. Pass a NULL student_id for an anonymous caller
	// (no derived roles are ever real student ids) - "student_id = NULL" never
	// matches, which is the same no-op the old code got from Prisma ignoring
	// an undefined filter.
	ListPoliciesForRolesOrStudentID(ctx context.Context, arg ListPoliciesForRolesOrStudentIDParams) ([]string, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsForArticles(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListTagsForArticlesRow, error)
	RemoveArticleLike(ctx context.Context, arg RemoveArticleLikeParams) error
	// Targeted single-field write: the caller's external scheduler task id,
	// recorded after scheduling a future publish succeeds. Deliberately
	// separate from UpdateArticle (which is full-replace) since this needs to
	// happen without the caller re-submitting the whole article.
	SetArticleScheduledID(ctx context.Context, arg SetArticleScheduledIDParams) error
	SoftDeleteArticle(ctx context.Context, slug string) error
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (UpdateArticleRow, error)
}

var _ Querier = (*Queries)(nil)
