// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: songs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSongSlugsWithPrefix = `-- name: CountSongSlugsWithPrefix :one
SELECT count(*) FROM songs WHERE slug LIKE $1 || '%'
`

func (q *Queries) CountSongSlugsWithPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSongSlugsWithPrefix, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSongs = `-- name: CountSongs :one
SELECT count(*) FROM songs
WHERE (
    CASE WHEN $1::bool IS TRUE THEN deleted_at IS NOT NULL ELSE deleted_at IS NULL END
  )
  AND (
    $2::text IS NULL
    OR title ILIKE '%' || $2::text || '%'
    OR lyrics ILIKE '%' || $2::text || '%'
    OR melody ILIKE '%' || $2::text || '%'
  )
  AND (
    $3::text[] IS NULL
    OR EXISTS (
        SELECT 1 FROM unnest($3::text[]) c
        WHERE category ILIKE '%' || c || '%'
    )
  )
`

type CountSongsParams struct {
	ShowDeleted pgtype.Bool `json:"show_deleted"`
	Search      pgtype.Text `json:"search"`
	Categories  []string    `json:"categories"`
}

func (q *Queries) CountSongs(ctx context.Context, arg CountSongsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSongs, arg.ShowDeleted, arg.Search, arg.Categories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSong = `-- name: CreateSong :one
INSERT INTO songs (title, lyrics, melody, category, video, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING id, title, lyrics, melody, category, created_at, updated_at, deleted_at, slug, video
`

type CreateSongParams struct {
	Title    string      `json:"title"`
	Lyrics   string      `json:"lyrics"`
	Melody   pgtype.Text `json:"melody"`
	Category pgtype.Text `json:"category"`
	Video    pgtype.Text `json:"video"`
	Slug     string      `json:"slug"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.Title,
		arg.Lyrics,
		arg.Melody,
		arg.Category,
		arg.Video,
		arg.Slug,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Lyrics,
		&i.Melody,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
		&i.Video,
	)
	return i, err
}

const getSongBySlug = `-- name: GetSongBySlug :one
SELECT id, title, lyrics, melody, category, created_at, updated_at, deleted_at, slug, video
FROM songs
WHERE slug = $1 AND ($2::bool IS TRUE OR deleted_at IS NULL)
`

type GetSongBySlugParams struct {
	Slug           string      `json:"slug"`
	IncludeDeleted pgtype.Bool `json:"include_deleted"`
}

// include_deleted here means "also visible if deleted" (a union, unlike
// ListSongs' show_deleted above, which is an exclusive toggle) - mirrors the
// old app's detail-page load, which bypasses the deletedAt filter entirely
// for a caller holding song:delete rather than requiring a separate
// "viewing the trash" mode.
func (q *Queries) GetSongBySlug(ctx context.Context, arg GetSongBySlugParams) (Song, error) {
	row := q.db.QueryRow(ctx, getSongBySlug, arg.Slug, arg.IncludeDeleted)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Lyrics,
		&i.Melody,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
		&i.Video,
	)
	return i, err
}

const listDistinctSongCategories = `-- name: ListDistinctSongCategories :many
SELECT DISTINCT category FROM songs
WHERE category IS NOT NULL
  AND ($1::bool IS TRUE OR deleted_at IS NULL)
ORDER BY category
`

func (q *Queries) ListDistinctSongCategories(ctx context.Context, includeDeleted pgtype.Bool) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listDistinctSongCategories, includeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var category pgtype.Text
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSongMelodies = `-- name: ListDistinctSongMelodies :many
SELECT DISTINCT melody FROM songs
WHERE melody IS NOT NULL
  AND ($1::bool IS TRUE OR deleted_at IS NULL)
ORDER BY melody
`

func (q *Queries) ListDistinctSongMelodies(ctx context.Context, includeDeleted pgtype.Bool) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listDistinctSongMelodies, includeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var melody pgtype.Text
		if err := rows.Scan(&melody); err != nil {
			return nil, err
		}
		items = append(items, melody)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongs = `-- name: ListSongs :many
SELECT id, title, lyrics, melody, category, created_at, updated_at, deleted_at, slug, video
FROM songs
WHERE (
    CASE WHEN $3::bool IS TRUE THEN deleted_at IS NOT NULL ELSE deleted_at IS NULL END
  )
  AND (
    $4::text IS NULL
    OR title ILIKE '%' || $4::text || '%'
    OR lyrics ILIKE '%' || $4::text || '%'
    OR melody ILIKE '%' || $4::text || '%'
  )
  AND (
    $5::text[] IS NULL
    OR EXISTS (
        SELECT 1 FROM unnest($5::text[]) c
        WHERE category ILIKE '%' || c || '%'
    )
  )
ORDER BY title ASC
LIMIT $1 OFFSET $2
`

type ListSongsParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	ShowDeleted pgtype.Bool `json:"show_deleted"`
	Search      pgtype.Text `json:"search"`
	Categories  []string    `json:"categories"`
}

// show_deleted toggles between two mutually exclusive views (mirroring the
// old app's "show-deleted" query param on the songbook list page): the
// normal active-songs list (false/unset) or the trash view of only
// soft-deleted songs (true) - never both at once, unlike GetSongBySlug's
// include_deleted below, which unions.
func (q *Queries) ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongs,
		arg.Limit,
		arg.Offset,
		arg.ShowDeleted,
		arg.Search,
		arg.Categories,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Lyrics,
			&i.Melody,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Slug,
			&i.Video,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSong = `-- name: RestoreSong :exec
UPDATE songs SET deleted_at = NULL WHERE id = $1
`

func (q *Queries) RestoreSong(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreSong, id)
	return err
}

const softDeleteSong = `-- name: SoftDeleteSong :exec
UPDATE songs SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteSong(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSong, id)
	return err
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET title = $2, lyrics = $3, melody = $4, category = $5, video = $6, updated_at = now()
WHERE id = $1
RETURNING id, title, lyrics, melody, category, created_at, updated_at, deleted_at, slug, video
`

type UpdateSongParams struct {
	ID       pgtype.UUID `json:"id"`
	Title    string      `json:"title"`
	Lyrics   string      `json:"lyrics"`
	Melody   pgtype.Text `json:"melody"`
	Category pgtype.Text `json:"category"`
	Video    pgtype.Text `json:"video"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, updateSong,
		arg.ID,
		arg.Title,
		arg.Lyrics,
		arg.Melody,
		arg.Category,
		arg.Video,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Lyrics,
		&i.Melody,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Slug,
		&i.Video,
	)
	return i, err
}
