// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stocklist.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustDrinkItemQuantity = `-- name: AdjustDrinkItemQuantity :one
UPDATE drinkitem SET
    quantity_available = COALESCE(quantity_available, 0) + $1::int,
    nr_bottles = COALESCE(nr_bottles, 0) + $2::int
WHERE id = $3
  AND COALESCE(quantity_available, 0) + $1::int >= 0
  AND COALESCE(nr_bottles, 0) + $2::int >= 0
RETURNING id, quantity_type, name, price, "group", systembolaget_id,
          bottle_empty_weight, bottle_full_weight, quantity_available, nr_bottles
`

type AdjustDrinkItemQuantityParams struct {
	QuantityDelta  int32       `json:"quantity_delta"`
	NrBottlesDelta int32       `json:"nr_bottles_delta"`
	ID             pgtype.UUID `json:"id"`
}

// Atomically applies a signed adjustment to quantity_available/nr_bottles,
// guarded so neither can go negative (returns zero rows, not an error, if
// the guard would be violated - the caller distinguishes "not found" from
// "insufficient stock" itself). Used by every stocklist write path that
// touches an item's running totals: CreateBatch (the delta itself),
// UpdateBatch/DeleteBatch (the net difference between old and new/removed
// delta) - unifying what the old app implemented as three separate
// ad-hoc Prisma transactions into one atomic SQL statement.
func (q *Queries) AdjustDrinkItemQuantity(ctx context.Context, arg AdjustDrinkItemQuantityParams) (Drinkitem, error) {
	row := q.db.QueryRow(ctx, adjustDrinkItemQuantity, arg.QuantityDelta, arg.NrBottlesDelta, arg.ID)
	var i Drinkitem
	err := row.Scan(
		&i.ID,
		&i.QuantityType,
		&i.Name,
		&i.Price,
		&i.Group,
		&i.SystembolagetID,
		&i.BottleEmptyWeight,
		&i.BottleFullWeight,
		&i.QuantityAvailable,
		&i.NrBottles,
	)
	return i, err
}

const createDrinkItem = `-- name: CreateDrinkItem :one
INSERT INTO drinkitem (
    quantity_type, name, price, "group", systembolaget_id,
    bottle_empty_weight, bottle_full_weight
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
RETURNING id, quantity_type, name, price, "group", systembolaget_id,
          bottle_empty_weight, bottle_full_weight, quantity_available, nr_bottles
`

type CreateDrinkItemParams struct {
	QuantityType      DrinkQuantityType `json:"quantity_type"`
	Name              string            `json:"name"`
	Price             int32             `json:"price"`
	Group             DrinkGroup        `json:"group"`
	SystembolagetID   int32             `json:"systembolaget_id"`
	BottleEmptyWeight pgtype.Int4       `json:"bottle_empty_weight"`
	BottleFullWeight  pgtype.Int4       `json:"bottle_full_weight"`
}

func (q *Queries) CreateDrinkItem(ctx context.Context, arg CreateDrinkItemParams) (Drinkitem, error) {
	row := q.db.QueryRow(ctx, createDrinkItem,
		arg.QuantityType,
		arg.Name,
		arg.Price,
		arg.Group,
		arg.SystembolagetID,
		arg.BottleEmptyWeight,
		arg.BottleFullWeight,
	)
	var i Drinkitem
	err := row.Scan(
		&i.ID,
		&i.QuantityType,
		&i.Name,
		&i.Price,
		&i.Group,
		&i.SystembolagetID,
		&i.BottleEmptyWeight,
		&i.BottleFullWeight,
		&i.QuantityAvailable,
		&i.NrBottles,
	)
	return i, err
}

const createDrinkItemBatch = `-- name: CreateDrinkItemBatch :one
INSERT INTO drinkitembatch (drink_item_id, "user", date, quantity_delta, nr_bottles_delta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, drink_item_id, "user", date, quantity_delta, nr_bottles_delta
`

type CreateDrinkItemBatchParams struct {
	DrinkItemID    pgtype.UUID      `json:"drink_item_id"`
	User           string           `json:"user"`
	Date           pgtype.Timestamp `json:"date"`
	QuantityDelta  int32            `json:"quantity_delta"`
	NrBottlesDelta pgtype.Int4      `json:"nr_bottles_delta"`
}

func (q *Queries) CreateDrinkItemBatch(ctx context.Context, arg CreateDrinkItemBatchParams) (Drinkitembatch, error) {
	row := q.db.QueryRow(ctx, createDrinkItemBatch,
		arg.DrinkItemID,
		arg.User,
		arg.Date,
		arg.QuantityDelta,
		arg.NrBottlesDelta,
	)
	var i Drinkitembatch
	err := row.Scan(
		&i.ID,
		&i.DrinkItemID,
		&i.User,
		&i.Date,
		&i.QuantityDelta,
		&i.NrBottlesDelta,
	)
	return i, err
}

const deleteDrinkItem = `-- name: DeleteDrinkItem :execrows
DELETE FROM drinkitem WHERE id = $1
`

func (q *Queries) DeleteDrinkItem(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDrinkItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDrinkItemBatch = `-- name: DeleteDrinkItemBatch :execrows
DELETE FROM drinkitembatch WHERE id = $1
`

func (q *Queries) DeleteDrinkItemBatch(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDrinkItemBatch, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDrinkItemBatchByID = `-- name: GetDrinkItemBatchByID :one
SELECT id, drink_item_id, "user", date, quantity_delta, nr_bottles_delta
FROM drinkitembatch
WHERE id = $1
`

func (q *Queries) GetDrinkItemBatchByID(ctx context.Context, id pgtype.UUID) (Drinkitembatch, error) {
	row := q.db.QueryRow(ctx, getDrinkItemBatchByID, id)
	var i Drinkitembatch
	err := row.Scan(
		&i.ID,
		&i.DrinkItemID,
		&i.User,
		&i.Date,
		&i.QuantityDelta,
		&i.NrBottlesDelta,
	)
	return i, err
}

const listAvailableDrinkItems = `-- name: ListAvailableDrinkItems :many
SELECT id, quantity_type, name, price, "group", systembolaget_id,
       bottle_empty_weight, bottle_full_weight, quantity_available, nr_bottles
FROM drinkitem
WHERE quantity_available > 0
ORDER BY name ASC
`

func (q *Queries) ListAvailableDrinkItems(ctx context.Context) ([]Drinkitem, error) {
	rows, err := q.db.Query(ctx, listAvailableDrinkItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Drinkitem{}
	for rows.Next() {
		var i Drinkitem
		if err := rows.Scan(
			&i.ID,
			&i.QuantityType,
			&i.Name,
			&i.Price,
			&i.Group,
			&i.SystembolagetID,
			&i.BottleEmptyWeight,
			&i.BottleFullWeight,
			&i.QuantityAvailable,
			&i.NrBottles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrinkItemBatches = `-- name: ListDrinkItemBatches :many
SELECT b.id, b.drink_item_id, b."user", b.date, b.quantity_delta, b.nr_bottles_delta,
       i.name AS item_name, i.price AS item_price, i.quantity_type AS item_quantity_type,
       i."group" AS item_group
FROM drinkitembatch b
JOIN drinkitem i ON i.id = b.drink_item_id
WHERE $1::timestamp IS NULL OR b.date <= $1::timestamp
ORDER BY b.date DESC
`

type ListDrinkItemBatchesRow struct {
	ID               pgtype.UUID       `json:"id"`
	DrinkItemID      pgtype.UUID       `json:"drink_item_id"`
	User             string            `json:"user"`
	Date             pgtype.Timestamp  `json:"date"`
	QuantityDelta    int32             `json:"quantity_delta"`
	NrBottlesDelta   pgtype.Int4       `json:"nr_bottles_delta"`
	ItemName         string            `json:"item_name"`
	ItemPrice        int32             `json:"item_price"`
	ItemQuantityType DrinkQuantityType `json:"item_quantity_type"`
	ItemGroup        DrinkGroup        `json:"item_group"`
}

// Every batch entry (optionally only those on/before before_date), joined
// with its item, newest first - matches treasury/+page.server.ts's load
// exactly (before_date unset = every entry).
func (q *Queries) ListDrinkItemBatches(ctx context.Context, beforeDate pgtype.Timestamp) ([]ListDrinkItemBatchesRow, error) {
	rows, err := q.db.Query(ctx, listDrinkItemBatches, beforeDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDrinkItemBatchesRow{}
	for rows.Next() {
		var i ListDrinkItemBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.DrinkItemID,
			&i.User,
			&i.Date,
			&i.QuantityDelta,
			&i.NrBottlesDelta,
			&i.ItemName,
			&i.ItemPrice,
			&i.ItemQuantityType,
			&i.ItemGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrinkItems = `-- name: ListDrinkItems :many
SELECT id, quantity_type, name, price, "group", systembolaget_id,
       bottle_empty_weight, bottle_full_weight, quantity_available, nr_bottles
FROM drinkitem
ORDER BY name ASC
`

func (q *Queries) ListDrinkItems(ctx context.Context) ([]Drinkitem, error) {
	rows, err := q.db.Query(ctx, listDrinkItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Drinkitem{}
	for rows.Next() {
		var i Drinkitem
		if err := rows.Scan(
			&i.ID,
			&i.QuantityType,
			&i.Name,
			&i.Price,
			&i.Group,
			&i.SystembolagetID,
			&i.BottleEmptyWeight,
			&i.BottleFullWeight,
			&i.QuantityAvailable,
			&i.NrBottles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrinkItem = `-- name: UpdateDrinkItem :one
UPDATE drinkitem SET
    name = $1,
    price = $2,
    "group" = $3,
    systembolaget_id = $4,
    bottle_empty_weight = $5,
    bottle_full_weight = $6
WHERE id = $7
RETURNING id, quantity_type, name, price, "group", systembolaget_id,
          bottle_empty_weight, bottle_full_weight, quantity_available, nr_bottles
`

type UpdateDrinkItemParams struct {
	Name              string      `json:"name"`
	Price             int32       `json:"price"`
	Group             DrinkGroup  `json:"group"`
	SystembolagetID   int32       `json:"systembolaget_id"`
	BottleEmptyWeight pgtype.Int4 `json:"bottle_empty_weight"`
	BottleFullWeight  pgtype.Int4 `json:"bottle_full_weight"`
	ID                pgtype.UUID `json:"id"`
}

// Mirrors showproducts' updateSchema exactly - quantityType is not
// editable via this action (only set at creation), matching the old form's
// own field set.
func (q *Queries) UpdateDrinkItem(ctx context.Context, arg UpdateDrinkItemParams) (Drinkitem, error) {
	row := q.db.QueryRow(ctx, updateDrinkItem,
		arg.Name,
		arg.Price,
		arg.Group,
		arg.SystembolagetID,
		arg.BottleEmptyWeight,
		arg.BottleFullWeight,
		arg.ID,
	)
	var i Drinkitem
	err := row.Scan(
		&i.ID,
		&i.QuantityType,
		&i.Name,
		&i.Price,
		&i.Group,
		&i.SystembolagetID,
		&i.BottleEmptyWeight,
		&i.BottleFullWeight,
		&i.QuantityAvailable,
		&i.NrBottles,
	)
	return i, err
}

const updateDrinkItemBatch = `-- name: UpdateDrinkItemBatch :one
UPDATE drinkitembatch SET
    quantity_delta = $1,
    nr_bottles_delta = $2
WHERE id = $3
RETURNING id, drink_item_id, "user", date, quantity_delta, nr_bottles_delta
`

type UpdateDrinkItemBatchParams struct {
	QuantityDelta  int32       `json:"quantity_delta"`
	NrBottlesDelta pgtype.Int4 `json:"nr_bottles_delta"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDrinkItemBatch(ctx context.Context, arg UpdateDrinkItemBatchParams) (Drinkitembatch, error) {
	row := q.db.QueryRow(ctx, updateDrinkItemBatch, arg.QuantityDelta, arg.NrBottlesDelta, arg.ID)
	var i Drinkitembatch
	err := row.Scan(
		&i.ID,
		&i.DrinkItemID,
		&i.User,
		&i.Date,
		&i.QuantityDelta,
		&i.NrBottlesDelta,
	)
	return i, err
}
