// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addArticleTags = `-- name: AddArticleTags :exec
INSERT INTO _article_tags ("A", "B")
SELECT $1, unnest($2::uuid[])
ON CONFLICT ("A", "B") DO NOTHING
`

type AddArticleTagsParams struct {
	ArticleID pgtype.UUID   `json:"article_id"`
	TagIds    []pgtype.UUID `json:"tag_ids"`
}

func (q *Queries) AddArticleTags(ctx context.Context, arg AddArticleTagsParams) error {
	_, err := q.db.Exec(ctx, addArticleTags, arg.ArticleID, arg.TagIds)
	return err
}

const clearArticleTags = `-- name: ClearArticleTags :exec
DELETE FROM _article_tags WHERE "A" = $1
`

func (q *Queries) ClearArticleTags(ctx context.Context, articleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearArticleTags, articleID)
	return err
}

const listTags = `-- name: ListTags :many
SELECT id, name_sv, name_en, color, is_default FROM tags ORDER BY name_sv
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.Color,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForArticles = `-- name: ListTagsForArticles :many
SELECT t."A" AS article_id, tags.id, tags.name_sv, tags.name_en, tags.color, tags.is_default
FROM _article_tags t
JOIN tags ON tags.id = t."B"
WHERE t."A" = ANY($1::uuid[])
ORDER BY tags.name_sv
`

type ListTagsForArticlesRow struct {
	ArticleID pgtype.UUID `json:"article_id"`
	ID        pgtype.UUID `json:"id"`
	NameSv    string      `json:"name_sv"`
	NameEn    pgtype.Text `json:"name_en"`
	Color     pgtype.Text `json:"color"`
	IsDefault pgtype.Bool `json:"is_default"`
}

func (q *Queries) ListTagsForArticles(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListTagsForArticlesRow, error) {
	rows, err := q.db.Query(ctx, listTagsForArticles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForArticlesRow{}
	for rows.Next() {
		var i ListTagsForArticlesRow
		if err := rows.Scan(
			&i.ArticleID,
			&i.ID,
			&i.NameSv,
			&i.NameEn,
			&i.Color,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
