name: "Close stale PRs"
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          stale-pr-message: "This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 14 days."
          close-pr-message: "This PR was closed because it has been stalled for 14 days with no activity."
          days-before-stale: 30
          days-before-issue-stale: -1
          days-before-close: 14
          days-before-issue-close: -1
          debug-only: true
